### ISSUE TITLE
have_received with block argument is nil

### ISSUE THREAD

**Issue by patrick99e99** [rspec/rspec-mocks#1003]
If I do:

    subject
    expect(foo).to have_received(:bar) {|&block| expect(block.call).to eq 'something' }

I get undefined method call for nil class-- block is nil inside the block.

But if I do:

    expect(foo).to receive(:bar) {|&block| expect(block.call).to eq 'something' }
    subject

Then it works.

**Comment by myronmarston** [comment]
Thanks for reporting this!  I've got a fix in #1003.
