### ISSUE TITLE
have_received(:method).with(object1, object2) fails in 3.3.3 but not in 3.2.1

### ISSUE THREAD

**Issue by bunnymatic** [rspec/rspec-mocks#1005]
We had a spec like this

```
describe '#my_method' do
    before do
      MyService.new(obj).my_method
    end
    it 'calls the nested method with the right args' do
     expect(inner_object).to have_received(:my_nested_method).with(object1, object2)
    end
  end
end
```

where object1, and object2 are both ActiveRecord objects. 
In 3.2.1, this test passed.  After the upgrade, it failed.  The failure report reads (roughly):

```
expected:  Object(id => 1), Object( id => 3)
         got:  Object(id => 1), Object( id => 3)
Diff:

```

At first glance, it seems like the `expected` and `got` are, in fact, the same thing.  And the `Diff` shows empty.  I wonder if this is something about how the equality is computed.  I noticed a bunch of checkins in the CHANGELOG around how `have_received` is working.

I'll try to put together a more isolated concrete example.

**Comment by myronmarston** [comment]
I can't think of any changes between 3.2.1 and 3.3.2 that would cause this.

> I'll try to put together a more isolated concrete example.

That would be great -- without that we have no way to guess at the specific circumstances of your failure.

**Comment by bunnymatic** [comment]
Ok... i think i figured it out.  The output from Rspec was misleading.

The two objects that are passed in are Presenters built using SimpleDelegator.  The expected objects (in the with) were the base models, not presenters.  Something in the `to_s` was obscuring the fact that the actual values used when the method was called were the Presenter versions.  I'm not sure who's bug this is to fix (if anyones). 

For now, I can close this as it's not really your issue.

Cheers
