### ISSUE TITLE
Proxy method with assertions

### ISSUE THREAD

**Issue by rwz** [rspec/rspec-mocks#1008]
At Heroku we're doing a massive refactoring of one of our biggest apps from using [RR](https://github.com/rr/rr) mocking library to pure rspec/rspec-mocks and one of the problems we're facing is the absence of "proxying" assertions.

To give you an example, in RR it's possible to do something like this:

```ruby
mock.proxy(MyObject).my_method(1,2,3)
```

which is roughly equivalent to Rspec's:

```ruby
original_method = MyObject.method(:my_method)
expect(MyObject).to receive(:my_method).with(1,2,3) do |*args|
  original_method.call(*args)
end
```

Basically, it creates an expectation AND still allows the method body to be executed.
One could argue that this is not the optimal way to test behavior, but we already have TONS of code written and tested that way.

I've searched around and it seems like Rspec is lacking a native support for such assertion technique or at least it's not mentioned in the documentation. There're a few StackOverflow questions about that and all they can offer is a bunch of variations of the rspec example above, which is clearly not the most elegant solution.

I've briefly looked through the code of this gem and saw some mentions of VerifyingProxy and other code that looks like it could be used to give us the behavior we're looking for.

So my question is, is there any way to recreate this assertion technique in RSpec using only the existing code and if yes, is there any documentation available around that?

If not, what would be the most BDD-friendly way of tackling the problem? We'd like to minimize the amount of custom homegrown RSpec extensions to support.

**Comment by myronmarston** [comment]
RSpec does support this directly:

``` ruby
expect(MyObject).to receive(:my_method).with(1, 2, 3).and_call_original
```

Or, if you want to "wrap" the original and not just call it:

``` ruby
expect(MyObject).to receive(:my_method).with(1, 2, 3).and_wrap_original do |original_method, *args|
  # you can modify the args before delegating to the original or do something with the return value here
  original_method.call(*args)
end
```

These are highlighted in our docs on configuring responses:

https://relishapp.com/rspec/rspec-mocks/v/3-3/docs/configuring-responses

Is there a way we could make these more visible?
