### ISSUE TITLE
Request for help to clean custom DSL

### ISSUE THREAD

**Issue by fgarcia** [rspec/rspec-mocks#1011]
I am trying to write a custom DSL to do some "unethical" hack in my classes. Basically I want to prevent the definition of mocks/stubs in my specs and instead define named mocks/stubs directly into my classes. Something like this:

    class Person
      attr_reader :name
      attr_reader :mood

      def initialize(name, mood = 'happy')
        @name = name
        @mood = mood
      end

      stubs do
        def grumpy
          allow.to receive(:mood) { 'grumpy' }
        end
      end
    end

Now in my Specs I can have named stubs like this:

    describe Person do
      it 'demo' do
        expect(subject.name).to eq "fran_1"
        expect(subject.mood).to eq "happy"

        subject.stub! self, :grumpy
        expect(subject.mood).to eq "grumpy"
      end
    end

This is my current DSL code:

    module StubsDSL
      Stubs = Module.new
      def self.stubs(&block)
        Stubs.module_eval(&block)
        extend Stubs
      end
      
      def stub!(who, method, *args)
        this = self
        unbound = Stubs.instance_method method
        who.instance_eval do
          @this = this
          def allow
            super(@this)
          end
          unbound.bind(who).call
        end
      end
    end

I've been exploring rspec-mocks source code, but I am a bit lost between Proxy / Space objects and how everything works together.  Above all things I want to monkey patch Rspec to replace the old #stub implemention without the warnings. Something like this:

     subject.stub :grumpy

I also believe the function `stub!(who, method, *args)` could be moved somewhere else like inside RSpec::Mocks::Syntax, but I am not sure how

Any help would be greatly welcome!

I know this sounds like a quite dirty hack, but I am trying to learn more about Rspec internals and test some ideas

**Comment by JonRowe** [comment]
We provide methods for removing the 'should' syntax from use in RSpec, this should allow you to monkey patch your own methods in without encountering warnings (as it's simply not going through our code), I wouldn't recommend trying to add your own `stub!` method to our syntax definition, just define your own syntax module and include that were you need it.

**Comment by JonRowe** [comment]
If you look how we define our `allow` `expect` methods, this will also give you an idea how to define your own to setup our stubs as we expect, but using your own style of syntax.

**Comment by JonRowe** [comment]
Closing as this isn't an issue / feature request, happy to continue discussing / helping you to achieve your goals :)
