### ISSUE TITLE
argument matcher: array_matching

### ISSUE THREAD

**Issue by jvenezia** [rspec/rspec-mocks#1014]
What do you think about `array_matching` wich checks if array matches regardless the order of the elements? I think this should be a default argument matcher. I'll pull-request this if you think it's a good idea.

```ruby
 expect(object).to receive(:message).with(array_matching([1,2,3])) #=> object.message([2, 3, 1])
```

**Comment by myronmarston** [comment]
What you're looking for is already available from rspec-expectations as `a_collection_containing_exactly`

http://rspec.info/documentation/3.3/rspec-expectations/RSpec/Matchers.html#contain_exactly-instance_method

If you want to be able to use `array_matching`, you can just use [`alias_matcher`](http://rspec.info/documentation/3.3/rspec-expectations/RSpec/Matchers.html#alias_matcher-class_method) to define that.

Anyhow, as discussed in #513 we don't want to keep adding new matchers to rspec-mocks right now as there's already a bit of a confusion-causing duplication between (but, in some cases, slightly different behavior) between rspec-mocks and rspec-expectations.

**Comment by jvenezia** [comment]
Thanks @myronmarston !

**Comment by LandonSchropp** [comment]
For anyone who runs across this issue in the future, it looks like `match_array` will work as well with a slightly different API.

```
expect(object).to receive(:message).with(match_array([1,2,3]))
```
