### ISSUE TITLE
Stubbing class from another gem does not stub when verify_partial_mocks is true

### ISSUE THREAD

**Issue by jfelchner** [rspec/rspec-mocks#1019]
I'm not 100% sure on the reproduction here so let me try to explain as best I can.  This started happening on `3.3`.  `3.2` works just fine.

We have a gem which imports another gem (they're both engines if it matters).  Let's call the gem I'm working in `Gem` and the gem I have as a requirement `RequiredGem`.

I can stub:

```ruby
allow(Gem).to receive(:my_class_method)
```

all day long.  Works fine.  But if I try to stub:

```ruby
allow(RequiredGem).to receive(:my_required_method)
```

it does not stub and instead calls the original method.

This happens _only_ when `verify_partial_mocks` is true.

**Comment by jfelchner** [comment]
To help you all narrow it down I tried it with `3.3.0`, `3.3.1` and `3.3.2`.  It's `3.3.0` where the problem was introduced.

**Comment by myronmarston** [comment]
Thanks.  Any chance you could put together a reproducible example?  Or maybe if you could run `git bisect` between 3.2.0 and 3.3.0 it would pin down the problem commit.

**Comment by jfelchner** [comment]
@myronmarston I'll be happy to bisect for you :)

**Comment by jfelchner** [comment]
@myronmarston looks like e5bfbcb75bca581924697ab0e9fd9447e9257b76 is the first bad commit.  Looking at it I can't see why, but that's what `git bisect` told me.

**Comment by JonRowe** [comment]
That should only affect ActiveRecord based models, but it's possible theres a side effect going on, can you try the bisect on rspec-rails itself?

**Comment by jfelchner** [comment]
@JonRowe I absolutely can and yes, it is an `ActiveRecord` object. As I said it's an engine so there are AR objects in there.

**Comment by jfelchner** [comment]
But it's also the case that I can stub AR objects in the engine under test just fine, but I have dependent engines which also have AR objects and that one fails.  I don't know if that's the actual reason for the failure but I'm just trying to give you as much info as possible.

**Comment by jfelchner** [comment]
@JonRowe this has been a couple months and, although the problem still exists, I've had to turn my attention to other projects.  Feel free to close this if you deem it necessary.

**Comment by JonRowe** [comment]
I think this belongs as an issue with rspec-rails, if you can provide a reproduction feel free to open there.
