### ISSUE TITLE
BooksController :create action test with rails 4.2 and rspec

### ISSUE THREAD

**Issue by ulugbekov** [rspec/rspec-mocks#1031]
```
describe BooksController do
 describe 'POST create' do
    let!(:book) { mock_model('Book') }

  it 'sends new message to Book' do
    params = {name: 'Ruby'}
    #Book.method(:new).arity is -1, which means any arguments.

    allow(Book).to receive(:new).with(params) { book }
    post :create, book: params
  end
end
```

ArgumentError:
       wrong number of arguments (1 for 0)

Why is it complaining?

**Comment by myronmarston** [comment]
Can you run your spec with '-b' to print the full backtrack and paste that?

**Comment by ulugbekov** [comment]
1) BooksController POST create sends new message
     Failure/Error: allow(Book).to receive(:new).with(params) { book }
       Wrong number of arguments. Expected 0, got 1.
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:320:in `notify'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:304:in `__raise'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:124:in `raise_invalid_arguments_error'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_message_expecation.rb:48:in `block in validate_expected_arguments!'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:209:in `with_signature'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_message_expecation.rb:40:in `validate_expected_arguments!'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_message_expecation.rb:27:in `block in with'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_message_expecation.rb:26:in `tap'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_message_expecation.rb:26:in `with'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/expectation_customization.rb:15:in `playback_onto'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:99:in `block in setup_method_substitute'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:98:in `each'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:98:in `setup_method_substitute'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:84:in `setup_mock_proxy_method_substitute'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:41:in `setup_allowance'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/targets.rb:45:in `define_matcher'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/targets.rb:14:in `block in delegate_to'
     # ./spec/controllers/readers_controller_spec.rb:37:in `block (3 levels) in <top (required)>'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-rails-3.3.3/lib/rspec/rails/example/controller_example_group.rb:190:in `block (2 levels) in <module:ControllerExampleGroup>'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:389:in `execute_with'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:273:in `call'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `block in run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `map'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:522:in `run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/bin/rspec:23:in `load'
     # /Users/aulugbekov/.rbenv/versions/2.1.2/bin/rspec:23:in `<main>'

Finished in 0.01435 seconds (files took 1.81 seconds to load)

**Comment by JonRowe** [comment]
```
let!(:book) { mock_model('Book') }

**Comment by ulugbekov** [comment]
Thanks for comment.
let is for sure outside of it block. params is local variable. But those are not real issue. Real issue is with allow and receive.

**Comment by myronmarston** [comment]
Can you paste your definition of Book#initialize? Book.new delegates to that and we use the signature of #initialize to validate arguments.

**Comment by ulugbekov** [comment]
It is inheriting rails active record. 
Instead of what we used to do like stubbing rails models, I am trying to do it with rspec allow method. It should work out of the box. I tested both initialize and new returns -1 for arity from mock_model("Book"). But it is complaining. I am also trying to debug rspec-mocks gem internals, but did not succeed yet.

**Comment by JonRowe** [comment]
Can you paste your controller implementation?

**Comment by ulugbekov** [comment]
@book = Book.new(book_params)

regular rails 4 way

**Comment by JonRowe** [comment]
Full code snippets are preferred if you'd like our help, we actually have plenty of tests showing the "regular way" works fine so this must be an edge case caused by something unusual so unless you can provide us with a snippet that actually doesn't work (so far your spec works for me)

**Comment by ulugbekov** [comment]
Hi,
Nothing special. Just rails scaffold.
I am really surprised that it is working for you.  
# POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

private

 def book_params
      params.require(:book).permit(:name)
 end

**Comment by ulugbekov** [comment]
I am debugging gem internals. Here is the result. Still debugging. Looks like initialize method.
#<RSpec::Mocks::VerifyingExistingClassNewMethodDouble:0x007fde0c699c58>
#<UnboundMethod: Book(BasicObject)#initialize>

**Comment by JonRowe** [comment]
Can you paste your `Book` implementation like @myronmarston asked?

**Comment by ulugbekov** [comment]
Sorry I missed that,
it is simple class.
What I wonder is I am allowing :new method to be called with params, and why it is trying to verify signature on initialize. I did not request that to be checked.
class Book < ActiveRecord::Base
end

**Comment by JonRowe** [comment]
By default we validate doubles against their implementations, the implementation of new calls initialize so we use that to validate the double.

**Comment by JonRowe** [comment]
Can you swap `mock_model` for `double` for me? `mock_model` is actually provided by a 3rd party gem now.

**Comment by ulugbekov** [comment]
Ye, it is working as expected. No errors

**Comment by JonRowe** [comment]
This is not an issue with mocks then, we need to figure out why this isn't working in `rspec-activemodel-mocks`

**Comment by JonRowe** [comment]
I'm just working up a spec for an issue over on `rspec/rspec-activemodel-mocks`

**Comment by ulugbekov** [comment]
Thanks

**Comment by JonRowe** [comment]
Update, so it's the fact that Rails hasn't loaded `Book` when you first use `mock_model` that triggers this behaviour, `mock_model` creates a 'false model' for book to use and it's that model rspec uses to verify `Book`s behaviour.

**Comment by ulugbekov** [comment]
I know that.
So, how are we going to use mock_model. We have to test new method. But it tests initialize which do not take any args, cause it is fake model. Somebody should fix that issue.

**Comment by myronmarston** [comment]
Why do you need `mock_model` at all?  What benefit is it giving you over `instance_double(Book)`?

`mock_model` is no longer part of rspec-rails precisely because of complexities like these -- it took significant effort to support and we don't generally have the time to provide the kind of first-class support for it that users expect for features that we ship with the gems we maintain.

**Comment by ulugbekov** [comment]
I know people have different test preferences, instance_double can't create class Book if it does not exists? mock_model does if there is not Book class.

**Comment by myronmarston** [comment]
`instance_double` isn't meant to create any classes, but it can be used when the named class does not exist if you pass it a string name.  `class_double` will create the constant if it does not exist if you do `class_double("Book").as_stubbed_const` so that's a possibility if you prefer.

Anyhow, it seems like the problem with `mock_model` is that the fake version of the class doesn't define `initialize` like rails does to accept arguments.  (This is the general problem with `mock_model`: it's a fake object trying to more closely mimic a real one but it's not close enough).  I believe this issue could be fixed if `mock_model` was updated to define `initialize` appropriately.  Want to work up a PR making that change?

**Comment by ulugbekov** [comment]
:)
It is ok. I will be using latest your approach. Do not want to have other headaches on my way of testing. Thanks for heads up.
