### ISSUE TITLE
class_double and `is_a? Class`

### ISSUE THREAD

**Issue by dg-ratiodata** [rspec/rspec-mocks#1035]
Hey @myronmarston, hope you're doing fine? Recently I tried to use `class_double` and `stub_const`.

~~~ruby
    let!(:another_test_event_klass) do
      class_double('Events::AnotherTestEvent').tap do |double|
        stub_const('Events::AnotherTestEvent', double)
        allow(double).to receive(:new).and_return(another_test_event_instance)
      end
    end

    let!(:another_test_event_instance) do
      class_double('Events::AnotherTestEvent').tap do |double|
        stub_const('Events::AnotherTestEvent', double)
      end
    end
~~~

Somewhere in the code I would like to do the following:

~~~ruby
klass = event.is_a? Class ? event.to_s : event.class.to_s
~~~

I read your comments in #794, but maybe this use case is different. From my understanding an `class_double` should return true if some asks it, if it is a class?

**Comment by JonRowe** [comment]
You have to stub `is_a?` to return `true`, it's an instance of a `ClassVerifyingDouble` and we don't lie to Ruby so you'll have to do this manually:

```Ruby
allow(double).to receive(:is_a?).with(Class) { true }
```

**Comment by dg-ratiodata** [comment]
Ok. Sure. Damn...
