### ISSUE TITLE
stubbing rails route helper fails in Rails 4.2.5

### ISSUE THREAD

**Issue by badpk** [rspec/rspec-mocks#1038]
The following rspec test works in Rails 4.2.4 but breaks in Rails 4.2.5.

```
it 'stubs routes' do
  allow(Rails.application.routes.url_helpers).to receive(:root_path).and_return('rails_is_awesome')
  expect(Rails.application.routes.url_helpers.root_path).to eq('rails_is_awesome')
end
```

I am using rspec-rails 3.4.0

**Comment by ahorek** [comment]
Hi, it looks like it's related to this commit https://github.com/rails/rails/commit/0acd4a57768fc3c7e758f9f4b26563797f43e7ef

**Comment by JonRowe** [comment]
Looking at that commit, the solution would be to use a stub chain rather than an individual stub, due to Rails returning a new module each time.

e.g.
```Ruby
it 'stubs routes' do
  allow(Rails.application).to receive_message_chain(:routes, :url_helpers, :root_path) { 'rails_is_awesome' }
  expect(Rails.application.routes.url_helpers.root_path).to eq('rails_is_awesome')
end
```
