### ISSUE TITLE
rspec-mocks 3.4.0 on rubinius 2 fails for have_received matcher

### ISSUE THREAD

**Issue by peter-murach** [rspec/rspec-mocks#1040]
Running rspec `v3.4.0` on `Rubinius` I get the following error:
```
Missing or uninitialized constant: RSpec::Mocks::Matchers::HaveReceived
```
To see full report please [see](https://travis-ci.org/peter-murach/tty-prompt/jobs/96620536#L205)

Reverting back to rspec `v3.3.0` fixes the issue. Looking at the changelogs I can see there were some changes done to the `have_received` matcher?

**Comment by JonRowe** [comment]
Have you tried requiring the matcher manually? Rubinius has some weird behaviours sometimes for us and won't compile things so breaks. (Which is historically why we don't allow it to fail our travis build)

**Comment by peter-murach** [comment]
Adding the following to `spec_helper` fixes the issue
```ruby
require "rspec/mocks/matchers/have_received"
```
However, still it is a bit of a mystery to me why it fails without manually requiring it as I'm using this matcher in other projects with `rspec 3.4.0` and it works just fine. One difference with other projects is that this one doesn't directly require spec_helper but uses the dot file. I've tested this theory as well and the matcher wasn't loaded on Rubinius.

**Comment by JonRowe** [comment]
I suspect the answer with be "because Rubinius" sadly :/
