### ISSUE TITLE
Ruby 2.3.0-preview2 generates ruby warnings and fails many stub/double tests -

### ISSUE THREAD

**Issue by jrafanie** [rspec/rspec-mocks#1041]
I'm seeing issues with ruby 2.3.0-preview2 when rspec stub/doubles are involved where the wrong super method is being invoked.  This is probably [too much information but here it is](https://github.com/ManageIQ/manageiq/issues/5814) in case you want to how I got to this issue.

Because of that failure, I tried the rspec-mocks test suite with both 2.2.3 and 2.3.0-preview2 and noticed ruby warnings and test failures in 2.3.0 that don't occur on 2.2.3.

The warnings look like: 
`/Users/joerafaniello/Code/rspec-mocks/spec/rspec/mocks/double_spec.rb:254: warning: previous definition of method_with_default_argument was here`

I have the full output of  `bundle exec rake spec` from [both 2.2.3 and 2.3.0-preview2 here](https://gist.github.com/jrafanie/570aa8a80f78a2b51b61).  They indicate a problem with stubbing/mocking methods in 2.3.0-preview2.

I looked through the release notes and [this section looked very interesting](https://github.com/ruby/ruby/blob/v2_3_0_preview2/ChangeLog#L5720-L5834).

It references this bug: https://bugs.ruby-lang.org/issues/11278
Also, https://bugs.ruby-lang.org/issues/11279, which says "This is big change of method data structure."

It feels like this might be a ruby regression but I can't limit the scope of the warning outside of rspec yet.

**Comment by jrafanie** [comment]
I just noticed the ruby-head tests are also failing with the same errors:
![screen shot 2015-12-15 at 6 18 21 pm](https://cloud.githubusercontent.com/assets/19339/11827181/514630f0-a358-11e5-9fa4-bf8e7a64e498.png)

See: https://travis-ci.org/rspec/rspec-mocks/jobs/95425009

**Comment by jrafanie** [comment]
cc @JonRowe @myronmarston (I didn't see this reported elsewhere)

**Comment by JonRowe** [comment]
Thanks for reporting this, we haven't tried `2.3.0` ourselves yet, it's worth noting that this is fairly typical of a Ruby preview, and the final version may work as before.

**Comment by jrafanie** [comment]
I'm glad to help @JonRowe.  Thanks.  I didn't see a bug reported in https://bugs.ruby-lang.org/projects/ruby-trunk/issues?set_filter=1&tracker_id=1 that resembled the symptoms I was seeing. Please let me know if I can help in any way.

**Comment by JonRowe** [comment]
If you'd like to take a stab at fixing the issues please feel free!

**Comment by jrafanie** [comment]
@JonRowe Note, It looks like the reported problems are just warnings that we're capturing in the tests and asserting that no warnings were raised.  I found a different bug that is actually the problem I hit in my project.  I'll leave this issue for "figuring" out why we're getting warnings that cause our assertions to fail.

**Comment by JonRowe** [comment]
Yeah thats expected behaviour (the warnings causing failures)

**Comment by jrafanie** [comment]
For reference, I had to temporarily hack rspec-support to even test ruby 2.3.0-preview2 with rspec-mocks locally, see #1043
