### ISSUE TITLE
allow with wrap_original does not work on JRuby

### ISSUE THREAD

**Issue by envygeeks** [rspec/rspec-mocks#1045]
The following:

```
allow(described_class).to receive(:new).and_wrap_original do |method, *args, **kwd|
  kwd[:root] = true unless kwd.key?(:root) || kwd.key?(:root_metadata)
  method.call(*args, **kwd)
end
```

Will not work on JRuby.

**Comment by JonRowe** [comment]
Huh so is this a jruby bug?

**Comment by envygeeks** [comment]
Yes, but I cross posted just incase one of them can provide some insight that might lead it to being a bug here because I'll be honest, I don't know, I was just playing with kwd wrapping and deduplication of our specs and discovered all this stuff months ago but finally got around to filing it now that I had a few minutes to replicate it and start filing.

**Comment by enebo** [comment]
This was fixed many releases ago on jruby (did not bisect for which but it should not longer be an issue for you).
