### ISSUE TITLE
allow with wrap_original causes a segfault on Ruby 2.1

### ISSUE THREAD

**Issue by envygeeks** [rspec/rspec-mocks#1046]
The following:

```
allow(described_class).to receive(:new).and_wrap_original do |method, *args, **kwd|
  kwd[:root] = true unless kwd.key?(:root) || kwd.key?(:root_metadata)
  method.call(*args, **kwd)
end
```

causes Ruby 2.1 on Travis-CI to segfault, this is constantly reproducable.

**Comment by JonRowe** [comment]
Segfaults are not normally anything to do with rspec but the underlying Ruby implementation, out of curiosity what happens when you change `method` to `method_name`?

**Comment by envygeeks** [comment]
It's the keywords causing the segfault, and it only happens in RSpec so I assumed the ticket should originate here so we can track down what in RSpec causes the segfault so we can then file a ticket on Ruby.

**Comment by envygeeks** [comment]
I'll also be quite honest that the latest Ruby 2.1 did fix a segfault in enumerator so tomorrow I'll actually test this against the latest 2.1 and close it if it doesn't segfault with that method.

**Comment by pirj** [comment]
Closing as stale.
