### ISSUE TITLE
Too strong restriction for matchers

### ISSUE THREAD

**Issue by nepalez** [rspec/rspec-mocks#1055]
Seems like the requirement `only the 'receive', 'have_received' and 'receive_messages' matchers are supported with 'allow(...).to'` is too restrictive.

For example, I provide the matcher, that is sort of [semi-transparent extension for the `receive`](https://gist.github.com/nepalez/ac049b788c369e8d98a3#file-receive_request-rb-L59-L65)

I believe it could work, but it doesn't because of the restriction above. Do we really need it?

Surely, I could just reload the `receive` method (and actually I did) and then monkey-patch the whole `RSpec::Mocks::Matchers::Receive` class. But also I do need to reload both the `allow` and `expect` to [switch `client` to `client.connection`](https://gist.github.com/nepalez/ac049b788c369e8d98a3#file-receive_request-rb-L64). It works, but seems far too messy, not to mention dark sides of monkey patching by itself.

I think, it would be far better way to allow developer to shoot himself :gun:  in the foot, not restricting him so strongly.

**Comment by nepalez** [comment]
Actually I understood that a proposed solution is not sufficient. What I do need is a way to extend receive matcher to make it accessible to both `expect` and `allow` (my solution doesn't do this)

**Comment by myronmarston** [comment]
Exactly.  Matchers in general don't work with `allow`.  `allow` doesn't even use the matcher protocol, because it has to act differently than `expect` does.  It actually calls `setup_allowance` on the matcher, but that's not a published public API.

I think you could get `allow(client).to receive_request(:get, url)` to work if you define `receive_request` as a method that delegates to `receive` internally -- which would just return the same kind of object that `receive` returns which `allow` would understand.

**Comment by nepalez** [comment]
Hi, @myronmarston, and thank you for the suggestion!

Yes, this is [what I've done eventually](https://gist.github.com/nepalez/7a33e39d5fc3162c0ba2#file-receive_request_1-rb-L46-L51).

Though this works, still there is one more issue. Seems like the restriction requires exact classes (`RSpec::Mocks::Matchers::Receive` and so on) for the allowance matchers. If it **allowed subclassing too**, I could remove all this mess from the `#receive_request` and just define my own receiver, and do something like this:

```ruby
module Receiver
  def initialize(method, path = nil)
    # ...
    super # ...
  end

  def where(&block)
    # ...
  end
end

class ReceiveRequest < RSpec::Mocks::Matchers::Receive
  include Receiver
end

class HaveReceivedRequest < RSpec::Mocks::Matchers::HaveReceived
  include Receiver
end

def receive_request(*args)
  ReceiveRequest.new(*args)
end

def have_received_request(*args)
  HaveReceivedRequest.new(*args)
end
```

Because I've intentionally kept myself from monkey-patching the `Receive` class, I had to implement the initializer in this weird way outside of the class. It works but not as clean as it could be.

**Comment by myronmarston** [comment]
> Seems like the restriction requires exact classes (RSpec::Mocks::Matchers::Receive and so on) for the allowance matchers. If it allowed subclassing too

Looking at the [implementation](https://github.com/rspec/rspec-mocks/blob/v3.4.1/lib/rspec/mocks/targets.rb#L20-L29), it looks like it does allow subclasses (using classes in a `case` statement will match on instances of that class or any subclass).

What makes you say it does not allow subclassing?

**Comment by nepalez** [comment]
In the exampe as shown above, I received:

```
only the `receive`, `have_received` and `receive_messages` matchers are supported with `allow(...).to`, but you have provided: #<Evil::Client::RSpec::ReceiveRequest:0x00000003de14f0>
```

**Comment by myronmarston** [comment]
Can you push up a repo containing a reproducible example?

**Comment by nepalez** [comment]
I'll try doing this a bit later, because its a part of private repo. Need some time to carefully extract it from there

**Comment by nepalez** [comment]
Well, i've decided to provide a simplest one :)

```ruby
require "rspec"

describe "inheriting", :focus do
  ReceiveRequest = Class.new(RSpec::Mocks::Matchers::Receive)

  def receive_request(method)
    ReceiveRequest.new(method, nil)
  end

  it "works" do
    client = double

    allow(client).to  receive_request(:call)
    expect(client).to receive_request(:call)

    client.call
  end
end
```

**Comment by myronmarston** [comment]
Thanks for the example.  I see the problem now.  The case statement I referred to before is used for a different situation.  The check for this situation is here:

https://github.com/rspec/rspec-mocks/blob/42ef957e0af1813c0933f29588121e78fadb8244/lib/rspec/mocks/targets.rb#L40-L42

...which just looks at the matcher class name (it's a simple way to ask, "is this one of the rspec-mocks matchers?")

That can certainly be changed to a more robust mechanism that allows subclasses.  Also, for now you can just define your subclass as a constant nested under `RSpec::Mocks::Matchers::` to work around this issue.

**Comment by myronmarston** [comment]
Also, I meant to ask: are you willing to work up a PR to fix this?  It's generally hard for us to find time for things like this that only one user has asked for.
