### ISSUE TITLE
misleading error message

### ISSUE THREAD

**Issue by betesh** [rspec/rspec-mocks#1062]
https://github.com/rspec/rspec-mocks/blob/v3.5.0.beta1/lib/rspec/mocks/message_expectation.rb#L117 raises an error when and_wrap_original is called on a pure double.  However, the error message refers to `and_call_original`, not `and_wrap_original`, which leads to confusion when you are not calling `and_call_original` at all.

There was a time that `and_wrap_original` was not documented and not part of the officially supported API, and at that time, this message would have been a very reasonable choice.  However, `and_wrap_original` is now documented and public, so the error message should refer to it.

**Comment by myronmarston** [comment]
Yep.  Want to work up a PR improving the error message?

**Comment by betesh** [comment]
Sure.  I just didn't want to make this change without agreement for the rspec team--I was anticipating more of a debate.

Here are my thoughts: The fact that `and_call_original` calls `and_wrap_original` is an implementation detail that users may not care about.  So in order to provide the right error message, we need to know whether `and_wrap_original` was called directly or via `and_call_original`.  There are 2 ways we could do that:
1) pass an extra arg to `and_wrap_original`--for instance, a Symbol with the name of the calling method.  If nil, then it was called directly.  However, because it is a documented method, that makes it part of a public interface, so we may even need to create a separate private method for this.
2) Catch the error sooner by duplicating the raise in `and_call_original`.  Less DRY in terms of both code and performance (it's running the same check twice).

Does the core team have any strong preferences about which approach to take?

**Comment by JonRowe** [comment]
Yep, extract it to a private method with an argument, we can't/don't want to change the public method signature.

**Comment by betesh** [comment]
@JonRowe PR is in #1063

**Comment by JonRowe** [comment]
Thanks :heart:
