### ISSUE TITLE
expect(obj).not_to receive(:method) failing because method is called in an `after` block

### ISSUE THREAD

**Issue by lionelperrin** [rspec/rspec-mocks#1074]
The follwing test is failing whereas I was expecting that the calls made in an after block are not taken into account for the test.

In my case, I need to do a test like:
* make sure that one call is not closing an underlying object
* but close the underlying object in the end to avoid leaks

```
let(:myobj) { "something" }
it 'receive count takes after block into account' do
   expect(myobj).not_to receive(:upcase) # this is failing
   myobj
end
after(:each) {
   myobj.upcase
}
```

**Comment by myronmarston** [comment]
That's working by design.  Mocks aren't verified and cleaned up until after the `after` hooks are run, so I'd expect it to work that way.  You'll have to find an alternate way to make it work.  One way would be to create your own mocks scope just in the example block:

``` ruby
let(:myobj) { "something" }

it 'receive count takes after block into account' do
  RSpec::Mocks.with_temporary_scope do
    expect(myobj).not_to receive(:upcase) # this is failing
    myobj
  end
end

after(:each) { myobj.upcase }
```
