### ISSUE TITLE
Extending message expectations?

### ISSUE THREAD

**Issue by delner** [rspec/rspec-mocks#1075]
Just a question for some knowledgeable RSpec folks. I'm working on implementing a callback pattern into some code of mine. I'd like to stub/mock calls to functions that implement this pattern, and make them emulate callbacks in my RSpec tests.

Right now, the most stripped down version of my test looks something like:

    class MyClass
      def self.foo do |&block|
        # If success
        block.call(:success)
        # If failure
        block.call(:failure)
      end
    end

    # RSpec example
    expect(MyClass).to receive(:foo) { |&block| block.call(:success) }

Although it works through some ugly use of the `and_return` block shorthand, it hurts test readability. I'd like instead to extend the RSpec mocks, in a gem, with my own MessageExpectation method `and_callback` to do the same functional thing, which might look something like:

    expect(MyClass).to receive(:foo).and_callback(:success)

I've been digging through the RSpec documentation and source code, and am not seeing a clear means of adding my own expectation behavior to the RSpec suite. [Another person was trying to do something similar](http://stackoverflow.com/questions/14217148/how-to-extend-rspec-mock-expectation), and Andrew Haines suggested `alias_method` to accomplish that goal.

Outright monkey patching RSpec seems like a bad idea to me, but is there a cleaner alternative or support to do an extension on the suite like this? I'm all ears!

**Comment by myronmarston** [comment]
You can use `and_yield` to yield to a callback:

``` ruby
expect(MyClass).to receive(:foo).and_yield(:success)
```

**Comment by delner** [comment]
Okay, you're definitely right about `and_yield`, which pretty much satisfies my above example. I think I oversimplified it a bit. In my actual code I implemented a callback class to wrap up the code a bit more neatly. In practice it looks more like:

```
class MyClass
  def self.foo do |&block|
    callbacks = Callbacks[block]
    # If success
    callbacks.respond_with(:success)
    # If failure
    callbacks.respond_with(:failure)
  end

  class Callbacks
    def self.[](block)
      # Invokes block to define callback methods
    end
    def respond_with(name, *args)
      # Invokes callback method
    end
  end
end

# Sample usage:
MyClass.foo do |on|
  on.success { puts "Success!" }
  on.failure { puts "Failure!" }
end

# Sample expectation:
expect(MyClass).to receive(:foo) do |&block|
  MyClass::Callbacks[block].respond_with(:success)
end

# Ideal expectation:
expect(MyClass).to receive(:foo).and_callback(:success)
```

I'm not sure how to cleanup that sample expectation using the current RSpec implementation, which was why I was thinking "if I can tap into the expectation chain with a custom matcher, get the object/class that is expecting a call, and the callback block that's passed as an argument, I can inject my `respond_with` call into the expectation chain."

**Comment by JonRowe** [comment]
I'm not sure chaining is a good fit here, why not implement a macro instead? e.g.

```Ruby
module CustomReceive
  def receive_then_callback(name, callback)
    receive(name) do |&block|
      MyClass::Callbacks[block].respond_with(callback)
    end
  end
end
```
RSpec.configuration.include CustomReceive

**Comment by delner** [comment]
I think that's a fair option.

I was also thinking about some scenarios where I might want to trigger multiple callbacks, and pass a different set of arguments to each of those callbacks. But I think I could manage most of the things I'd like to do with callbacks by implementing a similar macro pattern to what you listed above.

However, in the case I were to find scenario where I'd actually need to implement something custom on the chain, would there be a clean way of doing so? Like how developers can define their own matchers?

**Comment by myronmarston** [comment]
RSpec doesn't provide any APIs specifically for defining your own methods for this purpose but you can use Ruby's `SimpleDelegator` to do it pretty cleanly:

``` ruby
require 'delegate'

class ReceiveWrapper < SimpleDelegator
  def and_foo(foo)
    # do whatever
  end

  # Re-wrap the return values of all method calls so that
  # things like `receive(:bar).with(:args).and_foo` work.
  def method_missing(*args, &block)
    ::ReceiveWrapper.new(super)
  end
end

module ReceiveMethodWrapper
  def receive(*args, &block)
    ::ReceiveWrapper.new(super)
  end
end

RSpec.configure do |c|
  c.include ReceiveMethodWrapper
end
```

(Note: I haven't actually tried the above code, but I believe it, or something very close to it, should work.)

Here's how it works:

* `receive` is overriden in `ReceiveMethodWrapper` to delegate to RSpec's implementation and then the return value is wrapped with `ReceiveWrapper`.
* `ReceiveWrapper` is a delegator so it'll have all the methods of the wrapped object. We customize `method_missing` so that return values are wrapped again.
* On the `ReceiveWrapper` you can define whatever new chained methods you want -- in this case, `and_foo`.

**Comment by delner** [comment]
Cool, thanks @myronmarston!
