### ISSUE TITLE
Unable to stub method with required keyword arguments 

### ISSUE THREAD

**Issue by Tonkpils** [rspec/rspec-mocks#1076]
When attempting to stub a method that contains required keyword arguments as such
```
class Foo
  def test(test:)

  end
end

describe Foo do
  it "should stub required keyword argument method" do
    allow_any_instance_of(Foo).to receive(:test).and_return("bar")

    b = Foo.new
    expect(b.test).to eq('bar')
  end
end
```

the following error is raised 

```
  1) Foo should stub required keyword argument method
     Failure/Error: expect(b.test).to eq('bar')

     ArgumentError:
       Missing required keyword arguments: test
```

It doesn't seem like expected behavior to me, so I can try to write up a fix for it if you're interested.

**Comment by soulcutter** [comment]
b.test is an invalid method call, though.

**Comment by Tonkpils** [comment]
Agh, I should've caught that on the sample spec. I modified the original spec that showed this issue but I'm sure it must've been something similar. Thanks for catching this!
