### ISSUE TITLE
have_received doesn't work with ordered messages

### ISSUE THREAD

**Issue by ingobecker** [rspec/rspec-mocks#1078]
I tried to test an object to receive messages in a specific order. Using `receive` works but `have_received` doesn't:

```ruby
describe 'a double' do
  let(:dbl) { double('dbl') }
  before do
    allow(dbl).to receive(:foo)
    allow(dbl).to receive(:bar)
  end

  it 'works with receive' do
    expect(dbl).to receive(:foo).ordered
    expect(dbl).to receive(:bar).ordered
    expect(dbl).to receive(:foo).ordered

    dbl.foo
    dbl.bar
    dbl.foo
  end

  it 'fails with have_received' do
    dbl.foo
    dbl.bar
    dbl.foo

    expect(dbl).to have_received(:foo).ordered
    expect(dbl).to have_received(:bar).ordered
    expect(dbl).to have_received(:foo).ordered
  end
end
```
This test fails with the following result

```
a double
  works with receive
  fails with have_received (FAILED - 1)

Failures:

  1) a double fails with have_received
     Failure/Error: expect(dbl).to have_received(:foo).ordered
     
       (Double "dbl").foo(*(any args))
           expected: 1 time with any arguments
           received: 2 times with any arguments
     # /tmp/receive_spec.rb:23:in `block (2 levels) in <top (required)>'

Finished in 0.02743 seconds (files took 0.13699 seconds to load)
2 examples, 1 failure

Failed examples:

rspec /tmp/receive_spec.rb:18 # a double fails with have_received
```
I like to stick to the [four phase test pattern](https://robots.thoughtbot.com/four-phase-test) which is why i tried to use `have_received` instead of `receive`. Is there a reason why `have_received` behaves differently and is there a way to make it work as shown above?

**Comment by JonRowe** [comment]
Spies verify their behaviour directly and this is an oversight on our part, we probably should have removed the unsupported `ordered` modifier here until it was implemented. PRs would be welcome to implement it however!

**Comment by myronmarston** [comment]
This is a known issue -- see #916.  Fixing it isn't simple, unfortunately, which is why it hasn't been done yet.  If you'd like to chip in, that'd be great.  Please respond on #916. I'm going to close this to keep the conversation going on the existing issue.
