### ISSUE TITLE
Count recursive calls

### ISSUE THREAD

**Issue by guizmaii** [rspec/rspec-mocks#1099]
Hi,

I'm not able to count recursive calls:

```ruby
describe "Count recursive calls" do
  class AClass
    def rec_function(try = 3)
      try > 0 ? rec_function(try - 1) : nil
    end
  end

  let!(:instance) { AClass.new }
  it {
    expect(instance).to receive(:rec_function).exactly(4).times
    instance.rec_function
  }
end
```

<img width="726" alt="capture d ecran 2016-06-23 10 46 44" src="https://cloud.githubusercontent.com/assets/1193670/16297690/2cf1b1b4-3932-11e6-9950-de5e702a3c39.png">

Is it normal ?

I use rspec-mocks 3.4.1

thanks.
Jules

**Comment by JonRowe** [comment]
Yes. The implementation doesn't exist. You need to add `and_call_original`

**Comment by guizmaii** [comment]
Yes thanks ! I found this ticket that had the answer : https://github.com/rspec/rspec-mocks/issues/917
