### ISSUE TITLE
undefined method `to' for #<RSpec::Matchers::DSL::Matcher allow>

### ISSUE THREAD

**Issue by jjbohn** [rspec/rspec-mocks#1105]
Having a really odd problem. `to` seems to be undefined all of the sudden. We recently went from a 2.x version to 3.5 so I'm thinking that might have something to do with it and it just wasn't caught until now.

`to` is working fine with `except`.

I feel like I have some wonky piece of configuration that I might be missing but I can't track it down. Any ideas?

**Comment by jjbohn** [comment]
Just realized I meant to put this in rspec-exceptations. That said, I did some more digging and this definitely looks isolated to me. Sorry for the noise.

**Comment by mrageh** [comment]
@jjbohn Can you please put together a reproducible example demonstrating this issue?

**Comment by myronmarston** [comment]
@jjbohn `allow` is a method provided by rspec-mocks so I think this belongs here.  I'll reopen this.

Anyhow, based on your error, it looks like maybe you have defined an `allow` matcher with `RSpec::Matchers.define :allow`, which would cause a matcher object that returns `#<RSpec::Matchers::DSL::Matcher allow>` when inspected.  If you've done that, you'll need to rename it so as not to conflict with rspec-mocks `allow` method.

**Comment by jjbohn** [comment]
@myronmarston you're completely right. Just found it as I was doing some further digging. Thanks for the help!
