### ISSUE TITLE
Copying expectations

### ISSUE THREAD

**Issue by ktimothy** [rspec/rspec-mocks#1107]
Is there a way to copy/move expectations from one object to another? For instance, I would like to do something like that:
```ruby
source = double
expect(source).to receive(:bar)
target = double

RSpec::Mocks.move_expectations(source, target)
target.bar
```

**Comment by JonRowe** [comment]
No there isn't but there is `expect_any_instance_of(object).to receive(:bar)`, but thats generally only considered a good idea for legacy/rails style code, can I ask what you are trying to achieve?

**Comment by ktimothy** [comment]
Sure, I am trying to find a shorter way to stub [Grape APIs helpers](https://github.com/ruby-grape/grape#stubbing-helpers). The problem is, that actual endpoint object is accessible only when I call the api, but that is too late to set expectations. So I try to set expectations on a double, and copy them to endpoint, when I can access it.

What I am trying to actually achieve is to write
```ruby
expect(api_helpers).to receive(:helper_method)
```
instead of
```ruby
Grape::Endpoint.before_each do |endpoint|
  allow(endpoint).to receive(:helper_method)
end
```

**Comment by JonRowe** [comment]
Forgive me, what's wrong with:

```
Grape::Endpoint.before_each do |endpoint|
  allow(endpoint).to receive(:helper_method)
end
```

?

**Comment by ktimothy** [comment]
Nothing, I would just like to write shorter code to set expectations.

**Comment by JonRowe** [comment]
You can implement something shorter yourself, try this:

```
module GrapeEndpointHelper
  def expect_endpoint_to(matcher)
    Grape::Endpoint.before_each { |endpoint| expect(endpoint).to matcher }
  end

  RSpec.configuration.include self
end
```

**Comment by ktimothy** [comment]
Well, that looks pretty, thanks.
