### ISSUE TITLE
Proposal: more consistent/compact spies

### ISSUE THREAD

**Issue by zverok** [rspec/rspec-mocks#1108]
Idea is:
```ruby
# I already can with RSpec
expect { some code }.to raise_error
expect { some code }.to change(some, :value)

# And I'll be happy to:
expect { some code }.to send_message(foo, :bar).with(blah).and_obtain(baz)
# (exact matcher names could differ)

# What about chaining?..
expect { large call }
  .to send_message(Scheduler, :schedule).with(...)
  .and send_message(SomeService, :cleanup).with(...)
  .and ....
```

Currently, message expectations seems the only frequently used matcher which has no way to write it in one-line readable statement, whatever preparational operations you'll put in `before` block.

WDYT on the idea? Was it already discussed (haven't find on the tracker)? If it could be accepted, I'll be happy to come with a corresponding PR.

**Comment by JonRowe** [comment]
This has actually recently been discussed over in rspec/rspec-expectations#934 (wrong repo for it but never mind) and we came to the conclusion this was best left to an extension gem for now.

**Comment by JonRowe** [comment]
Quoting @myronmarston here:

>FWIW, when we first introduced spying features, we discussed a very similar syntax to what you've suggested (see #220), but decided to go with a simple have_received matcher. The main reasons are:

> * A block form doesn't provide an easy way to configure how the spy should respond to the messages -- whereas that's not a problem at all with the direction we went.
* A block form can get unwieldy when there are multiple messages in play, where as having multiple expect(...).to have_received(...) calls in a row is far less unwieldy.
* RSpec's spying features work best when dealing with command methods (where there isn't a meaningful return value) and you can therefore use a simple spy with no need to configure how it responds:
```Ruby
ledger = spy("Ledger")
process_transaction_with(ledger)
expect(ledger).to have_received(:record).with(transaction)
```
(notice that we don't need to allow anything on the ledger).

> Overall, I don't think a block form buys us anything significant over what we have now, and it seems to me to be less flexible. In addition, if we added it, it would be yet another thing for our users to need to learn--which to me is a hard sell given there aren't notable benefits over what we already have. So I'm inclined not to add support for this to RSpec. I think it could make a great extension gem, though.
