### ISSUE TITLE
Extract ConstantMutator?

### ISSUE THREAD

**Issue by amarshall** [rspec/rspec-mocks#1111]
This is a generally useful utility that I’ve implemented on my own before, but RSpec’s is rather feature-complete. It would be nice to be able to use it without pulling in a whole bunch of RSpec (which I won’t do if it’s not already a dependency..

Thoughts?

**Comment by myronmarston** [comment]
We go out of our way to avoid depending on other gems in RSpec (with a few carefully selected exceptions like `diff-lcs`) to prevent version conflict problems where RSpec requires version 1.x of `contant-mutator` but some other gem your project depends on `constant-mutator` 2.x--in such a situation you would not be able to use the other gem and RSpec in the same project, so we try to avoid such situations by not depending on other gems, to ensure RSpec can be used in the widest array of project possible.

Anyone would be welcome to create a `constant-mutator` gem based on the code in RSpec (I believe the MIT license we use explicitly allows this) so if you want to extract a gem, you have our blessing -- just know that we'll continue to use version of the constant mutation logic over the extracted gem.
