### ISSUE TITLE
Do not allow stubbing on a mock

### ISSUE THREAD

**Issue by bquorning** [rspec/rspec-mocks#1123]
rspec-mocks allows us to define a mock and tacking a stub onto the end it:

```rb
expect(foo).to receive(:bar).with(42).and_return("hello world")

subject.exercise
```

Now RSpec will expect `foo` to receive `:bar` with the argument `42`.

If you read the code aloud, it very much sounds like `"hello world"` should also be part of the expectation. It isn’t.

I can think of at least two ways to rewrite this with the mocking and stubbing separated:

```rb
allow(foo).to receive(:bar).with(42).and_return("hello world")
expect(foo).to receive(:bar).with(42)

subject.exercise
```

or

```rb
allow(foo).to receive(:bar).with(42).and_return("hello world")

subject.exercise

expect(foo).to have_received(:bar).with(42)
```

This problem exists not only for `and_return`, but to all message expectation methods mentioned in https://relishapp.com/rspec/rspec-mocks/v/3-5/docs/configuring-responses: `and_return`, `and_raise`, `and_throw`, `and_yield`, `and_call_original`, and `and_wrap_original`.

My question is this: Is my opposition towards mixing mocks and stubs merely a stylistic preference? Or (totally possible) did I just get myself confused w.r.t. mocks and stubs?

**Comment by JonRowe** [comment]
It's allowed for this sort of situation:

```ruby
allow(foo).to receive(:bar).and_return("hello world")
expect(foo).to receive(:bar).with(666).and_return('the nasty one')
```

Which is totally allowable in our DSL, its fine if you wish to seperate them (I tend to also as I dislike multiple stubs with return values) but it's something we've always supported so needs to stay.

**Comment by JonRowe** [comment]
> did I just get myself confused w.r.t. mocks and stubs?

We got away from using the term mock, as it's ambiguous, and can be applied both ways. RSpec these days separates a mock into stubs e.g. `allow(...).to receive()` and doubles e.g. `instance_double(Object)`

**Comment by bquorning** [comment]
Thank you for the clarification.

I would probably rewrite your example to something like this:

```rb
allow(foo).to receive(:bar).and_return("hello world")
allow(foo).to receive(:bar).with(666).and_return('the nasty one')

subject.exercise

expect(foo).to have_received(:bar).with(666)
# Or an expectation involving the string `'the nasty one'`.
```

But I accept your argument that “it's something we've always supported so needs to stay”.

**Comment by jcoyne** [comment]
> but it's something we've always supported so needs to stay

@JonRowe would you consider deprecating this behavior?

**Comment by myronmarston** [comment]
> @JonRowe would you consider deprecating this behavior?

Maybe if there was a broad community consensus.  But users like to use different parts of RSpec in different ways and I would expect a lot of push back on such a deprecation.  In general, we don't deprecate or disallow things just because something is a code smell.

**Comment by JonRowe** [comment]
I'd lean against deprecating it as I think it's perfectly fine to do, and we reuse a lot of the code between the two which would make disallowing it a maintenance burden for no clear benefit in my view.
