### ISSUE TITLE
Add stub_chain documentation to README.md

### ISSUE THREAD

**Issue by glaucocustodio** [rspec/rspec-mocks#1129]
I find `stub_chain` very useful for some cases. I know there are concerns regarding Law of Demeter but I think we should instruct its usage at README.md.

Would a PR be welcome? Thank you.

**Comment by JonRowe** [comment]
Given that nearly everything else is, sure, however it would have to be `receive_message_chain` which is the modern incarnation.

**Comment by samphippen** [comment]
@glaucocustodio is this still something you'd like to file a PR for?

**Comment by glaucocustodio** [comment]
I'm sorry for the delay. Please, see https://github.com/rspec/rspec-mocks/pull/1137.
