### ISSUE TITLE
Rspec::Mocks::AnyInstance::Recorder build_alias_method_name creates invalid method alias when method name ends in exclamation point or question mark

### ISSUE THREAD

**Issue by eedwardsdisco** [rspec/rspec-mocks#1134]
Ran into this while using ChefSpec, but it appears to be a an rspec-mocks issue.

From my testing in IRB, it's invalid to declare a method such as:

ruby 2.3.0
```
irb(main):007:0> def _method!_without_any_instance__(foo)
irb(main):008:1> end
SyntaxError: (irb):7: syntax error, unexpected '(', expecting ';' or '\n'
def _method!_without_any_instance__(foo)
                                    ^
	from /opt/chefdk/embedded/bin/irb:11:in `<main>'
```

If I use a line such as this in my rspec file:

```
allow_any_instance_of(Chef::Resource).to receive(:powershell_out!).and_return(nil)
```

You can see I get a similar error as above:

```
SyntaxError:
       acme_pspackage_provider[NuGet_Scope_AllUsers] (acme-windows_test::install_acme_pspackage_provider line 1) had an error: SyntaxError: /opt/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:187: syntax error, unexpected '(', expecting ';' or '\n'
             def __powershell_out!_without_any_instance__(*args, &block)
                                                          ^
       /opt/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:187: syntax error, unexpected &
             def __powershell_out!_without_any_instance__(*args, &block)
                                                                  ^
```

Thus, I believe the method aliases being generated by 'build_alias_method_name' are possibly invalid when supplied with a method name ending in an exclamation mark `!` (or a question mark `?` as well).

**Comment by JonRowe** [comment]
Interesting, it's quite possible that this is a bug for us, obviously needs to be escaped or similar

**Comment by eedwardsdisco** [comment]
Just as an additional note, I'm finding myself getting bitten by this regularly while using ChefSpec.

Since the way it simulates a Chef run means you often don't get a reference to any of the Objects as part of the run, I regularly have to use allow_any_instance_of and expect_any_instance_of.

I'm a little surprised this failure case hasn't been hit before, as `soandso?` and `soandso!` methods seem very common in Ruby. I've done extensive googling and been unable to find anyone else who encountered this or found a workaround.

**Comment by samphippen** [comment]
This doesn't look like it's us.

```ruby
require "spec_helper"

class Foo
  def mutate!

  end
end

RSpec.describe Foo do
  it "works" do
    allow_any_instance_of(Foo).to receive(:mutate!).and_return("hi")
    Foo.new.mutate!
  end
end
```

passes for me on RSpec master. @eedwardsdisco, what version of RSpec do you have as the eventual dependency of RSpec?

**Comment by eedwardsdisco** [comment]
Hi @samphippen ,

`chef exec rspec --version` reports `3.5.4`

Can you confirm that `build_alias_method_name` from Rspec::Mocks::AnyInstance::Recorder is getting called for your example?

```
        # @private
        def build_alias_method_name(method_name)
          "__#{method_name}_without_any_instance__"
        end
```

I'm confused how your example would work, if it's using the above code as described in ::Recorder, as Ruby doesn't seem to like method names generated as such:

```
irb(main):001:0> def __method_name!_without_any_instance__(obj1, obj2)
irb(main):002:1>   puts 'hi'
irb(main):003:1> end
SyntaxError: (irb):1: syntax error, unexpected '(', expecting ';' or '\n'
def __method_name!_without_any_instance__(obj1, obj2)
                                          ^
(irb):1: syntax error, unexpected ')', expecting '='
(irb):3: syntax error, unexpected keyword_end, expecting end-of-input
	from /opt/chefdk/embedded/bin/irb:11:in `<main>'
irb(main):004:0> def __method_name_without_any_instance__(obj1, obj2)
irb(main):005:1>   puts 'hi'
irb(main):006:1> end
=> :__method_name_without_any_instance__
```

As you can see, it throws a SyntaxError in the same way my original example does (when called from chefspec).

Thanks!

**Comment by samphippen** [comment]
@eedwardsdisco we don't actually use the `def` keyword to achieve this, so your IRB example isn't really indicative of this bug. I can confirm that `build_alias_method_name` is being called. My guess would be something in chef is calling this and doing an old-style string eval on the class.

Given that when only our stack is involved, no exception is thrown, I'm inclined to close this issue. @rspec/rspec any further thoughts?

**Comment by eedwardsdisco** [comment]
Thanks for the additional info, @samphippen !

As per my original error, something in the (downstream?) stack is definitely taking the method name generated from ::Recorder and using it in a 'def' statement:
```
SyntaxError: /opt/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:187: syntax error, unexpected '(', expecting ';' or '\n'
             def __powershell_out!_without_any_instance__(*args, &block)
```

Your comments indicate that RSpec believes it's the responsibility of the consumer to use this generated name in a different way. I'd still argue that if RSpec generated a 'safe' method name, it would not lead to downstream consumers breaking in this way.

Anyway, I'll open an issue with the downstream once I zero in on the offender, so any example of the 'correct' way to call or define a method that has a name like this, would be appreciated. (e.g. how does RSpec utilize it without breaking?)

**Comment by JonRowe** [comment]
@samphippen can you recreate it with your examples if you `include Forwardable`?

**Comment by samphippen** [comment]
@JonRowe works if Forwardable is included.

My suspicion is that ChefSpec is using a string-style eval to define a method, invoking this RSpec method. Nothing in the ruby standard library or RSpec does that anymore, though.

**Comment by eedwardsdisco** [comment]
@JonRowe @samphippen Thanks to both of you. I will open a downstream ticket with ChefSpec. Appreciate the help.
