### ISSUE TITLE
NoMethodError with RSpec Mocks and Cucumber

### ISSUE THREAD

**Issue by ademars94** [rspec/rspec-mocks#1146]
I am trying to configure RSpec Mocks and Cucumber to play nice together, and I am getting an error.

This is in my env.rb from Cucumber:
```
RSpec.configure do |config|
  config.include ::RSpec::Mocks::ExampleMethods
  ::RSpec::Mocks.setup
end
```

And when I try to use RSpec mocks to expect a class to receive a message, I get this error:

```
undefined method `receive' for #<Cucumber::Rails::World:0x007fd3f23a91c0> (NoMethodError)
```

I think there is something wrong with the configuration but I can't find any documentation for setting this up with a third party thing (in this case, Cucumber).

**Comment by myronmarston** [comment]
Your `config.include` line just includes it into the RSpec example context, and not into cucumber's context.

It looks like cucumber includes built-in support for this:

https://github.com/cucumber/cucumber-ruby/blob/v2.4.0/lib/cucumber/rspec/doubles.rb

Have you tried `require 'cucumber/rspec/doubles` in your `env.rb`?  @mattwynne can you confirm if that is the way cucumber maintainers recommend?

**Comment by ademars94** [comment]
@myronmarston Rad. That is working. Thanks for your help!

**Comment by mattwynne** [comment]
Yeah I believe so @myronmarston. I don't use test doubles myself much in acceptance tests, so I don't remember when I last used this feature myself.

**Comment by mattwynne** [comment]
@ademars94 in general, if you want to mix in a module to your step definitions, you need to use the [`World`](http://www.rubydoc.info/github/cucumber/cucumber-ruby/Cucumber/RbSupport/RbDsl#World-instance_method) DSL method.
