### ISSUE TITLE
Feature: #string_matching argument matcher

### ISSUE THREAD

**Issue by Epigene** [rspec/rspec-mocks#1149]
Hi!

Lately I am am doing a lot of specs with mocks, for example:

```rb
expect(controller).to receive(:send_data).once.with("LONG TEXT", type: "text/plain")
```

I was wondering whether there is a matcher that would allow me to check if passed string arguments match a regex, so I could write specs like this:

```rb
expect(controller).to receive(:send_data).once.with(string_matching(/\A.*TEXT\z/), type: "text/plain")
```

I looked in `/lib/rspec/mocks/argument_matchers.rb` and did not see anything like that.
I am happy to write this feature if it is absent and would be useful.

**Comment by myronmarston** [comment]
Since `with` supports anything that defines `===`, you can pass a regex directly to it:

``` ruby
expect(controller).to receive(:send_data).once.with(/\A.*TEXT\z/, type: "text/plain")
```

You can also use any rspec-expectations matcher with `with`, and it provides `a_string_matching`:

``` ruby
expect(controller).to receive(:send_data).once.with(a_string_matching(/\A.*TEXT\z/), type: "text/plain")
```
