### ISSUE TITLE
expect message receipt with args, ignoring receipt with different args

### ISSUE THREAD

**Issue by Dania02525** [rspec/rspec-mocks#1150]
I think this is possible using something like:
```ruby
allow(foo).to receive(:bar)
expect(foo).to receive(:bar).with("baz")
```
But it would be nice to be able to ensure that a message was received with args at some point whether it was before or after messages with different args.  something like: `.at_some_point`.  

Used like this:
```ruby
expect(foo).to receive(:bar).with('baz').at_some_point

it 'fails' do
  foo.bar('biz')
end

it 'passes' do
  foo.bar('baz')
end

it 'also passes' do
  foo.bar('biz')
  foo.bar('baz')
end

```
This is useful when the order of messages received is indeterminate and not important beyond whether the message with specific args was received or not.

Have a working implementation of this if it seems like a good idea for rspec :-)

**Comment by myronmarston** [comment]
I don't think this is widely useful enough for us to take it on and enlarge our API.  You can already easily achieve this using a spy:

``` ruby
foo = instance_spy(Foo)

do_something_with(foo)

expect(foo).to have_received(:bar).with("baz")
```

This only passes if `foo.bar("baz")` was called, and ignores any other messages sent to `foo`.

**Comment by JonRowe** [comment]
```
allow(foo).to receive(:bar)
expect(foo).to receive(:bar).with("baz")
```

Is also a common pattern if you have multiple uses and only care about one, so I'm siding with @myronmarston here and closing this as "not widely useful enough for us to take on", but thank you for taking the time to suggest it!
