### ISSUE TITLE
How to stub initialize method on object

### ISSUE THREAD

**Issue by rusikf** [rspec/rspec-mocks#1152]
Lets we have class
```ruby
class Publish
  def initialize(options)
  end
  def call
  end
end

service = Publish.new(a: 1, b: 2)
service.call

```

How to test that `service` was initialized with `a: 1, b: 2` ?? 
If I want to test call method options, I can use `allow_any_instance_of(service).to receive(:call).with(options)`, but how to stub new method ??

With best regards, Ruslan.

**Comment by mikegee** [comment]
> How to test that service was initialized with `a: 1, b: 2` ??

Add reader methods to `Publish` for inspection, then:

```ruby
expect(service.a).to eq(1)
expect(service.b).to eq(2)
# or
expect(service).to have_attributes(a: 1, b: 2)
```

**Comment by JonRowe** [comment]
>How to test that service was initialized with a: 1, b: 2 ??
> If I want to test call method options, I can use `allow_any_instance_of(service).to receive(:call).with(options)`, but how to stub new method ??

You can assert that a specific instance is created by stubbing new, e.g. `allow(Publish).to receive(:new).with(a: 1, b:2).and_return(an_instance)`

**Comment by AlexWayfer** [comment]
> You can assert that a specific instance is created by stubbing new, e.g. allow(Publish).to receive(:new).with(a: 1, b:2).and_return(an_instance)

`an_instance` not found in code of `rspec-mocks`, and using this code triggers exception:

```
NameError:
       undefined local variable or method `an_instance' for #<RSpec::ExampleGroups::GuardSassRunner::Run:0x000055905f04c140>
       Did you mean?  an_instance_of
```

But when I'm using `.and_return(an_instance_of(::Sass::Engine))`, I'm getting:

```
NoMethodError:
       undefined method `render' for #<RSpec::Matchers::BuiltIn::BeAnInstanceOf:0x000055b87bd41d70>
```

Code:

```ruby
allow(::Sass::Engine).to receive(:new).with('', {
  :filesystem_importer => Guard::Sass::Importer,
  :load_paths          => ['sass'],
  :style               => :nested,
  :debug_info          => false,
  :line_numbers        => false,
  :syntax              => :sass,
  :filename            => 'a.sass',
  :all_on_start        => false,
  :output              => "css",
  :extension           => ".css",
  :shallow             => false,
  :noop                => false,
  :hide_success        => false
}).and_return(an_instance_of(::Sass::Engine))

expect_any_instance_of(::Sass::Engine).to receive(:render)

subject.new([pattern], formatter, defaults).run(['a.sass']) # <= triggers `new` and `render`
```

**Comment by JonRowe** [comment]
Yes it was pseudo code, 'an_instance' is a local variable you need to
create, this could either be a real instance or a double

**Comment by AlexWayfer** [comment]
@JonRowe, thank you! I don't want to write a long options twice, but `double` helps me.
