### ISSUE TITLE
Can't use ordered and count at the same time

### ISSUE THREAD

**Issue by Bastes** [rspec/rspec-mocks#1157]
(rspec-mocks 3.5.0, rspec 3.5.0)

So, here's the kind of thing I did:

```
allow(my_little_double).to receive(:my_little_method)

5.times { |i| my_little_double.my_little_method i }

expect(my_little_double).to have_received(:my_little_method).exactly(5).times
expect(my_little_double).to have_received(:my_little_method).with(0).ordered
expect(my_little_double).to have_received(:my_little_method).with(1).ordered
expect(my_little_double).to have_received(:my_little_method).with(2).ordered
expect(my_little_double).to have_received(:my_little_method).with(3).ordered
expect(my_little_double).to have_received(:my_little_method).with(4).ordered
```

Which fails saying "received :my_litte_method out of order" on the first have_received(...).with(...) line.

If I remove the count, the message can have been received more times than expected and still pass, if I remove the .ordered lines I have no way to check that the method has been called with the right arguments.

Shouldn't there be a way to check for both without retorting to splitting you spec in two?

**Comment by myronmarston** [comment]
Unfortunately, there are some bugs around `ordered` with spies.  See #916.  We haven't yet figured out a good fix. I believe your issue is related.
