### ISSUE TITLE
rspec-mocks only has a gem requirement for rubocop for 2.0 >= Ruby <= 2.1

### ISSUE THREAD

**Issue by agrberg** [rspec/rspec-mocks#1168]
The only mention of `rubocop` is in the [Gemfile:17](https://github.com/rspec/rspec-mocks/blob/master/Gemfile#L17). I'm not sure what version would be appropriate to add and if it should be here on in the gemspec.

**Comment by pirj** [comment]
There are 546 offences in `rspec-mocks` with `rubocop` 0.52.1.
There's no much point to update it before the offences are fixed.
I don't see a good reason for moving RuboCop dependency declaration to gemspec.
