### ISSUE TITLE
The correct way of making own Argument Matchers

### ISSUE THREAD

**Issue by shlajin** [rspec/rspec-mocks#1179]
Hello!
I apologise in upfront if this is the wrong place to ask such kind of questions; Haven't found any suggestions where to do that in the contributing guide.

Anyways, Readme file states:
> you are free to create your own custom RSpec::Matchers.

But no information of how this can be achieved is not given.

The only way I was able to find on my own is to monkey-patching `RSpec::Mocks::ArgumentMatchers`, but I sense I'm doing it wrong.
For example. say, I need `anything_but(value)` matcher, so I can use it in this way:
```
expect(something).to include hash: { with_value: anything_but(nil) }
```

```
class AnythingBut
  def initialize(*bad_values)
    @bad_values = bad_values
  end

  def ===(value)
    @bad_values.include?(value)
  end

  def description
    "anything_but(#{@bad_values.map(&:inspect).join(', ')})"
  end
end

module RSpec::Mocks::ArgumentMatchers
  def anything_but(*args)
    AnythingBut.new(*args)
  end
end
```

I believe a better way should exist and it would be so good if docs tell how.

**Comment by myronmarston** [comment]
The simplest way is to use `RSpec::Matchers.define`:

``` ruby
RSpec::Matchers.define :anything_but do |*bad_values|
  match { |value| bad_values.include?(value) }
end
```

**Comment by xaviershay** [comment]
Relevant docs: https://relishapp.com/rspec/rspec-expectations/v/3-6/docs/custom-matchers

**Comment by markaschneider** [comment]
The only issue I see with using `RSpec::Matchers.define` is that it can then be invoked like this, which doesn't read well:

```ruby
expect(something).to anything_but(something_else)
```

**Comment by myronmarston** [comment]
@markaschneider then define it with wording that does read well:

``` ruby
RSpec::Matchers.define :be_anything_but do |*bad_values|
  match { |value| bad_values.include?(value) }
end

expect(something).to be_anything_but(something_else)
```
