### ISSUE TITLE
How to avoid/disable warning “…unable to restore the original `…` method” due to stubbing frozen object?

### ISSUE THREAD

**Issue by jirutka** [rspec/rspec-mocks#1190]
I don’t share the stubbed object between multiple examples/tests, so I don’t need to reset it into the original state. However, I don’t know how to prevent RSpec from trying to to reset it, nor how to disable this warning without disabling all warnings. Also I can’t prevent the object being frozen, it’s done in external code (I’m writing an integration test).

**Comment by myronmarston** [comment]
I don't think we can advise without some example code showing a situation on which you are receiving this warning.  Can you provide some executable code that reproduces the issue?

**Comment by jirutka** [comment]
It’s directly related to #527. Do you still need a specific example?

**Comment by myronmarston** [comment]
Yes please.  Something based on your specific use case would be useful.

**Comment by jirutka** [comment]
Okay, there’s a minimal example demonstrating the issue.

```rb
class ThirdParty
  def initialize(x)
    @x = x.freeze
  end

  def call
    @x.hello
  end
end

class Foo
  def hello
    'Hello, world!'
  end
end

describe 'Integration' do
  let(:foo) { Foo.new }
  let(:third_party) { ThirdParty.new(foo) }

  before do
    expect( foo ).to receive(:hello).and_call_original
  end

  it 'calls my foo' do
    expect( third_party.call ).to eq 'Hello, world!'
  end
end
```

```sh
$ rspec example_spec.rb
WARNING: rspec-mocks was unable to restore the original `hello` method on #<Foo:0x007fd489aa59c8> because it has been frozen.  If you reuse this object, `hello` will continue to respond with its stub implementation. Warning generated from spec at `./example_spec.rb:25`.
.

Finished in 0.01288 seconds (files took 0.23944 seconds to load)
1 example, 0 failures
```

**Comment by JonRowe** [comment]
If this is an integration test, don't stub it, you should be asserting that for a given input you get a given output. You can then use a test double as a collaborator elsewhere to avoid duplicated expensive calls.

**Comment by myronmarston** [comment]
Or use a full-on test double (instead of a partial double), which RSpec won't try to restore at the end of each spec.

**Comment by jirutka** [comment]
That’s not applicable. I’m writing a module that works as a drop-in replacement for some built-in functionality (that is not customizable/extensible), so I need to ensure that my extension is really used instead of the built-in code.

It’s this: https://github.com/jirutka/asciidoctor-include-ext/blob/master/spec/integration_spec.rb.

Meanwhile I used an ugly workaround:

```rb
foo.define_singleton_method(:freeze) { self }
```

**Comment by myronmarston** [comment]
Given your constraints, that's probably the right way to go.

**Comment by jirutka** [comment]
I still don’t think that the current RSpec’s behaviour is correct. IMO it should be possible to disable automatic stub reset, for cases when the stub is not shared between examples/tests.

**Comment by myronmarston** [comment]
RSpec has always provided the guarantee that when you stub a partial double, it will remove the stub when the example completes.  AFAIK, you're the first user to ever ask for anything different.  As such, it's not something that we're willing to take on the maintenance burden for at this time.  If we hear that many users want the ability to prevent RSpec from resetting partial doubles, we can revisit.
