### ISSUE TITLE
`undefined method `[]' for #<Hash:> (NoMethodError)` after `expect_any_instance_of(Hash).not_to receive(:[])`

### ISSUE THREAD

**Issue by AlexWayfer** [rspec/rspec-mocks#1201]
```ruby
require 'rspec'

RSpec.describe 'work with Hash' do
  it do
    expect_any_instance_of(Hash).not_to receive(:[])
  end
end
```

```
$ rspec rspec.rb
Traceback (most recent call last):
	14: from /home/alex/.rbenv/versions/2.5.0/bin/rspec:23:in `<main>'
	13: from /home/alex/.rbenv/versions/2.5.0/bin/rspec:23:in `load'
	12: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
	11: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	10: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	 9: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
	 8: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
	 7: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
	 6: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `ensure in report'
	 5: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
	 4: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:193:in `close_after'
	 3: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:193:in `ensure in close_after'
	 2: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:238:in `close'
	 1: from /home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
/home/alex/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:58:in `registered_listeners': undefined method `[]' for #<Hash:0x000055ba8346ebd0> (NoMethodError)
```

**Comment by myronmarston** [comment]
`expect_any_instance_of` is a sharp object, and provides you with the opportunity to break RSpec itself.  RSpec uses hashes internally for many things (as you might expect) and has to use `Hash#[]=` to store values in a hash. So if you set up that expectation--which prevents `Hash#[]=` from working for the rest of the example--it breaks RSpec, unsurprisingly.  I don't think there's any way we can fix this outside of avoiding the use of `Hash` within RSpec, which isn't going to happen. (Plus, it would just shuffle the problem to some other core type that a user could similarly expect not to be used).

**Comment by AlexWayfer** [comment]
OK, but `Hash` object should have `#[]` method. I'm for meaningful messages from RSpec about its internal work and conflicts with its public API.

**Comment by myronmarston** [comment]
> OK, but `Hash` object should have `#[]` method.

Yep, this is why you can't do `expect_any_instance_of(Hash).not_to receive(:[])`, as that essentially removes the `#[]` method from `Hash`.

> I'm for meaningful messages from RSpec about its internal work and conflicts with its public API.

I'm also for that, as long as we can provide it for all the cases, and not just for a select few that users have happened to report.  Unfortunately, I don't know of a way to do that.  See the conversation in #1200 for further discussion on this.

**Comment by AlexWayfer** [comment]
> Unfortunately, I don't know of a way to do that. See the conversation in #1200 for further discussion on this.

Yes. Sorry for kind of duplication of this issue (exceptions are different).
