### ISSUE TITLE
stub subclass' class method uses cached superclass' class method

### ISSUE THREAD

**Issue by caffeinated-tech** [rspec/rspec-mocks#1203]
Given two classes:
```
class Bar
  def self.foo(a)
  end
end
```

```
class Baz < Bar
  def self.foo(a, b)
    ...
    super(a)
  end
end
```

I want to stub out the method foo for my tests:
```
 allow(Bar).to receive(:foo).and_return(...)
```

But when testing Baz, it will raise the error:
```     
ArgumentError:
  Wrong number of arguments. Expected 1, got 2.

```

So I add a specific test for the subclass Baz:
```
 allow(Bar).to receive(:foo).and_return(...)
 allow(Baz).to receive(:foo).and_return(...)
```

But it still fails (even when using `with(any_args)`). Delving into the code shows that `RSpec::Mocks::Space` reuses the first stub as it is the same method by inheritance. This would be fine, but my subclass expects 2 arguments rather than 1, so the call still fails.

Simply swapping the two stubs fixes this problem:

```
 allow(Baz).to receive(:foo).and_return(...)
 allow(Bar).to receive(:foo).and_return(...)
```

Looking at the code, I don't think this behavior should be changed as stubbing inherited methods is useful. Maybe a line in the documentation warning of this scenario would help.

**Comment by JonRowe** [comment]
I can't replicate your failure, I've tried both in our spec suite and with the latest version of RSpec and a dummy file:

```Ruby
class Bar
  def self.foo(a)
  end
end

class Baz < Bar
  def self.foo(a, b)
    super(a)
  end
end

RSpec.describe do
  it "works" do
    allow(Bar).to receive(:foo).and_return(:foobar)
    expect(Baz.foo(:a, :b)).to eq :foobar
  end

  it "works" do
    allow(Bar).to receive(:foo).and_return(:foobar)
    expect(Baz).to receive(:foo).and_return(:foobaz)
    expect(Baz.foo(:a, :b)).to eq :foobaz
  end

end
```

Can you provide a similar snippet which fails?

**Comment by xaviershay** [comment]
Closing per policy, please reopen with failing code!
