### ISSUE TITLE
Suggested improvement: Expect something to invoke a spy

### ISSUE THREAD

**Issue by keithbro** [rspec/rspec-mocks#1205]
It might be cool if it was possible to do something like

````
describe Bar do
  describe '.baz!' do
    subject(:baz!) { Bar.baz! }

    # Bar.baz! contains a call to Foo.bar that we want to spy on
    before { allow(Foo).to receive(:bar).and_return(true) }

    it { expect { baz! }.to invoke(Foo, :bar) }
  end
end
````

currently, you can do:

````
before do
  allow(Foo).to receive(:bar).and_return(true)
  baz!
end

it { expect(Foo).to have_received(:bar) }
````

But imagine if you had some other test that meant that you don't want to put the call in the `before` block:

````
it { expect { baz! }.to change { Foo.count }.by(1) }
it { expect(Foo).to have_received(:bar) }
````

This doesn't work because `baz!` is the subject and only runs once. It has already run and no changes are detectable in the `it` block.

Maybe there's a nice way to do this that I'm missing.

**Comment by myronmarston** [comment]
This has been discussed extensively before in #1108 and rspec/rspec-expectations#934 and isn't something we think makes sense as part of RSpec's built-in API.  Please read those issues for more details on why we feel that way.  There's an extension gem that provides it, though:

https://github.com/zverok/saharspec#matchers

**Comment by keithbro** [comment]
Thanks for the quick response 👍  I'll check out those links.
