### ISSUE TITLE
found typos in document.

### ISSUE THREAD

**Issue by dizy64** [rspec/rspec-mocks#1216]
There is nothing special about it.

I read a document and found a typographical error.

https://github.com/rspec/rspec-mocks/blob/master/features/verifying_doubles/partial_doubles.feature#L28

saave -> save

**Comment by JonRowe** [comment]
It'd be great if you could open a PR to fix this

**Comment by JonRowe** [comment]
Sorry! This typo is actually deliberate, my apologies I should have checked better, thank you very much for taking the time to help us out.
