### ISSUE TITLE
an_instance_of(String) not matching a string? Nor does anything

### ISSUE THREAD

**Issue by krainboltgreene** [rspec/rspec-mocks#1220]
### Your environment
* Ruby version: 2.5.0
* rspec-mocks version: 3.7.1

### Steps to reproduce
Have a test with:

``` ruby
      it "returns as json" do
        expect(
          subject
        ).to eq(
          {
            "data" => {
              "type" => "accounts",
              "attributes" => {
                "email" => "kurtis@example.com",
                "password" => anything
              }
            },
            "meta" => {
              "jsonapi_version" => "1.0"
            },
            "included" => [
              {
                "data" => {
                  "id" => "a",
                  "type" => "widget",
                  "attributes" => {
                    "title" => "Widget A"
                  }
                }
              }
            ]
          }
        )
      end
```

### Expected behavior

Complete match.

### Actual behavior

```
  1) SmartParams#as_json with a reasonably good params returns as json
     Failure/Error:
       expect(
         subject
       ).to eq(
         {
           "data" => {
             "type" => "accounts",
             "attributes" => {
               "email" => "kurtis@example.com",
               "password" => anything
             }

       expected: {"data"=>{"type"=>"accounts", "attributes"=>{"email"=>"kurtis@example.com", "password"=>anything}}, "...>"1.0"}, "included"=>[{"data"=>{"id"=>"a", "type"=>"widget", "attributes"=>{"title"=>"Widget A"}}}]}
            got: {"data"=>{"type"=>"accounts", "attributes"=>{"email"=>"kurtis@example.com", "password"=>"bd564a75e2a0...>"1.0"}, "included"=>[{"data"=>{"id"=>"a", "type"=>"widget", "attributes"=>{"title"=>"Widget A"}}}]}

       (compared using ==)

       Diff:
       @@ -1,4 +1,4 @@
       -"data" => {"type"=>"accounts", "attributes"=>{"email"=>"kurtis@example.com", "password"=>anything}},
       +"data" => {"type"=>"accounts", "attributes"=>{"email"=>"kurtis@example.com", "password"=>"bd564a75e2a04a4ca4f2aec24c18b46203c2d316d88ff5bee3dd57067d951c76"}},
        "included" => [{"data"=>{"id"=>"a", "type"=>"widget", "attributes"=>{"title"=>"Widget A"}}}],
        "meta" => {"jsonapi_version"=>"1.0"},
```

**Comment by mikegee** [comment]
`an_instance_of` and `anything` are part of rspec-mocks' argument matching functionality. I suppose they weren't intended to be used elsewhere.

I was able to make a simplified version of your example work by changing `eq` to `match`, though. Maybe give that a try?

**Comment by myronmarston** [comment]
> `an_instance_of` and `anything` are part of rspec-mocks' argument matching functionality. I suppose they weren't intended to be used elsewhere.

They don't provide as nice of output, but they do work just fine as matchers in an expression like what @krainboltgreene is doing.

> I was able to make a simplified version of your example work by changing `eq` to `match`, though. Maybe give that a try?

This is exactly what's going on, and it's by design.  `eq` only matches when the objects are strictly `==`.  That's the semantics `eq` is documented to provide.  `{key: anything}` is _not_ `==` to `{key: "some value"}`.

OTOH, `match` is designed to allow you to embed matches in data structures to "fuzzy match" like what you are trying to do--so use that!

**Comment by krainboltgreene** [comment]
Ahhhhh! That must be it, thanks so much!
