### ISSUE TITLE
Expect...with() should be able to specify constraints in argument list

### ISSUE THREAD

**Issue by ChrisSandison** [rspec/rspec-mocks#1223]
`expect(someObject).to receive(:a_method).with(arg1, arg2, [value1, value2, value3], {key1: 'a', key2: 'b'})`

Should support something like

`expect(someObject).to receive(:a_method).with(arg1, arg2, array_including(value1, value2, value3), hash_including({key1: 'a', key2: 'b'}))`

I can begin working on a PR for something like this

**Comment by JonRowe** [comment]
It does
