### ISSUE TITLE
anything method sometimes doesn't work

### ISSUE THREAD

**Issue by tmkw** [rspec/rspec-mocks#1234]
### Subject of the issue
anything method sometimes doesn't work...
Suppose there is a line as bellow:
```
allow(processor).to receive(:signup).with(anything, signup_args).and_raise
```
The mock named "processor" is intended to receive "signup" with a session object and a signup argument struct.
The session object is actually Rack's session object. That isn't important in my case, so I used anything method here.

However, rspec doesn't work as I intended.
The error was:
```
#<InstanceDouble(TodoApp::RequestProcessor) (anonymous)> received :signup with unexpected arguments
         expected: (anything, #<struct TodoApp::SignupArgs ...>)
              got: ({"session_id"=>"0d4aba0c32c6859401993bad15094e7b8226aea6cac75dfd8929eca11ab6a711", ...}, #<struct TodoApp::SignupArgs ...>)
       Diff:
       @@ -1,3 +1,3 @@
       -["anything",
       - #<struct TodoApp::SignupArgs user_id="", password="aiueo123", confirm_password="aiueo123">]
       +[{"session_id"=>"0d4aba0c32c6859401993bad15094e7b8226aea6cac75dfd8929eca11ab6a711", ...},
       + #<struct TodoApp::SignupArgs user_id="", password="aiuoe123", confirm_password="aiuoe123">]
```
This diff result  seems strange because it compares a string "anything"  and hash object.

From my understanding,  rspec-mock's anything method  can be used  as an argument place holder, regardless of actual argument object type.

In other tests, anything method  works fine, so this error is confusing to me.

Are there any possible reasons?

thanks.
### Your environment
* Ruby version:  2.5
* rspec-mocks version: 3.7.0

### Steps to reproduce
Sorry, I couldn't find how to reproduce this.

### Expected behavior
anything method is used to ignore actual argument object type.

### Actual behavior
a string "anything" is used to compare the actual argument.

**Comment by myronmarston** [comment]
The `anything` matcher _does_ always work (it's [hard coded to return true](https://github.com/rspec/rspec-mocks/blob/v3.7.0/lib/rspec/mocks/argument_matchers.rb#L151)), but the diff obscures the fact.  RSpec's differ is purely a textual diff.  RSpec converts the two values to strings using `inspect` (or `description` on a matcher) and uses diff-lcs to print a string diff.  Naturally, the string form of `anything` differs from whatever you are matching against, and it confusingly appears in the diff, leading users to the reasonable conclusion that the `anything` matcher isn't working when it is.  In your example, it's the 2nd argument that is failing to match.  `anything` just gets printed in the diff as well.

We have plans to improve the differ, but for now this is the unfortunate behavior.
