### ISSUE TITLE
ActiveRecord classes stubbed with stub_const are cached

### ISSUE THREAD

**Issue by keidax** [rspec/rspec-mocks#1240]
### Subject of the issue
I think this is the right place to report this issue, but it's possible rspec-rails is more appropriate.

If an ActiveRecord class has a temporary subclass created and stubbed with `stub_const`, and a record using the temporary class is loaded from the database, then the temporary class can be cached in the `ActiveSupport::Dependencies::Reference` store. This cache will persist between example groups.

If `stub_const` is later used to create another temporary subclass with the same name as the first, then the first stubbed class is still used for records loaded from the database.

### Your environment
* Ruby version: 2.4.4
* rspec-mocks version: 3.8.0
* Rails version: 5.2.1

### Steps to reproduce
I created a fresh Rails project and ran `rspec --init`. There's only one model:
``` ruby
class User < ApplicationRecord
end
```
`schema.rb` just has the `users` table:
``` ruby
ActiveRecord::Schema.define(version: 2018_10_05_030413) do

  create_table "users", force: :cascade do |t|
    t.string "type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
```
Specs to reproduce the issue:
``` ruby
require "rails_helper"

describe User do
  describe "with a stubbed subclass" do
    before do
      stub_const "FooUser", Class.new(User)
      FooUser.create!
    end

    it "loads an instance of the class" do
      expect(User.last.class).to be(FooUser)
    end
  end

  describe "with another stubbed subclass" do
    before do
      stub_const "FooUser", Class.new(User)
      FooUser.create!
    end

    it "loads an instance of the class" do
      expect(User.last.class).to be(FooUser)
    end
  end
end
```

### Expected behavior
The specs pass.

### Actual behavior
The second spec fails, because it uses the `FooUser` class loaded in the first example.
```
$ bin/rspec
.F

Failures:

  1) User with another stubbed subclass loads an instance of the class
     Failure/Error: expect(User.last.class).to be(FooUser)

       expected #<Class:47044797595500> => FooUser(id: integer, created_at: datetime, updated_at: datetime, type: string)
            got #<Class:47044803766640> => FooUser(id: integer, created_at: datetime, updated_at: datetime, type: string)

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.


       Diff:

     # ./spec/models/user_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 0.03604 seconds (files took 0.77661 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/models/user_spec.rb:25 # User with another stubbed subclass loads an instance of the class
```
I _can_ get this to pass by adding these lines:
``` ruby
  after do
    ActiveSupport::Dependencies::Reference.instance_variable_get(:@store).delete("FooUser")
  end
```
but I'm not sure if something so specific to ActiveSupport belongs in this project.

**Comment by JonRowe** [comment]
I'm afraid this doesn't belong as an issue on this project, if there was a public way to reset this dependency cache, it might be considered for inclusion in `rspec-rails` but this is a bit of an edge case and would possibly cause more harm by automatically resetting it between tests. It also seems like a bit of a bug in the cache.

Additionally can I ask why you are testing in this fashion? Creating a real temporary class would work around this:

```
it do
  foo_user_klass = Class.new(User)
  foo_user_klass.create!
end
```

**Comment by boardfish** [comment]
For anyone that's happening upon this, calling `.dup` on the parent class appears to work. I had this happen when even though `stub_const` unassigns the constant, it's still returned from `.descendants`. Not sure it's _the_ perfect solution, but it's there.
