### ISSUE TITLE
Multi-count expectations on any instance of a class

### ISSUE THREAD

**Issue by p-mongo** [rspec/rspec-mocks#1242]
### Subject of the issue

I am using the following pattern:

<pre>
    expect_any_instance_of(C).to receive(:meth).exactly(3).times.and_call_original
</pre>

It seems that all 3 invocations are required by rspec-mocks to happen on the same instance of C, where in my application there are 3 instances of C and each gets meth invoked on it once.

<pre>
class C
  def meth
  end
end

describe 'Foo' do
  it 'calls C.meth three times' do
    expect_any_instance_of(C).to receive(:meth).exactly(3).times.and_call_original

    C.new.meth
    C.new.meth
    C.new.meth
  end
end
</pre>

Result:

<pre>
Failures:

  1) Foo calls C.meth three times
     Failure/Error: C.new.meth
       The message 'meth' was received by #<C:47229324748320 > but has already been received by #<C:0x000055e8de3feb80>
     # ./spec/foo_spec.rb:13:in `block (2 levels) in <top (required)>'
</pre>

How can I assert that the method is invoked 3 times, either with or without asserting the distinctiveness of instances of C on which it is invoked?

### Your environment
* Ruby version: 2.5.1
* rspec-mocks version: 3.8.0

### Steps to reproduce
Repro: https://github.com/p-mongo/tests/tree/master/rspec-multi-instance-expectations

### Expected behavior

I should be able to assert that the method is called the required number of times even if invocations are on different class instances.

Note that using allow_any_instance_of instead of expect_any_instance_of does pass, and I can pass a block to it to do my own counting, however I don't know how to invoke the original method from the block and specifying and_call_original makes my block not get called:

<pre>
WARNING: You're overriding a previous stub implementation of `scan!`. Called from /home/w/apps/ruby-driver/lib/mongo/server/monitor.rb:130:in `block (2 levels) in run!'.. Called from /home/w/apps/ruby-driver/lib/mongo/server/monitor.rb:130:in `block (2 levels) in run!'.
</pre>

(message from the actual ruby driver project)

### Actual behavior

I am not able to enforce that my method is called a specific number of times while also calling the original implementation of the method.

**Comment by JonRowe** [comment]
Sure it is:
```
e.g.

instances = (1..3).to_a.map do
  klass.new.tap do |instance|
    expect(instance).to receive(:msg).once
  end
end
expect(klass).to receive(:new).extactly(3).times.and_return { instances.shift }
```

**Comment by JonRowe** [comment]
Theres nothing that prevents you from returning a real instance in a stub, you can even use `and_call_original` to provide real behaviour, the important thing is you control whats happening, in order to be unambigious.

**Comment by p-mongo** [comment]
I see, I confused instance_double with double. However, the class in question's initialize looks like this:

https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/server/monitor.rb#L58

... and is invoked by Server's constructor which builds those needed objects. Hence it is still not at all clear to me how to make this all work.

In this case, any instance expectations are exactly what I want. There is a complex process that results in an object hierarchy being constructed, and it is convenient to assert that a certain method is called (or not called) *in addition to* other assertions verifying user-visible behavior.

**Comment by JonRowe** [comment]
The second code snippet I require will allow 3 instances to receive msg once, if you need a random 3 instances from a much greater set thats trickier, but can still be achieved:

```
instances_allocated = []
n = 0
expect(klass).to receive(:new).and_wrap_original do |o, *args
  instance = o.call(*args)
  instances_allocated << instance
  allow(instance).to receive(:msg).and_wrap_original do |m, *args|
    n += 1
    m.call(*args)
  end
end
expect(n).to eq 3
```

This is more complicated of course, but so is what you're trying to do, it's still a lot simpler than the existing any instance functionality, and a lot simpler than our implementation trying to do either behaviour would be.

**Comment by p-mongo** [comment]
I am not sure what you mean by "existing any instance functionality", but I had this written (which doesn't work):

<pre>
        expect_any_instance_of(Mongo::Server::Monitor).to receive(:scan!).
          exactly(SpecConfig.instance.addresses.length).times.and_call_original
</pre>

I am not claiming this is easy to implement in rspec-mocks but isn't the job of a mocking library to implement functionality like this so that the application does not need to?

**Comment by p-mongo** [comment]
A possible solution API-wise is to keep expect_any_instance_of as it is and add a plural version which will allow different instances to receive the calls:

<pre>
        expect_any_instance<b>s</b>_of(Mongo::Server::Monitor).to receive(:scan!).
          exactly(SpecConfig.instance.addresses.length).times.and_call_original
</pre>

**Comment by JonRowe** [comment]
It will work, provided you don't mean multiple instances

**Comment by p-mongo** [comment]
Is there a discussion one can read somewhere about ceasing development of any instance functionality? I am curious how this decision was reached.

**Comment by xaviershay** [comment]
Not exactly what you asked for (I'm not sure we have a canonical source for discussion), but some context here: https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance

**Comment by JonRowe** [comment]
The relevant paragraph from those docs:

> This feature is sometimes useful when working with legacy code, though in general we
discourage its use for a number of reasons:
>
> * The rspec-mocks API is designed for individual object instances, but this feature operates on entire classes of objects. As a result there are some semantically confusing edge cases. For example, in expect_any_instance_of(Widget).to receive(:name).twice it isn't clear whether a specific instance is expected to receive name twice, or if two receives total are expected. (It's the former.)
> * Using this feature is often a design smell. It may be that your test is trying to do too much or that the object under test is too complex.
> * It is the most complicated feature of rspec-mocks, and has historically received the most bug reports. (None of the core team actively use it, which doesn't help.)

The consensus amongst the team was that it wasn't worth expanding the feature set either, for those same reasons.

**Comment by JonRowe** [comment]
Thanks for finding those docs @xaviershay I'd totally forgotten we'd written this behaviour up!

**Comment by Gerst20051** [comment]
is that a typo? shouldn't `extactly` be `exactly` instead?
