### ISSUE TITLE
Threads and method stubs

### ISSUE THREAD

**Issue by tonobo** [rspec/rspec-mocks#1243]
Well, sometimes the method expectation didn't work properly. I'm currently don't know how to reproduce them consistently. Maybe you've already heard about something like that.

I'm trying to test a kind of routine which communicates over an strictly thread safe database and needs to be triggered from 2 different routines. The first thread triggers the second one using a `Typhoeus` stub. The thread tracks some usage data within thread variables. 

So whats going on (just abstract):

```ruby
# let(:_one) { ... }
# let(:_two) { ... }

$thread_var = nil
expect(_one).to receive(:run) do
  $thread_var = Thread.new { _two.run }
end
expect(_one).to receive(:moo).ordered
expect(_two).to receive(:moo).ordered

Thread.new{_one.run}.join
$thread_var.join
```

I guess the success ratio is about 1/10. 10 successful runes comes with one failed one.

### Your environment
* Ruby version: 2.3 / 2.5
* rspec-mocks version: 3.8 / 3.7

**Comment by JonRowe** [comment]
Hi, we are aware that rspec-mocks is not fully thread safe, but I'm having trouble understanding the description of your specific problem. 

Is calling your stubbed methods not resulting in the stub being executed? (e.g. the original method is being called) or are you not receiving the expected message counts?

If its the former, thats a new issue I don't think we've seen, if it's the later see if #1236 fixes it for you.

**Comment by tonobo** [comment]
When using `allow_any_intance_of(My::Class).to receive(:moo)` it works quite better

**Comment by tonobo** [comment]
Sorry, its quite hard to describe :smile: 
I'll try with a more abstact sample. 

```ruby
class MyClass
  def foo
    # Normally this shouldn't be ever called, but due to Threads this happens sometimes.
    raise "This shouldn't be called anytime"
  end

 def run
   foo
 end
end

let (:_one) { MyClass.new } 
let (:_two) { MyClass.new } 

it 'should just work' do
  $thread_var = nil
  expect(_one).to receive(:run) do
    _one.foo
    $thread_var = Thread.new { _two.run }
  end
  expect(_one).to receive(:foo)
  expect(_two).to receive(:foo)
end
Thread.new{_one.run}.join
$thread_var.join
```

When setting up global stubs then this just works, by using this at instance level then it works sometimes. I've only trouble with the instance based stubs in threaded environments. Maybe it's better to understand?

**Comment by tonobo** [comment]
I've applied the patches from referenced pull request and nothing has changed. The tests will fail sometimes.

**Comment by mikegee** [comment]
I think the problem is right here:

```ruby
    $thread_var = Thread.new { _two.run }
  end
  expect(_one).to receive(:foo)
  expect(_two).to receive(:foo)
```
That new thread is given a block to run, but that thread might not invoke its block until after you've made those two expectations in the main thread.

This doesn't look like an issue with RSpec's thread-safety or lack thereof to me.

**Comment by tonobo** [comment]
Well it's pretty hard to guess where the issue comes from. I can guarantee that I've registered the method stubs before invoking the Thread, but it looks like the stubs sometimes aren't correctly set. I'm closing this for now because I'm unable to reproduce that. Maybe I'll reopen later. Thank you very much guys.
