### ISSUE TITLE
[Discussion] Signature for stubbing instances

### ISSUE THREAD

**Issue by kurko** [rspec/rspec-mocks#1262]
### Subject of the issue

In the codebases I have worked with in the past few years, the following patterns repeats over and over: stub `:new` then mock a method. It makes the codebase longer and terse.

```rb
user = instance_double(User)

# Step 1: stub instantiation
allow(User)
  .to receive(:new)
  .with(name: 'Myron Marston')
  .and_return(user)

# Step 2: mock what you expect to be called
expect(user)
  .to receive(:first_name)
  .with(arg: anything)
  .and_return('Myron')

described_class.new(user: user)
```

This is the sort of thing that could be collapsed into a better API. Albeit similar, it's not the same as the monkey-patchy `expect_any_instance_of` because with the example you're able to inject the `user` double into classes, whereas the monkey patch is pervasive everywhere.

I'm not sure what would be the ideal API to collapse those steps into one, but it's definitely a thing we can improve with the community help.

```rb
user = instance_double(User)

expect(User)
  .instantiated_with(name: 'Myron Marston')
  .as(user)
  .to receive(:first_name)
  .with(arg: anything)
  .and_return('Myron')

described_class.new(user: user)
```

Above suggestion is still pretty verbose, although better than separate steps, but it seems to include only the precise functions we need to call. Just a first draft.

Would love opinions on this.

**Comment by JonRowe** [comment]
:wave: First off you can streamline this further with the existing api already:
```
user = instance_double(User, first_name: "Myron")

allow(User)
  .to receive(:new)
  .with(name: 'Myron Marston') { user }

expect(user)
  .to receive(:first_name)
  .with(arg: anything)

described_class.new(user: user)
```

Which would produce the same reduction in lines as your example.

Secondly, I think I'm open to the idea of an `be_instantiated_with(args)` matcher, shortcutting `receive(:new).with(args)` to a one liner, but its actually "more characters" so its not a saving, and does it confer extra meaning?

I don't think that we should add a `.as()` but it could be done easily an alias to `and_return`, but those making it less explicit typically reach for the block short hand instead (which works with any item in the chain).

Finally, we don't want to increase the api surface of `expect` so anything we do will have to be as a `to matcher` style expression.

**Comment by benoittgt** [comment]
@kurko does Jon's response help you? Can we close this issue?

I don't think we need `be_instantiated_with(args)` same for `.as()`.

**Comment by kurko** [comment]
Yeah. Thanks.
