### ISSUE TITLE
raising ActiveRecord::RecordInvalid raises argument error instead

### ISSUE THREAD

**Issue by nc-lot** [rspec/rspec-mocks#1267]
### Subject of the issue
```ruby
allow(subject).to receive(:something).and_raise(ActiveRecord::RecordInvalid)

begin
  subject.something
rescue => e
  e # ArgumentError (wrong number of arguments (given 0, expected 1)
end
```
This issue is caused by the assumption that all `ActiveRecordError`'s behave the same.
https://github.com/rspec/rspec-mocks/blob/24442456174015b6ab7a786e78abbf894d0bbc19/lib/rspec/mocks/message_expectation.rb#L143

### Your environment
* Ruby version: 2.5
* rspec-mocks version:
* rspec: 3.6.0

### Expected behavior
should raise `ActiveRecord::RecordInvalid` error

### Actual behavior
raises `ArgumentError`

**Comment by JonRowe** [comment]
Hi, This is the intended behaviour, if you have arguments you need for your error you must either instantiate your error before hand, or pass them into `and_raise`. e.g.
```
allow(subject).to receive(:something).and_raise(ActiveRecord::RecordInvalid.new(arg_a, arg_b))
```
or
```
allow(subject).to receive(:something).and_raise(ActiveRecord::RecordInvalid, arg_a, arg_b)
```
Just as you would have to do to use `raise` yourself, we can't predict non standard error behaviour.

**Comment by nc-lot** [comment]
@JonRowe okay that's fair enough with me.
