### ISSUE TITLE
Allow singular #time with #exactly, #at_least and #at_most

### ISSUE THREAD

**Issue by Pistos** [rspec/rspec-mocks#1269]
### Subject of the issue

Cannot write `(1).time`.  Must write either `(1).times` or `once`.

### Your environment

* Ruby version: 2.5.0
* rspec-mocks version: 3.8.0

### Steps to reproduce

    git clone https://github.com/Pistos/rspec-mocks-singular-count
    cd rspec-mocks-singular-count
    bundle install
    bundle exec rspec

### Expected behavior

* There should be no exceptions raised.
* We should be allowed to write `(1).time`, with it having the same meaning and behaviour as `(1).times`.

### Actual behavior

```
       expected no Exception, got #<NoMethodError: undefined method `time' for #<RSpec::Mocks::Matchers::Receive:0x000055e213191ce8>
       Did you mean?  times> with backtrace:
```

**Comment by xaviershay** [comment]
Thankyou for clear issue!

Given the error points you to the correct method, I'm slightly negative on adding an alias. I'm not sure I can justify that though:

Potential pro:
* Better English
* Matches rails?
* I suppose we've explicitly made an API that reads like English, so probably need to sleep in the bed we've made...

Potential con:
* Expand API surface area
* Another thing for people to know

Anyone else have an opinion?

**Comment by Pistos** [comment]
I don't see the harm in this, as everyone can continue in ignorance of the new addition to the API and continue to write `(1).times` or `.once`.  I'd even be fine with it if it were left out of the rdocs, etc. as an undocumented feature.

I just, personally, have never been a fan of things like `#once`, `#first` and `#last`.  I always reference arrays with `[0]` and `[-1]`, so that everything stays consistent.  (After all, we don't have `#second`, `#third`, `#four_hundred_and_fiftieth`, `#seventh_last`, or anything else like that.)

**Comment by JonRowe** [comment]
Given that the `times` method doesn't do anything, I think I'm ok with adding a `time` alias to it to tackle this, it should be documented if added though.

**Comment by benoittgt** [comment]
I just opened a PR for this topic https://github.com/rspec/rspec-mocks/pull/1271
