### ISSUE TITLE
Strange issue with Kernel#require stubbing

### ISSUE THREAD

**Issue by engineersmnky** [rspec/rspec-mocks#1278]
### Subject of the issue
I was attempting to assist with the [This SO Question](https://stackoverflow.com/questions/56499905/how-can-i-mock-a-ruby-require-statement-in-rspec/56500033?noredirect=1#comment99621442_56500033) where the OP wanted to stub Kernel#require for whatever reason. 

Originally I used the hacky `allow_any_instance_of` to handle the `require` portion and the test passed but upon further investigation, in an attempt to provide a more supportable answer, I noticed that the following allows the test to pass as well and I am not sure why: 

     describe 'require' do 
       it 'exhibits strange behavior in expectation' do 
         file = 'non-existent-file'
         expect(self).to receive(:require).with(file).and_return(true)
         require file
      end
    end

### Your environment
* Ruby version: 2.5.0
* rspec-mocks version: 3.5.0

### Expected behavior
Given the fact that `require` is not stubbed here I would have anticipated that a `LoadError` would be raised but instead the test passes. 

    require
      exhibits strange behavior in expectation

    Finished in 0.13503 seconds (files took 0.85895 seconds to load)
    1 example, 0 failures

I would love to understand why this occurs

**Comment by RossPatterson** [comment]
I'm the StackOverflow original poster engineersmnky mentions.  The use case is simply to attempt to unit-test a cli (based on a Thor derivative, not that it should matter) which allows the user to specify a file to be `require`d under certain circumstances, and to confirm that the cli does that.  I can't share the actual code, but I can discuss the case in general terms.

**Comment by engineersmnky** [comment]
I believe This may be a miss understanding on my part as to how `and_return` works, again hoping someone can clarify. My current assumption is that in this context `and_return` enforces a return value and is not part of the expectation itself. I think the test would be better written as 

       it 'stubbing require' do 
         file = 'non-existent-file'
         allow(self).to receive(:require).with(file).and_return(true)
         expect(self).to receive(:require).with(file)
         expect(require file).to eq(true)
      end

**Comment by JonRowe** [comment]
`expect`/`allow` `.to receive` are different edges of the same coin, they have the same api and the same affect. The difference being that the former will fail your test if you don't make the call matching its setup. In both cases `and_return` is specifying the return version of the stub, we don't offer verification of the original return value, thats kind of counter to the point of a stubbing library :)
