### ISSUE TITLE
unable to stub 'puts'

### ISSUE THREAD

**Issue by jcoyne** [rspec/rspec-mocks#1289]
### Subject of the issue
I'm unable to mock a method called `puts`

### Your environment
* Ruby version: 2.5.3
* rspec-mocks version: 3.8.1

### Steps to reproduce

```
  let(:log) { instance_double(Logger, puts: true) }

  it 'writes to the log' do
   log.puts "hi"
  end

     Failure/Error: log.puts "hi"
    NoMethodError:
       private method `puts' called on #<InstanceDouble(Logger) (anonymous)>
```

### Expected behavior
I should be able to mock `puts`

### Actual behavior
`NoMethodError`

**Comment by jcoyne** [comment]
My mistake here, I meant to stub `File` not `Logger`.

**Comment by JonRowe** [comment]
For future travellers, this is because `puts` is a private method on `Logger` :joy:
