### ISSUE TITLE
"Trace mode" for better error messages?

### ISSUE THREAD

**Issue by dorner** [rspec/rspec-mocks#1292]
At my company, we make heavy use of partial doubles. Our biggest pain points around onboarding tend to be RSpec, much more than Ruby or Rails. I think this could be mitigated with better errors when an expectation doesn't come to pass. 

Things I've seen:
* Expectations on the wrong instance of an object.
* Expectations on a class instead of an instance (e.g. where both respond to the same method).
* Expectation on a method that never actually got called because some other method was stubbed out by accident.

I have a working piece of code which uses TracePoint to record *all* methods being called, and storing them up to compare later on when an expectation fails. This does slow down specs, so I'd want to have a `--trace` option to turn it on (i.e. you'd only want it on while writing new specs, not while running your suite). But I've wrestled with RSpec often trying to track down why my method isn't being called - something like this could be a lifesaver.

I can start getting a PR together but I wanted to gauge interest on whether this is something that others feel would be useful to add to the gem?

**Comment by pirj** [comment]
I feel your pain at times as well. How do you plan to use this option, to run `rspec` with it against a specific example that doesn't pass?

Would you consider for the latter case to temporarily wrap the object with [`object_double`](https://relishapp.com/rspec/rspec-mocks/v/3-8/docs/verifying-doubles/using-an-object-double) to detect what was called on that object?

For the first case, calling on a wrong instance, wouldn't the output be too verbose if a lot of methods are being called? Would you only output those defined in the scope of the example and `let`s?

**Comment by dorner** [comment]
Yep, if you're writing tests and one fails but you can't figure out why, you'd rerun it with `--trace` turned on. It'll run more slowly but will print out some guesses as to what you meant.

Not sure I understand how wrapping the object with `object_double` would work? If I understand what you mean, it would help in the cases where you're stubbing a method that doesn't exist on the object, but wouldn't help in cases like where the method exists but is never called in actual code because it's called on a different object instead.

I don't necessarily want to limit the scope to defined objects because in the past I've added expectations on things like `my_record.some_association` which isn't actively defined. I have added some simple heuristics to catch common cases, though:
* If the exact method was called on another object of the same class, it'll only output those on the assumption that you probably meant that other object. Ditto for a method defined on a class but which you expected on an instance, or vice versa.
* If the exact method was called on some other object, it'll output those other objects.
* If a different method was called on that object, it'll show all the methods called only on that object.
* Failing that, it'll just print all the stubbed methods that were actually called (looking through `Rspec::Mocks.space.proxies`.

I do like the idea of actually printing out the names of the `let` variables or local variables defined in the method if they match an object being printed out rather than printing the name + address via `inspect`. I can look at adding that as well.

**Comment by JonRowe** [comment]
:wave: Hi, I like the idea, but I do wonder if this should be an extension gem rather than part of the core mocks library, it seems like it would add a rather large maintenance burden for something that should only ever be used in debugging a test, it could easily be added to specific tests by wrapping it with a metadata tag.

**Comment by dorner** [comment]
That was another direction I was thinking of taking it. Part of the problem is that it requires a bit of monkey patching to get it working right. I might just submit a PR to split out some of the logic which would allow me to just replace some methods rather than overriding them and inserting logic in the middle.

I'll wait a few more days to hear if anyone else wants to weigh in before proceeding.

**Comment by JonRowe** [comment]
I'm happy to help improve the public api to help integrate this, but an extension gem would heavily be the preferred route

**Comment by dorner** [comment]
Thanks for the input - that's the route I'll take. Expect a PR in the next few weeks once I figure out where the integration points would make the most sense! 👍
