### ISSUE TITLE
warning: removing `initialize' may cause serious problems

### ISSUE THREAD

**Issue by felipero** [rspec/rspec-mocks#130]
Hi,

I'm getting some annoying warnings when using rspec-mocks on integration tests. I'm using that to mock twitter and facebook services.

Example: 

/gems/rspec-mocks-2.8.0/lib/rspec/mocks/method_double.rb:105: warning: removing `initialize' may cause serious problems
/gems/rspec-mocks-2.8.0/lib/rspec/mocks/any_instance/recorder.rb:135: warning: removing`initialize' may cause serious problems

The mocks works well and specs are fine. But my output gets filled with these warnings.

Any idea about how to deal with it?

Thanks,

Felipe

**Comment by CoderMiguel** [comment]
since this thread is coming up in searches, I wanted to add that the `expect` syntax is favored over the `should` syntax: https://github.com/rspec/rspec-expectations/blob/main/Should.md
