### ISSUE TITLE
Spec involving Mutex passes in 3.8 but fails in 3.9

### ISSUE THREAD

**Issue by johann-koebbe-fidelity** [rspec/rspec-mocks#1327]
### Subject of the issue
This comes from a project that hasn't been updated in a few years, but I was recently bringing into the modern day. A spec involving the use of `Mutex.new` passes in 3.8 but fails in 3.9. I believe it is related to the change in rspec-mocks 3.9 that improves thread safety by using `Mutex`. 

### Your environment
* Ruby version: ruby 2.7.0p0 (currently, but experienced in 2.5 and 2.6 as well)
* rspec-mocks version: 3.8.2 (working), 3.9.1 (failing)

### Steps to reproduce
```ruby
class Mootex
  def mootex
    @mootex ||= Mutex.new
  end
end

RSpec.describe Mootex do
  describe 'memoization' do
    subject { described_class.new }

    it 'creates a mootex when one is not available' do
      subject.instance_variable_set('@mootex', nil)
      expect(Mutex).to receive(:new)
      subject.mootex
    end

    it 'does not create a mootex when one is available' do
      subject.instance_variable_set('@mootex', 'mootex')
      expect(Mutex).not_to receive(:new)
      subject.mootex
    end
  end
end
```

### Expected behavior
Both specs should pass.

### Actual behavior
```
  1) Mootex memoization creates a mootex when one is not available
     Failure/Error: @mootex ||= Mutex.new

     NoMethodError:
       undefined method `synchronize' for #<Object:0x0000000002376430>
```

**Comment by pirj** [comment]
I guess there's some overlap with `Support::Mutex.new`, but making expectations on `::Mutex` doesn't change the situation. 🤔

**Comment by JonRowe** [comment]
This happens because we use `Mutex` when it is available to make mocks threadsafe, there is no real `Support::Mutex` except on `1.8.7`, but we've done this by simply assigning the class to the constant.

See rspec/rspec-support#411

**Comment by JonRowe** [comment]
Closing here now, as the fix is over in `rspec-support`, however as a work around you could add `and_call_original` to generate mutexes.

**Comment by johann-koebbe-fidelity** [comment]
@JonRowe Thanks for the quick reply/fix! I tried

```ruby
    it 'creates a mootex when one is not available' do
      subject.instance_variable_set('@mootex', nil)
      expect(Mutex).to receive(:new).and_call_original
      subject.mootex
    end
```

but got the same error. It's not a big deal, though, since you already have a fix in place. I'll just leave the project pinned at 3.8.x until the fix hits the wild.

Many thanks!
