### ISSUE TITLE
`and_raise` does not reset exception backtrace when exception raised multiple times in single test

### ISSUE THREAD

**Issue by AldenPeterson** [rspec/rspec-mocks#1330]
### Subject of the issue

When using `and_raise` to generate an exception, the backtrace is not reset if the exception is rescued and reraised. This leads to a confusing stack trace when the test fails.

This seems to be because the same exception is reused in both cases even though the first time it was rescued.

### Your environment
* Ruby version: 
```
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

* rspec-mocks version:
```
$ gem list | grep rspec-mocks
rspec-mocks (3.9.1)
```

### Steps to reproduce

Create these two files:

```
$ cat -n lib/tester.rb 
     1  class Exceptional
     2
     3    def raiser(m)
     4      
     5      m.foo
     6    rescue
     7      puts 'Rescued exception'
     8      nil
     9    end
    10
    11    def nested_raiser(m)
    12      raiser(m)
    13
    14      m.foo
    15    end
    16  end
```

and

```
$ cat spec/tester_spec.rb 
$ cat spec/tester_spec.rb 
require './lib/tester'

RSpec.configure do |config|
    config.mock_with :rspec
end

describe Exceptional do

  it 'shows the incorrect exception line' do
    m = double("m")
    e = Exceptional.new
    allow(m).to receive(:foo).and_raise(ArgumentError.new)
    e.nested_raiser(m)
  end
  it 'shows the correct exception line' do
    m = double("m")
    e = Exceptional.new
    allow(m).to receive(:foo) { raise ArgumentError.new }
    e.nested_raiser(m)
  end
end
```

### Expected behavior

I expect that in both cases the exception points to line 14, where it was raised.

This works correctly when passing a block to `receive` which creates a new error each time.

### Actual behavior

In the first case, the exception is shown as raised on the line where the rescued exception was raised - not where the fatal exception was raised.

This is quite confusing when debugging a failing test.

```
$ rspec spec/tester_spec.rb 
Rescued exception
FRescued exception
F

Failures:

  1) Exceptional shows the incorrect exception line
     Failure/Error: m.foo
     
     ArgumentError:
       ArgumentError
     # ./lib/tester.rb:5:in `raiser'
     # ./lib/tester.rb:12:in `nested_raiser'
     # ./spec/tester_spec.rb:13:in `block (2 levels) in <top (required)>'

  2) Exceptional shows the correct exception line
     Failure/Error: allow(m).to receive(:foo) { raise ArgumentError.new }
     
     ArgumentError:
       ArgumentError
     # ./spec/tester_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./lib/tester.rb:14:in `nested_raiser'
     # ./spec/tester_spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 0.02153 seconds (files took 0.24175 seconds to load)
2 examples, 2 failures
```

**Comment by pirj** [comment]
There's clearly some difference. Have you managed to research it deeper?
By the way, it seems that if you do it this way, backtraces become identical:
```diff
- allow(m).to receive(:foo).and_raise(ArgumentError.new)
+ allow(m).to receive(:foo).and_raise(ArgumentError)
```

However, from my point of view, this is an inconsistency between those two ways of setting the expectation.

Can `raise_already_invoked_error_if_necessary` that is used by `and_raise` be involved?

**Comment by JonRowe** [comment]
This is raising a specific error, which is reused each time, e.g. it is the same exception, and the backtrace is probably persisting due to Ruby.

```
allow(m).to receive(:foo).and_raise(ArgumentError.new)
```

This is a new error each time the block is invoked.

```
allow(m).to receive(:foo) { raise ArgumentError.new }
```

I believe @pirj's suggestion, will do what you want to, because the error is not created until it is raised.

```
allow(m).to receive(:foo).and_raise(ArgumentError)
```

**Comment by tylerholien** [comment]
@JonRowe It is correct that Ruby is causing this (when raising the same exception instance twice, it only gets the backtrace set the first time), but it'd be nice to see this mentioned in the docs with a suggestion for how to address the problem with your suggestion of `allow(m).to receive(:foo) { raise ArgumentError.new }`. I can also imagine `#and_raise` accepting a block argument that returns the exception instance (I don't think this is supported yet).

**Comment by JonRowe** [comment]
I'll happily welcome a PR added to the docs that you should either instantiate exceptions in a block or use the class name only to prevent reuse.

**Comment by pirj** [comment]
As far as I can see, `and_raise` does accept several arguments that it blindly delegates to `raise`.
`raise`, in turn, is passing the rest of the arguments to its first argument's `.new` method.

So probably a proper call should become `.and_raise(ArgumentError, 'message', backtrace_if_you_like)` instead of passing an instance of the exception.

@JonRowe do you think it's a good idea to deprecate passing exception instances in `and_raise` in 3.99?

**Comment by tylerholien** [comment]
@pirj The trouble I've run into is with exceptions that take more than one required constructor argument and/or their constructor argument expects something other than a message (an [example from Rails](https://github.com/rails/rails/blob/5-2-stable/activemodel/lib/active_model/errors.rb#L511)).

```ruby
# for exceptions like that one would still need to raise in a block as suggested earlier by @JonRowe 
allow(m).to receive(:foo) { raise UnknownAttributeError.new(record, attribute) }

# alternatively could add support for passing a block would need to be added to `and_raise`
allow(m).to receive(:foo).and_raise { UnknownAttributeError.new(record, attribute) }
```

**Comment by JonRowe** [comment]
No because as the docs point out, if you have an (admittedly non standard) exception taking multiple args, you need to have an instance. The docs could point out the issue with the backtrace however.
