### ISSUE TITLE
performance regression in 3.9.1

### ISSUE THREAD

**Issue by beanieboi** [rspec/rspec-mocks#1333]
Hi everybody,

first of all i want to thank you for your work on rspec.

### Subject of the issue
We recently upgraded from 3.7 to 3.9. After the upgrade we saw a huge performance regression in a part of our test suite. Not all specs are affected. I was able to trace it down to this commit https://github.com/rspec/rspec-mocks/commit/407a8aa70cb10ad2c79cc2b47576d2b1f5aa7b5e. Everything before this commit is fine, everything after is slow.

To give you some examples, here is the top 10 of the worst slow downs we see. (sorry i can't provide file names here).
What you see here is the time i takes to run 1 single spec file. It shows the duration in seconds before the change and after the change. it highlights the slowdown (diff) in seconds as well.

```
before -> after
spec/file1_spec.rb: 20.7 -> 560.2 (diff: 539)
spec/file2_spec.rb: 38.3 -> 540.0 (diff: 502)
spec/file3_spec.rb: 5.9 -> 167.2 (diff: 161)
spec/file4_spec.rb: 3.1 -> 99.9 (diff: 97)
spec/file5_spec.rb: 3.0 -> 84.1 (diff: 81)
spec/file6_spec.rb: 114.9 -> 190.1 (diff: 75)
spec/file7_spec.rb: 3.1 -> 68.1 (diff: 65)
spec/file8_spec.rb: 40.6 -> 89.5 (diff: 49)
spec/file9_spec.rb: 60.9 -> 97.9 (diff: 37)
spec/file10_spec.rb: 1.3 -> 38.1 (diff: 37)
```

i was able to get some traces with rbspy and will highlight the biggest differences here:

before:
```
Time since start: 12s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
  2.41    11.20  block in ancestor_is_an_observer? - /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-mocks-3.7.0/lib/rspec/mocks/any_instance/recorder.rb
  0.75    15.10  parse - /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/2.6.0/time.rb
  0.66    11.45  super_class_observing? - /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-mocks-3.7.0/lib/rspec/mocks/any_instance/recorder.rb
```
after
```
Time since start: 32s. Press Ctrl+C to stop.
Summary of profiling data so far:
% self  % total  name
  1.30    66.60  block in ancestor_is_an_observer? - /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/any_instance/recorder.rb
  0.37    66.57  super_class_observing? - /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/any_instance/recorder.rb
  0.28    66.60  already_observing? - /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/any_instance/recorder.rb
```

Ruby spends _way_ more time in those particular methods.

### Your environment
* Ruby version: 2.6
* rspec-mocks version: 3.9.1

### Steps to reproduce
as of now, i'm not sure what makes those specs special, why they are affected that much, we have some spec files that are not affected by this at all.

### Expected behavior
the time it takes to execute our specs should stay the same in rspec-mocks 3.9.1

### Actual behavior
there is a _big_ slowdown when running our specs on rspec-mocks 3.9.1

I'm happy to help with this, but at this point i need your input to provide more data on this. Let me know what kind of data i can provide to track this down.

Thanks for your help
Cheers Ben

**Comment by JonRowe** [comment]
If the bisect is correct, and the commit `407a8aa70cb10ad2c79cc2b47576d2b1f5aa7b5e` is the source of the increase in spec time then turning off verifying partial doubles should improve your spec times:

```
RSpec.configure do |config|
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = false
  end
end
```

Its to be expected that verifying doubles increases the spec run time given its doing more work, in particular if you've got lots of instances with an `any_instance_of` expectations, can you tell me / show me the sorts of expectations you using? Especially in the worst affected files. Is this a Rails app?

**Comment by pirj** [comment]
@beanieboi Can you please help us understand if there's something actionable here?

`verify_partial_doubles` and `any_instance_of` come with a price. But I would not expect it to slow down your tests 10x, so probably there's something that can be improved. Can you confirm that turning off `verify_partial_doubles` brings the previous spec execution speed back?

**Comment by JonRowe** [comment]
Closing as stale as no actionable info has come up, happy to reopen if you can provide something specific.

**Comment by beanieboi** [comment]
Hey, sorry for the delay on this.

we recently upgraded from Ruby 2.6.6 to 2.7.2 and the problem went away. 3.9.0 and 3.9.1 are now equally fast. Maybe it's worth a call out to this issue and encourage people to upgrade to a newer Ruby version. I can still reproduce it on 2.6.6 if you are interested.

But either way, I'm happy to leave this closed.
