### ISSUE TITLE
Shared context seems to be leaking mocked info

### ISSUE THREAD

**Issue by luke-hill** [rspec/rspec-mocks#1334]
### Subject of the issue
RSpec mocks leaking cross "shared context"

### Your environment
* Ruby version: 2.4
* rspec-mocks version: 3.9

### Steps to reproduce
See github SHA for failing rspec test here: https://github.com/site-prism/site_prism/runs/872888494

### Expected behavior
I'm not sure why this context is leaking. Inside my context I stub and require a certain input/output. These should be completely isolated right? Maybe I'm doing something wrong?

### Actual behavior
The Xpath shared context is leaking info to the css shared context

**Comment by JonRowe** [comment]
Can you link directly to the file and part of the build you'd like us to look at? We don't have time to dig through your codebase and build output.

**Comment by luke-hill** [comment]
Sorry mybad.

Commit SHA where I add references inside the shared contexts - https://github.com/site-prism/site_prism/pull/68/commits/874cf517ed7e57d9f415cae1e3c2c3ede9b95266#diff-420eec461dcee2d4bebde4204d2be9c0R88

Sample failing build, tests that are problematic start here: https://travis-ci.com/github/site-prism/site_prism/jobs/361220368#L882

It says the XPath page expected a css element and vice versa. Maybe it's something wrong with my setup, I'm not sure. I actually only wanted to write a test for a warning being thrown to increase code coverage.

**Comment by pirj** [comment]
I may get it wrong, but:
```ruby
context 'with a Page defined using CSS locators' do
  let(:page) { CSSPage.new }
  it ...
    allow(page).to receive(:element).with(:no_way_should_this_be_written, '//a[@class="c"]//b[@class="d"]').and_call_original
```

it seems to me you're passing an XPath selector to a CSSPage and the other way around.

**Comment by luke-hill** [comment]
I've switched those round and I get different errors now. So I think..... maybe you are right @pirj 

Given this feels like it's something that can't be globally broken. I'll close this Issue for now and investigate further. Sorry for wasting everyones time.

I'm not sure what's broken, but fairly sure it's not rspec.

**Comment by benoittgt** [comment]
Feel free to reopen @luke-hill if you see an issue in RSpec itself.

**Comment by pirj** [comment]
No worries, @luke-hill.
Sometimes we have bugs, and if it's not so obvious, please feel free to open a ticket.
You're always welcome.
