### ISSUE TITLE
Arbitrary mocks behave in an odd, undocumented, bevior

### ISSUE THREAD

**Issue by saveriomiroddi** [rspec/rspec-mocks#1337]
### Subject of the issue

Arbitrary handling has an odd behavior. It's not clear if this is intended or not; in the first case, it should be documented, in the latter, it's a bug.

### Your environment
* Ruby version: 2.6.2
* rspec-mocks version: 3.9.1

### Steps to reproduce

Example 1:

```
expect(my_double).to receive(:mymethod) do |param|
  expect(true).to eql(true) # phony just for illustration
  expect(false).to eql(true)
end
```
Example 2:

```
expect(my_double).to receive(:mymethod) do |param|
  raise "FAIL!"
end
```

### Expected behavior

`Example 1` should fail, or, if this is intended behavior, it should be documented that only one `expect` is allowed inside the block.

`Example 2` should fail as well. Again, if this is intended, it should be documented that only `expect` statements will cause the outer expectation to fail.

### Actual behavior

`Example 1` will pass - only the first `expect`ation is executed.
`Example 2` will pass as well. It's a bit unclear why.

**Comment by pirj** [comment]
Can you please provide a reproduction example? I can't reproduce it with this spec:
```ruby
RSpec.describe do
  let(:receiver) { double }

  it do
    expect(receiver).to receive(:foo) do
      expect(5).to eq(5)
      expect(4).to eq(4)
      expect(2).to eq(100)
    end
    receiver.foo
  end
end
```
```
  is expected to eq 100 (FAILED - 1)

Failures:

  1) is expected to eq 100
     Failure/Error: expect(2).to eq(100)

       expected: 100
            got: 2

       (compared using ==)
 ```


For the second case:
```ruby
RSpec.describe do
  let(:receiver) { double }

  it do
    expect(receiver).to receive(:foo) do
      expect(5).to eq(5)
      expect(4).to eq(4)
      raise 'foo'
    end
    receiver.foo
  end
end
```

```
  is expected to eq 4 (FAILED - 1)

Failures:

  1) is expected to eq 4
     Failure/Error: raise 'foo'

     RuntimeError:
       foo
 ```
or
```
  is expected to receive foo(*(any args)) 1 time (FAILED - 1)

Failures:

  1) is expected to receive foo(*(any args)) 1 time
     Failure/Error: raise 'foo'

     RuntimeError:
       foo
 ```
depending on if there are expectations in the block or not.

**Comment by saveriomiroddi** [comment]
Thanks for the reply. I'll follow up in a couple of days. I'm definitely experiencing, and now I suspect there is some odd interaction happening, which will take a bit to dissect!

**Comment by JonRowe** [comment]
In the first example the expectation should fail the test when `my_double.mymethod` is called, in the second example it should error and thus fail the test, again when `my_double.mymethod` is called.

In either case if you `rescue Exception` around the code calling `my_double.mymethod` RSpec would never see the result of the block, is it possible thats whats happening here?

**Comment by pirj** [comment]
Have you had a chance to look at it @saveriomiroddi ?

**Comment by saveriomiroddi** [comment]
> Have you had a chance to look at it @saveriomiroddi ?

Hello @pirj, thanks for giving attention. Since this will be a time consuming issue, it's taking me some time. I'll allocating one or two hours tomorrow morning to trying to find out a minimal test case, then I'll get you back, so, to summarize, I'm reporting in less than 24 hours :smile:

**Comment by pirj** [comment]
> a time consuming issue

No worries, it's typical to be a time consuming issue when it comes to `rspec-mocks` :D
Just making sure this doesn't slip through the cracks.

**Comment by saveriomiroddi** [comment]
So, phew!

I dug into the issue, and the conclusion is that there is no issue (my example was an improper oversimplification).

The reason for this has been my incomplete reading of the manpage. The [arbitrary handling section](https://github.com/rspec/rspec-mocks#arbitrary-handling) uses a `expect`, while I've originally used `expect_any_instance_of`, like:

```ruby
expect_any_instance_of(klazz).to receive(:msg) do |arg|
  expect(arg.size).to eq 7
end
```

This misses the fact that the first argument is the instance itself; the (a) broken inner expectation raised an error, which was rescued by the controller, which in turn, caused `raise` not to fail.

This behavior (first parameter is the instance) is documented [here](https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance#block-implementation-is-passed-the-receiver-as-first-arg), so I wonder if adding this behavior (additional) example to the arbitrary handling help section would be worth - but on the other hand, it would constitute duplication.

To conclude, not an issue :grin:, thanks for the response - I appreciate responsive project management :+1:

**Comment by pirj** [comment]
Thanks for getting back!

Does it make sense to change the example in a way that emphasizes that the first block argument is the object itself? `value` may infer confusion even though the docstring sounds non-ambiguously ("Block implementation is passed the receiver as first arg"):
```diff
-    allow_any_instance_of(String).to receive(:slice) do |value, start, length|
-      value[start, length]
+    allow_any_instance_of(String).to receive(:slice) do |string, start, length|
+      string[start, length]
    end
```

**Comment by saveriomiroddi** [comment]
> Thanks for getting back!
> 
> Does it make sense to change the example in a way that emphasizes that the first block argument is the object itself? `value` may infer confusion even though the docstring sounds non-ambiguously ("Block implementation is passed the receiver as first arg"):
> 
> ```diff
> -    allow_any_instance_of(String).to receive(:slice) do |value, start, length|
> -      value[start, length]
> +    allow_any_instance_of(String).to receive(:slice) do |string, start, length|
> +      string[start, length]
>     end
> ```
> 
> or maybe `receiver` instead of `value`?

In my opinion, receiver is very fitting.

I personally suggest `instance`. The rationale is that it's generic (therefore practical to use for copy/paste), but at the same time, its proximity with `allow_any_instance_of` makes it unmistakeable which is the underlying concept.

But `receiver` also has the same characteristics, with the difference being only that it's a bit more technical, so I think it's a good choice as well.

**Comment by pirj** [comment]
Agree, I would personally have had least doubts with `instance` in that example. Would you like to tackle changing this doc?

**Comment by saveriomiroddi** [comment]
> Agree, I would personally have had least doubts with `instance` in that example. Would you like to tackle changing this doc?

Sure! Will take care between today and tomorrow. :+1:

**Comment by saveriomiroddi** [comment]
> Agree, I would personally have had least doubts with `instance` in that example. Would you like to tackle changing this doc?

Created [PR with the change](https://github.com/rspec/rspec-mocks/pull/1340).
