### ISSUE TITLE
TypeError: can't define singleton

### ISSUE THREAD

**Issue by zhisme** [rspec/rspec-mocks#1356]
### Subject of the issue
Try to mock class not by an object, but by a symbol and get very uninformative error message.
Maybe we can improve such behaviour and leave for programmer better error message, like
> Tried to mock symbol, but object expected.

Of course we can go to [stackoverflow](https://stackoverflow.com/questions/47080835/typeerror-cant-define-singleton-rspec) with some googling, but on my opinion this error message very unfriendly and error-phone.

### Your environment
* Ruby version: 2.7.0
* rspec-mocks version: 2.14.6

### Steps to reproduce
```ruby
allow(:subject).to receive(:foo).and_return(:baz)
```

### Expected behavior
Some error raised

```ruby
raise ArgumentError, 'Passed not an object'
```

### Actual behavior
```
Failure/Error: allow(:action).to receive(:foo).and_return(:baz)
     TypeError:
       can't define singleton
```

**Comment by pirj** [comment]
Well noticed. I've been making this mistake a couple of times as well.
A pull request is welcome.

**Comment by zhisme** [comment]
great, I will take care of implementation then
