### ISSUE TITLE
expecting keyword args for a method that receives a hash passes tests but fails in reality for Ruby 3

### ISSUE THREAD

**Issue by davetron5000** [rspec/rspec-mocks#1417]
### Subject of the issue

Given:

```ruby
expect(object).to have_received(:doit).with(a: 10, b: 20)
```

And actual code:

```ruby
hash  = { a: 10, b: 20 }
doit(hash)
```

This code fails at runtime in Ruby 3, but the expectation passes.  See runnable example below.

### Your environment
* Ruby version:
   ```
   # ruby --version
   ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
   ``` 
* rspec-mocks version:
   ```
   # grep rspec-mocks Gemfile.lock 
         rspec-mocks (~> 3.10.0)
       rspec-mocks (3.10.1)
         rspec-mocks (~> 3.10)
   ````

### Steps to reproduce

Check out this gist: https://gist.github.com/davetron5000/62ea68c47bdbf3852f3a6c5f6dc39f5c

```
curl https://gist.githubusercontent.com/davetron5000/62ea68c47bdbf3852f3a6c5f6dc39f5c/raw/03daeb3513a7250f2d2aed43bd7963ba0ba04260/rspec_kwargs_spec.rb > rspec_kwargs_spec.rb
```

Then:

```
rspec rspec_kwargs_spec.rb
```

You'll see the tests pass.

Then:

```
ruby rspec_kwargs_spec.rb run
# or
bundle exec ruby rspec_kwargs_spec.rb run
```

You'll see that the invocation of `UsesHash` fails due to an `ArgumentError`, despite our test passing.

### Expected behavior

I would expect the test to fail since we are expecting keyword args but were given a hash.

### Actual behavior

The expectation passes even though the code fails.

**Comment by JonRowe** [comment]
We merged support for automatically verifying keywords instead of hashes in #1394 but it as yet unreleased, can you try `main` please.
