### ISSUE TITLE
How to stub yaml and write rspec

### ISSUE THREAD

**Issue by krvicky31** [rspec/rspec-mocks#1427]
### How to write rspec with stubing

 def rules_to_run
        @checks_to_run = YAML.safe_load(File.read('lib/property.yaml'))
      end
-->

### Your environment
* Ruby version: 2.7.3
* rspec-mocks version:

### Actual behavior
 Not able to write as stubing is not doing anything

**Comment by pirj** [comment]
https://rspec.info/help/ list resources where you can seek help. We strive to keep the issue tracker for bugs and enhancements.
