### ISSUE TITLE
New release timeline

### ISSUE THREAD

**Issue by jcoleman** [rspec/rspec-mocks#1437]
### Subject of the issue
I'd like to inquire about a timeline for a new release, as we'd be very interested in being able to take advantage of 7a5e2c1aaf46800c7a81f8bb908fd94907dd4ca1.

**Comment by pirj** [comment]
It will be released in 3.11, but no promises on when exactly.
I understand the inconvenience of pointing to a `ref` in your `Gemfile`, and sorry for that.
