### ISSUE TITLE
Using `receive(:new).and_wrap_original` on a base class breaks instantiation of anything that inherits from that base class.

### ISSUE THREAD

**Issue by jejacks0n** [rspec/rspec-mocks#1451]
### Subject of the issue

It appears that `receive(:new).and_wrap_original` on a base class breaks instantiation of anything that inherits from that base class.

### Your environment

* Ruby version: 2.7.5
* rspec-mocks version: 3.10.2

### Steps to reproduce

Here's a spec that exhibits the behavior pretty clearly. It specifies how one might expect Ruby to behave when calling `Dog.new`, and fails because the instance returned is not a Dog instance.

```ruby
class Animal
  def initialize
    puts 'initializing animal'
  end
end

class Dog < Animal
  def initialize
    puts 'initializing dog'
    super
  end
end

RSpec.describe ":new with and_wrap_original" do
  it "appears to ignore subclasses" do
    allow(Animal).to receive(:new).and_wrap_original do |method|
      puts 'stubbed logic'

      method.call # this will return our Animal instance
    end

    # This fails because an Animal instance is returned, not a Dog instance.
    # Dog#initialize is also never called.
    expect(Dog.new).to be_a(Dog)
  end
end
```

### Expected behavior

One would expect `Dog.new` to return a `Dog` instance under all circumstances.

### Actual behavior

Calling `Dog.new` returns an `Animal` instance and `Dog#initialize` is never called.

**Comment by pirj** [comment]
It's not specifically `and_wrap_original`, `and_return` behaves in the same way.

**Comment by pirj** [comment]
My quick guess is that we use base class's singleton class to override the stubbed method.

```ruby
class A
end

class B < A
end

A.define_singleton_method(:new) { 'A string' }

B.new # => "A string"
```

**Comment by jejacks0n** [comment]
Ah, that would make sense. Is this the expected behavior, and if so, is it clarified in documentation or anything?

I think this might surface as a more common pattern now that `*_any_instance_of` logic has been documented as unmaintained. At least, that's how I ended up coming across it.

I've resolved it in my situation by introducing an anonymous "nothing" subclass that simply inherits from the base class. We then never instantiate the base class directly, but it's all a bit of a gotcha, for sure.

```
class Animal
  def initialize
    puts 'initializing animal'
  end
end

class AnonymousAnimal < Animal
end
```

Now because we're never instantiating our base class directly, we can `allow(AnonymousAnimal).to receive(:new).and_wrap_original { }` without causing issues on other instances that inherit from `Animal`.

I wonder what others have learned in this space. Thanks for your comments and attention on it @pirj.

**Comment by pirj** [comment]
> Is this the expected behavior

I wouldn't say so. Wondering if there's a straightforward way to work this around. Do you have an idea?

> now that `*_any_instance_of` logic has been documented as unmaintained

It's not unmaintained to my best recollection, but [is only recommended for use with legacy code](https://relishapp.com/rspec/rspec-mocks/v/3-9/docs/working-with-legacy-code/any-instance).

> introducing an anonymous "nothing" subclass

Very inventive workaround.

Out of curiosity, can you share a bit more context on the purpose of wrapping the initializer of the base class?
I don't mean in any way that your testing approach is incorrect, just wondering how widespread this could be.
A pretty common example that also suffer from the same problem:
```ruby
regular_user = instance_double('User')
allow(User).to receive(:new).and_return(regular_user)
# ...
admin = AdminUser.new # :boom:, regular user is returned instead
```

**Comment by jejacks0n** [comment]
I'd say I'm on an edge use case, so likely isn't an example worth sharing?

The places I saw it coming up are exactly how you described it. With models I'd see it being an issue with STI, as well, I've used presenters in generating a response from a controller where one presenter inherited from a useable base class -- again, often an `Author < User` kind of scenario.

I doubt it's a _BIG_ use case, but I was sure surprised by the behavior after I understood it. I'd say that there might be some dragons hidden under mocking `:new`, so documenting the potential risks there might be useful?

I'll think on it, but the best idea I can come up with off hand, is a warning when appropriate.

> You're attempting to mock `:new` on a class with descendants, and this will cause any new instance of those descendants to be replaced by an instance of the class you're mocking.

Let me know how you'd like for me to help.

**Comment by pirj** [comment]
I'd suggest `prepend Module.new` as an alternative:
```ruby
class A
  def self.a
    'a'
  end
end
class B < A
  def self.a
    'b'
  end
end
A.singleton_class.prepend Module.new { define_method(:a) { 'A string' } }
A.singleton_class.prepend Module.new { define_method(:new) { 'A new' } }

puts A.a # A string
puts B.a # b
puts A.new # A new
puts B.new # A new
```

However:
1. It doesn't work with `new`
2. To my best knowledge, it's impossible to unstab just as easy as `delete_method` does now
3. `prepend` didn't exist in earier Rubies that we still support in RSpec 3, so this would have to wait anyway


Speaking of the warning. Sounds good in general.
Wondering how it would be possible to mute the warning for I don't care about subclasses/I don't have control over this code cases?
It will take a walk down the ObjectSpace to find out if the class has descendents. Wondering if this comes with a performance impact. Probably only for codebases that stub `new` often.

**Comment by JonRowe** [comment]
I'm pretty sure this is a deliberate behaviour, consider this scenario instead:

```
class Animal
  def self.expensive_sound_generator
    # expensive wav generator routine
  end
end

class Dog < Animal
  def self.expensive_sound_generator
    # ...
    super
  end
end

RSpec.describe do
  it "works with subclasses" do
    allow(Animal).to receive(:expensive_sound_generator).and_wrap_original do |method|
      "soundfile.wav"
    end

    expect(Dog.expensive_sound_generator).to eq "soundfile.wav"
  end
end
```

That would be the correct behaviour, and is much more obvious as to what is going on, but is the same as your spec just with a different method name.

As you're stubbing `new` here which is called by `super` on `Dog`, you're skipping the normal allocation process that would return a Dog instance, you could possibly use `method` to find the class called and have a case statement, but I'm a bit fuzzy on what the owner class is at this point.

I'm going to close this as "working as expected" but I'm open to a PR improving the documentation around this, I'm not so sure a warning is a good idea because it would affect legitimate usage of this behaviour.

**Comment by pirj** [comment]
Just a note that it works differently with non-`new` class methods:
```ruby
class Animal
  def self.expensive_sound_generator
    # expensive wav generator routine
  end
end

class Dog < Animal
  def self.expensive_sound_generator
    # ...
    super
    "DOG.wav" # Override!
  end
end

RSpec.describe do
  it "works with subclasses" do
    allow(Animal).to receive(:expensive_sound_generator).and_return("soundfile.wav")

    expect(Dog.expensive_sound_generator).to eq "soundfile.wav"
  end
end
```
```
     Failure/Error: expect(Dog.expensive_sound_generator).to eq "soundfile.wav"

       expected: "soundfile.wav"
            got: "DOG.wav"
```

**Comment by JonRowe** [comment]
@pirj `super` returns "soundfile.wav"`its the `super` call thats important, the default implementation for `Dog.new` is (paraphrased)`def self.new; super; end` which then calls `Animal.new` and that returns the original implementation of calling `Animal.new`

**Comment by jejacks0n** [comment]
Yeah, that's just all I could come up with off hand. I don't love my suggestion of the warning message, because it surfaces its own complexity that would be worth avoiding.

The best solution would be one that makes it a non-concern.

I played around a bit with overriding `new` on a class. I know all of these things are anti-patterns in daily life, but aren't really for a mocking library. Haha, I had to kind of get out of "rules" mode to think on some of this.

```ruby
class A
  def initialize
    puts "A#initialize"
  end
end

class B < A
  def initialize
    puts "B#initialize"
    super
  end
end

RSpec.describe "one potential approach" do
  it "might handle :new by setting an instance variable and using that on instantiation" do
    A.instance_variable_set(:@__mocked_new, true)
    A.define_singleton_method(:new) do |*args|
      return super(*args) unless @__mocked_new

      return 'MOCKED'
    end

    expect(A.new).to eq('MOCKED')
    expect(B.new).to be_a(B)
  end
end
```

What I came to was that we want our mock to only ever be executed when the source of instantiation is "the mocked class". The way I wedge that in the example is to set an instance variable on the class.

I'm guessing a mocking library has better implementation tooling for at kind of concept -- like a mocking space or something, where things that are mocked might be tracked? I'd utilize something like that to keep track of the objects that I was mocking instantiation on, because it does seem to fall slightly outside the standard? That's for someone with more knowledge of the library to think on though. It also made me think on how the relationship between `.new` and `#initialize` makes `.new` a somewhat unique concept, but I wonder if there are other examples of this kind of relationship? 🤔 

Ultimately this simple example does exhibit the expected behavior though, where we only mock instantiation on `A`, and not on `B`. `B` can even successfully call `super` within `#initialize` without being an issue.

Is all of this just recreating the complexity that arose within `*_any_instance_of` though? 😬

**Comment by jejacks0n** [comment]
I wanted to take a moment to say that I appreciate your time @JonRowe. It was nice to have a some dialog and to not feel dismissed or that I was "doing it wrong," which could be entirely possible.

If you care about the background, this came up on a gem that we've written at GitLab -- https://gitlab.com/gitlab-org/ruby/gems/gitlab-experiment. We use it to run experiments, and the design is that experiment behavior can be customized by inheriting a configurable base class, whilst simultaneously handling "anonymous" experiments (ones for which no class can be resolved).

It's in using these anonymous experiments, which instantiate the base class, that we see the problem arise. Like I said, I can't think it's a huge use case or design pattern, and we'll resolve it internally by creating and using an internal `AnonymousExperiment` class instead of the base class, but I think several engineers came up against the issue without realizing that's what they were experiencing.

**Comment by jejacks0n** [comment]
I didn't see your comments and that the issue had been closed @JonRowe. Anyway, I'd like to keep discussing it because your example is incorrect. Could you please confirm?

Here's what I see:

```ruby
class A
  def self.class_method
    "A"
  end
end

class B < A
  def self.class_method
    "#{super}+B"
  end
end

RSpec.describe "behavior" do
  context "when mocking general class methods" do
    it "does not impact inheritance" do
      expect(A.class_method).to eq "A"
      expect(B.class_method).to eq "A+B"

      allow(A).to receive(:class_method).and_wrap_original { |method| "MOCKED+#{method.call}" }

      expect(A.class_method).to eq "MOCKED+A"
      expect(B.class_method).to eq "MOCKED+A+B"
    end
  end

  context "when mocking the :new class method" do
    it "breaks inheritance" do
      expect(A.new).to be_a A
      expect(B.new).to be_a B

      allow(A).to receive(:new).and_wrap_original { |method| method.call }

      expect(A.new).to be_a A
      expect(B.new).to be_a B # this is the issue, it's an instance of A?
    end
  end
end
```

If you'd like to discuss further I'd say the underlying issue is in how `.new` and `#initialize` interact, which it seems like needs to be accounted for. There's like a zero percent chance that calling `B.new` should ever _NOT_ return an instance of `B`.

**Comment by jejacks0n** [comment]
I kinda understand what you're saying @JonRowe, but the way it's implemented, there's not a way to handle what anyone would likely want on `:new`. That's my point.

At the time that we can provide the block to wrap, we don't have enough information to do what any sensible person would want to do, and I'm trying to see if that's an oversight or if it should be added to the implementation of mocking for `:new`.

**Comment by jejacks0n** [comment]
Alright, I'll try to distill this down to what seems incorrect. Let's start with a fairly basic inheritance structure like the following:

```ruby
class Base < Object # intentionally redundant inheritance of `Object`
  def self.foo
    "#{self.name}.foo" # intentionally redundant use of `self` to highlight the issue
  end
end

class A < Base
end

class B < A
end
```

Really simple example of how `A` and `B` don't implement a given class method and so the implementation in `Base` is used.

```ruby
A.foo # => "A.foo"
B.foo # => "B.foo"

Base.method(:foo) # => #<Method: Base.foo() (irb):2>
A.method(:foo) # => #<Method: A.foo() (irb):2>
B.method(:foo) # => #<Method: B.foo() (irb):2>
```

Looking at where those methods are defined, they're all the same -- irb line 2, which is where they were defined when I pasted it into the console. More importantly, we see that a simplified but reasonable model, is to imagine that calling `A.foo` and `B.foo` is handled by traversing the inheritance hierarchy until `Base.foo` is found, where `self` will reference the instance that we're traversing from. This is important for the rest of the discussion.

What I'm trying to surface here is that `self` is critically important for both our `.new` and `.foo` methods to be properly handled on the `A` and `B` classes. Right?

Regardless of what class we call `.foo` from, `self` should reference _that_ class. If we call `B.foo`, we obviously expect `self` inside of any calls up the inheritance hierarchy to be `B`, and here is where I believe the issue is. So let's highlight that in an example:

```ruby
RSpec.describe "mocking with inheritance concerns" do
  it "shows that mocking A.foo breaks the use of `self` inside the Base.foo implementation" do
    allow(A).to receive(:foo).and_wrap_original { |method| "#{method.call}(mocked)" }

    expect(Base.foo).to eq 'Base.foo'
    expect(A.foo).to eq 'A.foo(mocked)'
    expect(B.foo).to eq 'B.foo(mocked)' # this fails, but likely shouldn't
  end
end
```

Focus in on that last line, and then consider that there seems to be no way to work around this. The `method` variable, which is all we have to work with, is bound to `A` and so any reference to `self` all the way up the inheritance hierarchy for this method will _always_ be `A` regardless of what `self` refers to inside of any other class method inside of `B`. This starts to get really strange, right? When you think on it that way, you might see the number of issues this could cause.

I've had a couple hours to dig into the rspec-mocks library and have worked out what the issue is, and it can be described by this snippet, where we don't see the prob

```ruby
RSpec.describe "mocking with inheritance concerns" do
  it "could be done better" do
    original_method = A.method(:foo).unbind # get the method and unbind it
    A.define_singleton_method(:foo) do # redefine the method with our own
      method = original_method.bind(self) # don't bind to A (or object)! instead, bind to self.
      "#{method.call}(mocked)" # `method` is now bound to the right object
    end

    expect(Base.foo).to eq 'Base.foo'
    expect(A.foo).to eq 'A.foo(mocked)'
    expect(B.foo).to eq 'B.foo(mocked)'
  end
end
```

And when we get into it, `Object.new` is exactly like our `Base.foo` example, but in C. In Ruby we can imagine that as being implemented as:

```ruby
def self.new(*args, &block)
  self.allocate.tap { |i| i.send(:initialize, *args, &block) } # again, a redundant use of `self`
end
```

We can then see that if `self` is broken anywhere along our inheritance hierarchy, as it is when we take a method and bind it to the wrong object, we'll get strange things, like instances of `A` when we call `B.new`.

**Comment by jejacks0n** [comment]
Ultimately, what happens on https://github.com/rspec/rspec-support/blob/main/lib/rspec/support.rb#L52 (and the other definition) is part of what I think we're seeing. It binds the method to the object in that moment, and stores that. `B` will then inadvertently call that method that's bound to `A`, and where `self` will incorrectly return `A` instead of `B`.

I can see through comments in the code that this is a thing that's come up, I just don't think it's "right" yet.
