### ISSUE TITLE
Rails 7.1 breaks receive().with

### ISSUE THREAD

**Issue by palkan** [rspec/rspec-mocks#1530]
### Your environment
* Ruby version: 3.2
* rspec-mocks version: 3.12.2
* Rails version: [main](https://github.com/rails/rails/commit/20d87500a4568b175f1e06796572154a5a8d283d).

### Steps to reproduce

In a Rails application (i.e., with Rails loaded), define a method expectation:

```ruby
mock = instance_double("Hash")
allow(mock).to receive(:key?).with(:x) { 1 }

expect(mock.key?(:x)).to eq 1
```

### Expected behavior

Pass.

### Actual behavior

```
ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ../rails/activesupport/lib/active_support/core_ext/object/with.rb:24:in `with'
```

### What happened?

Rails monkey-patched `Object#with` https://github.com/rails/rails/pull/46681 /cc @byroot 

RSpec `receive` matcher defines chain methods only for undefined methods: https://github.com/rspec/rspec-mocks/blob/4a1032bf93fe8b47c9e3416413e2b05d604d109f/lib/rspec/mocks/matchers/receive.rb#L58-L59

Since `#with` is defined on `Object`, the `with` _modifier_ is no longer available.

**Comment by nobu** [comment]
Why does `MessageExpectation` need to b e a subclass of `Object`, not `BasicObject`?

**Comment by byroot** [comment]
Even then, why would it not redefine existing methods? I'll git blame to see if I can find the reason for this.

**Comment by byroot** [comment]
Ah, I think the intent is to not redefine methods directly defined in `Receive`, since we're copying all the matchers. `method_defined?(name, false)` would fix it I think.

**Comment by byroot** [comment]
I think I have a fix for it, but GitHub seems to be having issues, I get an error message when trying to create the PR....

https://github.com/rspec/rspec-mocks/compare/rspec:main...casperisfine:receiver-with?expand=1

**Comment by pirj** [comment]
@byroot I’ve opened one, does it work for you?

**Comment by byroot** [comment]
Sure, thank you.
