### ISSUE TITLE
Keyword args not validated 

### ISSUE THREAD

**Issue by eaden-hnry** [rspec/rspec-mocks#1548]
With the following class, 

```ruby
class Foo
  def self.mymeth(arg1:, arg2:)
  end
end
```

The following test passes:

```
expect(Foo).to receive(:mymeth).with("hello").and_return(true)
Foo.mymeth("hello")
```

I have a couple of questions;
Given that `receive` will validate that `Foo` actually has a method called `mymeth`, it seems some validation is taking place. 

Should `with` also validate that the correct keyword arguments are passed?

If not, why should receive validate the method exists?

**Comment by pirj** [comment]
Are you certain you've turned on [partial double verifi﻿﻿cation on](http://rspec.info/features/3-12/rspec-mocks/verifying-doubles/partial-doubles/)?
```ruby
RSpec.configure do |config|
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```
