### ISSUE TITLE
doc: broken links (404) on rspec.info 

### ISSUE THREAD

**Issue by exoego** [rspec/rspec-mocks#1557]
### Subject of the issue

https://rspec.info/features/3-12/rspec-mocks/configuring-responses/
![image](https://github.com/rspec/rspec-mocks/assets/127635/308fbf0f-4b20-492b-bbab-22a63f4bf2b9)

Links in README.md appears broken (404).

### Your environment

No, it is about doc site.

### Steps to reproduce

Visit https://rspec.info/features/3-12/rspec-mocks/configuring-responses/ and click links.

### Expected behavior

Links should navigate to the proper document.

### Actual behavior

404 is shown
![image](https://github.com/rspec/rspec-mocks/assets/127635/2d556a01-c8a0-42ee-a81f-4c01e4ebb0e1)

**Comment by exoego** [comment]
I found GH repo for rspec.info and this issue appears to duplicate https://github.com/rspec/rspec.github.io/issues/188

**Comment by pirj** [comment]
You can take over if you like, @exoego. Unless you’ve started it already, @danieldiekmeier

**Comment by danieldiekmeier** [comment]
No, sorry, I haven't had time to start yet. 😰

**Comment by exoego** [comment]
I've tried to fix markdown generation in https://github.com/rspec/rspec-dev/blob/a2a50c9c855a1666194a139264b99fa735176617/Rakefile#L216 
but `bin/rake "update_docs[3-12-maintenance]"` failed and I do not know how to fix this dependency conflict with the Rake tasks.

```bash
$ bin/rake "update_docs[3-12-maintenance]"
Checking versions...                   
==================================================
# rspec-core
----------------------------------------
Switched to a new branch '3-12-maintenance'
bundle update &&          RUBYOPT='-I../rspec.github.io/lib' bundle exec yard                           --yardopts .yardopts                           --output-dir /Users/yasuhiro.tatsuno/IdeaProjects/rspec.github.io/source/documentation/3-12-maintenance/rspec-core/
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because every version of rspec-expectations depends on rspec-support = 3.13.0.pre
  and every version of rspec-core depends on rspec-support ~> 3.12.0,
  every version of rspec-expectations is incompatible with rspec-core >= 0.
So, because Gemfile depends on rspec-core >= 0
  and Gemfile depends on rspec-expectations >= 0,
  version solving has failed.
    Creating cucumber documentation requires the gherkin2makrdown tool:
    - Install go using your preferred run time (tested with asdf and golang 1.20)
    - Then run:
      ```
      go install github.com/raviqqe/gherkin2markdown@latest
      ```
      OR surpress this message by running with NO_CUCUMBER=true
```

`gherkin2markdown@latest` is already go-installed.

**Comment by pirj** [comment]
You need to go into every repo under ‘repos’ directory and ‘git checkout 3-12-stable’.

**Comment by exoego** [comment]
FYI: Opened https://github.com/rspec/rspec.github.io/pull/190
