### ISSUE TITLE
(Fixed in `3.13.0pre`) `ActiveSupport`'s `Object#with` core extension overrides `RSpec::Mocks::Matchers::Receive(Object)#with`

### ISSUE THREAD

**Issue by boardfish** [rspec/rspec-mocks#1559]
Didn't find this issue recorded as I found it, but I'd receive test failures like this:

```rb
allow(something).to receive(:a_method).with(/something/, anything)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 0)
```

This struck me as weird because `with` should receive any number of args. Using `byebug` to check the `source` and `source_location` of the `with` method, I found that it had been overridden by ActiveSupport. Updating my Gemfile to use the `main` branch as recommended on another issue fixed this:

```rb
  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'main'
  end
```

**Comment by JonRowe** [comment]
Yes there is an unreleased workaround for the clash with Rails
