### ISSUE TITLE
facing issue with rspec-mocks test cases

### ISSUE THREAD

**Issue by raoehtesham03** [rspec/rspec-mocks#1564]
### Your environment
* Ruby version: 2.7.8
* rspec-mocks version: 3.12.0
* rails version - 6.1.7.6
* rspec-rails - 6.0.0

### Expected behavior
       it { expect(Asset).to receive(:transaction).and_yield.exactly(5).times }
       This test case should pass.

### Actual behavior
    it { expect(Asset).to receive(:transaction).and_yield.exactly(5).times }
           expected: 5 times with any arguments
           received: 1 time with any arguments
           But I am facing this error again and again

**Comment by pirj** [comment]
In the same example you should at least call Asset.transaction. Your example must be incomplete if it says that it did indeed yield once.

Are you certain that `and_yield` works with countable specifiers? http://rspec.info/features/3-12/rspec-mocks/configuring-responses/yielding/
https://github.com/rspec/rspec-mocks/blob/main/spec/rspec/mocks/and_yield_spec.rb

Counts in this case are about how many times the method was called, not how many times it yielded.
