### ISSUE TITLE
`instance_double` raises "does not implement" errors on methods using `delegate_missing_to`

### ISSUE THREAD

**Issue by raldred** [rspec/rspec-mocks#1587]
### Subject of the issue
`instance_double` raises an error when mocking methods that have been delegated using `delegate_missing_to`.
`ActiveStorage::Attached::One` for example uses `delegate_missing_to` to provide access to `url` and other methods directly on the class.

### Your environment
* Ruby version: 3.3.0
* rspec-mocks version: 3.13.1

### Steps to reproduce
Mock `instance_double(ActiveStorage::Attached::One, attached?: true, url: 'https://example.com/sample.pdf')`

### Expected behavior
Should mock without error

### Actual behavior
Raises error
`ActiveStorage::Attached::One class does not implement the instance method: url`

I can't decide if it's reasonable to expect this can be supported.
Obviously falling back to using `double` works here.

**Comment by pirj** [comment]
`delegate_missing_to` is just a wrapper on top of `respond_to_missing?` and `method_missing`, right? But the `instance_double` doesn’t know what `respond_to_missing?` should return, as the delegation target is not initialized, so it would most certainly call a `respond_to?` on a `nil`, and just return `false` causing the observed behavior. Is this hypothesis correct?

I have the same doubts as you do regarding the support. If we allow any method to be stubbed if `respond_to_missing?` is defined, how do we sensibly fail for non-existent methods passed to instance_double’s initializer eg `instance_double(One, urllll: “such method never exists on the delegation target”)`.
On the other hand, it is an inconvenience.

Can you please share a more detailed usage example for more context, @raldred ?

**Comment by JonRowe** [comment]
Given that `delegate_missing_to` expects an instance to delegate to, theres no way we can know just from a class constant what the target of the delegation would be, I would recommend switching to `double` (as you mentioned) or refactoring to use something more defined.
