### ISSUE TITLE
Mocking non-existent params to method will pass

### ISSUE THREAD

**Issue by baweaver** [rspec/rspec-mocks#1591]
### Mocking non-existent params to a method will pass

When mocking a method call using `with` if you use method params which do not exist on that method it will work exactly as described in the mock rather than as the underlying method actually functions.

### Your environment

* Ruby version: 3.2.2
* rspec-mocks version: 3.13.1

### Steps to reproduce

* Mock a method with keywords which do not exist on that method
* Call that method with the same keywords
* Tests will pass

Minimal reproduction case:

```ruby
require 'rspec/autorun'

module Container
  def self.example_method(a:, b:) = a + b
end

RSpec.describe Container do
  describe ".example_method" do
    it "is called with non-existent params" do
      expect(Container).to receive(:example_method).with(b: Integer, c: Integer)

      Container.example_method(b: 1, c: 2)
    end
  end
end

# .
# 
# Finished in 0.00904 seconds (files took 0.08637 seconds to load)
# 1 example, 0 failures
```

### Expected behavior

RSpec warns that you're stubbing arguments which do not exist on the underlying method. These arguments could be derived from `Method#parameters`:

```ruby
# Example: Should be in the Set of [:a, :b]
Container.method(:example_method).parameters
# => [[:keyreq, :a], [:keyreq, :b]]

module Container
  def self.varadic(**keywords) = keywords.size
end

# Example: Should be using keyword arguments
Container.method(:varadic).parameters
 => [[:keyrest, :keywords]]
```

There are other cases to cover here potentially, but that at least gives a general idea.

### Actual behavior

RSpec will do exactly as it is asked to do, which is stub that method with those exact arguments and expect those same arguments.

I do not contest that that is a reasonable interpretation, but perhaps a subtly dangerous one that could hide bugs.

### Compromise?

On one hand I find this confusing, but on the other it's a perfectly reasonable way to handle that case even if it's probably not the intention of the writer. RSpec did exactly what they asked it to do.

If this _was_ changed it would likely be a breaking change, albeit the code under some of these cases may already be broken unbeknownst to the author. Would it be an acceptable compromise to have a configuration flag which could check whether or not stub calls with arguments represent a valid method call?

**Comment by pirj** [comment]
What if you turn [this](https://rspec.info/features/3-13/rspec-mocks/verifying-doubles/partial-doubles/) on?

**Comment by baweaver** [comment]
> What if you turn [this](https://rspec.info/features/3-13/rspec-mocks/verifying-doubles/partial-doubles/) on?

```
F

Failures:

  1) Container.example_method is called with non-existent params
     Failure/Error: expect(Container).to receive(:example_method).with(b: Integer, c: Integer)
       Missing required keyword arguments: a
     # proof_of_concept.rb:16:in `block (3 levels) in <main>'

Finished in 0.01505 seconds (files took 0.14884 seconds to load)
1 example, 1 failure

Failed examples:

rspec proof_of_concept.rb:15 # Container.example_method is called with non-existent params
```

Well I'll be. That answers that then.
