### ISSUE TITLE
With Ruby 1.9.2: can't convert Rspec::Mocks::Mock to String (Rspec::Mocks::Mock#to_str gives Rspec::Mocks::Mock)

### ISSUE THREAD

**Issue by dchelimsky** [rspec/rspec-mocks#3]
http://gist.github.com/388026

Very likely that rspec-mocks just needs to implement to_str

**Comment by mandysimon88** [comment]
@dchelimsky could you be more specific in your response? Have tried several different combinations of adding this code snipped to both spec_helper and rails_helper to no avail. Running Rails 4.0.4 && rspec 3 & rspec-mocks 3.0.4:
```
Rspec::Mocks::Mock.module_eval do
  alias to_str to_s
end
```

Always get undefined constant Rspec error...

**Comment by dchelimsky** [comment]
Just looking at your example, you're using `Rspec` instead of `RSpec`. Does changing it to `RSpec` fix it?

**Comment by mandysimon88** [comment]
No. Here is my file... But even if it did "fix" it, it would seem that this is something where I should change my code not to need this at all, since Double#to_str was intentionally removed. Opened a new issue, will post the code there.

**Comment by mandysimon88** [comment]
@dchelimsky opened issue here: https://github.com/rspec/rspec-mocks/issues/1145

**Comment by dchelimsky** [comment]
Hey @mandysimon88 - sorry, but I haven't worked in this codebase in several years. I was trying to help because it looked like the problem was a typo, but I think somebody else is going to have to take it from here. /cc @myronmarston
