### ISSUE TITLE
Remove `expect(…).to receive(…).with do...end` syntax

### ISSUE THREAD

**Issue by yujinakayama** [rspec/rspec-mocks#377]
Currently `MessageExpectation#with` supports the following syntax:

``` ruby
it 'receives #some_method with 1' do
  subject.should_receive(:some_method).with do |arg|
    arg == 1
  end

  subject.some_method(1)
end
```

This syntax allows you to expect arbitrary arguments _without_ `expect` or `should` by using the return value of the block passed to `#with`. This is available only when `#with` got no normal arguments but a block, and the block will _not_ be used as a substitute implementation.
- https://github.com/rspec/rspec-mocks/blob/e6d1980/lib/rspec/mocks/message_expectation.rb#L307
- https://github.com/rspec/rspec-mocks/blob/e6d1980/lib/rspec/mocks/argument_list_matcher.rb#L43

Then, if you convert the example into `expect` syntax straightforward:

``` ruby
it 'receives #some_method with 1' do
  expect(subject).to receive(:some_method).with do |arg|
    arg == 1
  end

  subject.some_method(1)
end
```

and run:

```
Failures:

  1) the issue with `expect(subject).to receive(:some_method).with do ... end` with #expect receives #some_method with 1
     Failure/Error: subject.some_method(1)
       Double "subject" received :some_method with unexpected arguments
         expected: (no args)
              got: (1)
```

This is caused by the lower precedence of `do..end` blocks. If you use `{..}` style block, it works. Basically this is similar to this one:
https://github.com/rspec/rspec-expectations/pull/295

I guess there's a way to handle this issue technically, though it would probably make `MessageExpectation` complex.

Rather, I'd like to suggest deprecating this feature. I think most users don't even know this exists and there's a reasonable alternative way. You can simply use `expect` in substitute implementation blocks like the example in [README](https://github.com/rspec/rspec-mocks/blob/e6d1980/README.md#arbitrary-handling).

In fact I didn't know this feature too. I've found this in [Guard's spec](https://github.com/guard/guard/blob/47b818d/spec/guard/notifiers/notifysend_spec.rb#L36) while testing my `should` to `expect` converter, though the spec seems to be using the feature unintentionally.

What do you think?

Reproducible example: https://gist.github.com/yujinakayama/6063761

**Comment by zw963** [comment]
This Post is old, But I want to say, in this case, use satisfy is redundant.

In Rspec 3(I use 3.2), You just need passed in one callable object, RSpec
will invoke this object call method lazily on spec lastest duration.

here is a example:

```ruby
          expect { post :create, promotion: valid_attributes }
          .to enqueue_a(Promotion::StatusSwitchJob)
          .with(lambda {|x| x == Promotion.last})
```

``lambda {|x| x == Promotion.last}`` will called after expect { ... } is execute, 
and lambda block is executed andl be verified.

**Comment by myronmarston** [comment]
> In Rspec 3(I use 3.2), You just need passed in one callable object, RSpec
> will invoke this object call method lazily on spec lastest duration.

This isn't quite accurate.  RSpec doesn't use `.call` as the interface there -- it uses `===`.  It just so happens that on Ruby 1.9+, lambdas implement `===`.

**Comment by zw963** [comment]
@myronmarston , I understood now,  so cool !
