### ISSUE TITLE
#ordered is not supported for any_instance

### ISSUE THREAD

**Issue by jarmo** [rspec/rspec-mocks#418]
I would like both of the examples to pass:

``` ruby
class A
  def x; y end
  def y; z end
  def z; end
end

describe A do
  it "does work" do
    a = A.new
    a.should_receive(:x).ordered.and_call_original
    a.should_receive(:y).ordered.and_call_original
    a.should_receive(:z).ordered.and_call_original

    a.x
  end

  it "does not work" do
    A.any_instance.should_receive(:x).ordered.and_call_original
    A.any_instance.should_receive(:y).ordered.and_call_original
    A.any_instance.should_receive(:z).ordered.and_call_original

    A.new.x
  end
end
```

Second one fails with `NoMethodError`:

```
Failure/Error: A.any_instance.should_receive(:x).ordered.and_call_original
     NoMethodError:
       undefined method `ordered' for #<RSpec::Mocks::AnyInstance::PositiveExpectationChain:0x51c6540>
```

Is this expected behavior?

**Comment by tansaku** [comment]
what about in feature tests where you are stubbing out a 3rd party service, and you are operating via capybara to hit a web interface?

**Comment by JonRowe** [comment]
> what about in feature tests where you are stubbing out a 3rd party service, and you are operating via capybara to hit a web interface?

In that situation you should use something like `webmock` to mock out the service endpoint. You shouldn't mock the internals of code you don't own, especially in an acceptance test.
