### ISSUE TITLE
Using "to_not have_received" with spy pattern

### ISSUE THREAD

**Issue by palfvin** [rspec/rspec-mocks#476]
The following example:

```
describe "" do
  it "" do
    Object.any_instance.stub(:bar)
    expect(Object.new).to_not have_received(:bar)
  end
end
```

fails with following error message:

```
 Failure/Error: expect(Object.new).to_not have_received(:bar)
   #<Object:0x007fade10435d0> expected to have received bar, but that method has not been stubbed.
```

My attempt to explain this is at http://stackoverflow.com/a/20152976/1008891, but I'm wondering if there is something I'm missing or if there is some improvement to RSpec that can be made.

**Comment by BrazhnykYuriy** [comment]
While migrating from Mocha to RSpec i've got this issue.
Is there any chance to get `.to have_received().never` and `.to_not have_received()` working with RSpec spies without too much refactoring?
While refactoring into `receive().never` you can easily get false-positives, unless you completely refactor the whole test to not use spies. And when you have more than thousand tests that is using this pattern you in trouble.

**Comment by JonRowe** [comment]
@BrazhnykYuriy I'm unsure what issue you are facing, the issue described here is specific to "any instance" which does not support asserting via spies that calls have never been made, but a normal expectation works fine.

**Comment by BrazhnykYuriy** [comment]
@JonRowe as i mentioned previously i'm migration from Mocha, which actually supports spies on any_instance. 
And the only solution i've got so far is to use `receive().never`, but again to refactor tests i would need to look through all of them and figure out what is the right order of execution. If this expectation would be after invocation it gives false-positives!!!
And when you have this pattern all over the place(20k tests), oh just kill me...

For me, this means that RSpec is not an option, it lacks core functionality...

Can you please explain why expecting any instance of a class to not receive message using spy pattern is  test smell?

**Comment by JonRowe** [comment]
> Can you please explain why expecting any instance of a class to not receive message using spy pattern is test smell?

In particular we view using any instance expectations as a smell, because its very invasive to the codebase and requires a lot of monkey patching, its error prone and causes false positives.

So we just haven't expanded its functionality when newer features (such as spies) have come along.

**Comment by BrazhnykYuriy** [comment]
@JonRowe
So you consider any use of `any_instance` a test-smell... Even without spy pattern?
Also i'm confused on why this is so difficult, since this was done almost 10 years ago for Mocha in ~100 LOC https://github.com/thoughtbot/bourne/tree/master/lib/bourne

This functionality proved to be really useful...

**Comment by JonRowe** [comment]
> So you consider any use of any_instance a test-smell... 

Yes

> Also i'm confused on why this is so difficult, since this was done almost 10 years ago for Mocha in ~100 LOC https://github.com/thoughtbot/bourne/tree/master/lib/bourne

In isolation features often look simple, especially if they only work for the "80%" of cases but there are real implementation difficulties ensuring that your monkey patched "tracking" methods are invoked first within a Ruby call stack (which they have to be to work, as you are replacing the implementation by default in an rspec-mock) and there are several sets of rules of precedence in differing Ruby versions. 

Add to this the fact that to "spy" you have do this for all methods a class might possess, create, or respond to at run time, and you get what we like to call, maintenance burden. 

So we as a team decided that as we viewed "any instance" expectations as an option for legacy code bases not properly in control of their allocation and not something we recommend in general usage not to extend our existing functionality and thus not add additional maintenance burden.

You are welcome to write an extension gem to add this functionality for those desiring it.

**Comment by BrazhnykYuriy** [comment]
@JonRowe Thanks. One last question. I guess you consider spy-pattern a test-smell too?

**Comment by JonRowe** [comment]
> I guess you consider spy-pattern a test-smell too?

Not at all, using a spy as a direct collaborator is perfectly fine in our eyes.
