### ISSUE TITLE
Double throws OutsideOfExampleError when description not given 

### ISSUE THREAD

**Issue by Ptico** [rspec/rspec-mocks#619]
Here is minimal example (tnx @cupakromer)

``` ruby
require 'spec_helper'

describe "Testing" do

  it do
    foo = double("Test")
    expect(foo).to be foo
  end

end
```

will throw

```
Failure/Error: Unable to find matching line from backtrace
       The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported.
```

with rspec-3.0.0.beta2

[full backtrace](https://gist.github.com/Ptico/9371259)

**Comment by arsduo** [comment]
This works for regular test failures but fails when the double is used in a raised error: https://gist.github.com/arsduo/733b802ef1d542c0e1227be59b519500.

I'll take a look at the PR that fixed the first part of it and see if I can figure out how to fix it; if not, I'll open another issue.

**Comment by myronmarston** [comment]
Thanks @arsduo!

**Comment by timriley** [comment]
@arsduo Just wanted to see how you got on with https://github.com/rspec/rspec-mocks/issues/619#issuecomment-203482008? I ran across the same problem as you described and luckily google found your gist, which brought me here.

I was raising an exception in my code under test and passing a double at the same time, which is what got me the unexpected "OutsideOfExampleError" RSpec error. Would be good to at least raise another issue to keep track of this if you haven't managed to work out a fix?

**Comment by florrain** [comment]
Bump 👊  ^. I got the same error while trying to raise an error instanciated with a double. Is there a known fix or workaround?

**Comment by myronmarston** [comment]
The work around is to not pass a double to an exception.  You can always use an `OpenStruct` or similar instead if you really need some kind of fake object.
