### ISSUE TITLE
instance_double attributes not using the same class it was given

### ISSUE THREAD

**Issue by nikkon226** [rspec/rspec-mocks#749]
I'm not sure if this is a duplicate of #744, but here is what I'm seeing in my controller tests.

```
let(:group){ instance_double("Group", id: 1) }
...
allow(Group).to receive(:find).with(1).and_return(group)

get :show, id: group.id
```

That should work fine, but here is what I get:

```
<Group(id: integer, type: string) (class)> received :find with unexpected arguments
         expected: (1)
              got: ("1")
        Please stub a default value first if message might be received with other args as well.
```

I also tried doing

```
let(:group){ instance_double("Group") }
...
allow(group).to receive(:id).and_return(1)
allow(Group).to receive(:find).with(1).and_return(group)

get :show, id: group.id
```

I get the same error as above.

**Comment by borenho** [comment]
I know this is closed, but to help anyone in future who might want to pass arguments to a stub/mock, you can use Openstruct. 
Like so:
`let(:group){ OpenStruct.new(id: 1) }`
then to mock you can do:
`allow(GroupModel).to receive(:find_by).with(id: group.id).and_return(some_group_record)`
