### ISSUE TITLE
Stubbing a method on any_instance_of(SomeModule) gives spurious error about prepended modules

### ISSUE THREAD

**Issue by afn** [rspec/rspec-mocks#781]
``` ruby
module Animal; def moo; end; end
class Cow; include Animal; end
expect_any_instance_of(Animal).to receive(:moo)
```

Raises:

```
Using `any_instance` to stub a method (moo) that has been defined on a prepended module (Animal) is not supported.
```

Should this:

``` ruby
prepended_modules = @klass.ancestors.take_while { |mod| !(Class === mod) }
```

stop when we encounter either a `Class` **or** `@klass` itself?

**Comment by mrgordon** [comment]
@myronmarston I'm seeing this on rspec and rspec-mocks 3.7. Do you know why this previous patch wouldn't have fixed my issue?

**Comment by myronmarston** [comment]
I'm not involved in RSpec anymore, and don't remember any details about this 10-year old issue, sorry.
