### ISSUE TITLE
and_wrap_original breaks in any_instance context

### ISSUE THREAD

**Issue by rf-** [rspec/rspec-mocks#867]
Example:

``` ruby
allow_any_instance_of(String).to receive(:upcase).and_wrap_original { |method| method.call }
```

Causes the error:

```
NoMethodError: undefined method `and_wrap_original' for #<RSpec::Mocks::AnyInstance::StubChain:0x007ff9facdbdc8>
```

The following monkeypatches make my specs work as expected, but I don't know if there are other places that also need to be fixed for it to be a complete solution:

``` ruby
class RSpec::Mocks::AnyInstance::StubChain
  prepend Module.new {
    def invocation_order
      @invocation_order ||= super.merge(
        and_wrap_original: [:with, nil]
      )
    end
  }
end

RSpec::Mocks::AnyInstance::Chain::Customizations.record :and_wrap_original
```

**Comment by JonRowe** [comment]
Well `prepend` isn't possible for us to use given we support Ruby < 2, and in general I'm wary of adding things to `any_instance` because we consider it a bad practise...

**Comment by rf-** [comment]
I'm not suggesting using `prepend` in real life. That's just a monkey-patch. The actual fixes would be adding `and_wrap_original` to [the definition of `RSpec::Mocks::AnyInstance::StubChain#invocation_order`](https://github.com/rspec/rspec-mocks/blob/master/lib/rspec/mocks/any_instance/stub_chain.rb#L34) and adding a `record :and_wrap_original` line [here](https://github.com/rspec/rspec-mocks/blob/master/lib/rspec/mocks/any_instance/chain.rb#L46). I don't know if there are other places that also need to be updated though.
