### ISSUE TITLE
Verifying doubles with as_null_object should verify arguments

### ISSUE THREAD

**Issue by aaronjensen** [rspec/rspec-mocks#878]
This test currently passes, but it would be nice if it failed:

```ruby
describe "test" do
  class Klass
    def foo(arg1, arg2)

    end
  end

  it "should fail" do
    klass = instance_spy Klass
    # expect(klass).to receive(:foo).with(3) # This fails, but...
    klass.foo(3) # It should fail here...
    expect(klass).to have_received(:foo).with(3) # Or at least here
  end
end
```

The docs specify that you must declare an argument matcher in order to get argument verification. This doesn't work if you're using spies because there's no reason to use argument matchers except in the expectation, and those are ignored. 

Maybe there's an option to enable this strict behavior?

**Comment by myronmarston** [comment]
> This test currently passes, but it would be nice if it failed:

It does fail -- on master.  The fix is in #829 and will be included in the soon-to-be-released RSpec 3.2.

> The docs specify that you must declare an argument matcher in order to get argument verification.

This isn't accurate -- can you point me to where you read that so we can clarify it?  With verified doubles, you don't have to use an argument matcher to have it verify the args against the method signature.  You can use argument matcher to verify additional things about the method call, though.

**Comment by aaronjensen** [comment]
Awesome! I guess I didn't search hard enough, thanks for that.

Here are the docs I was referring to: https://relishapp.com/rspec/rspec-mocks/v/3-1/docs/verifying-doubles/using-an-instance-double

>  If any argument matchers are specified, it also verifies that the
number of arguments is correct.

**Comment by myronmarston** [comment]
Thanks for directing me to that.  Can you check the new wording I've pushed in #879 and tell me if that makes more sense?

**Comment by aaronjensen** [comment]
Yes, that's more clear, thanks.

**Comment by myronmarston** [comment]
The doc update is live:

https://relishapp.com/rspec/rspec-mocks/v/3-1/docs/verifying-doubles/using-an-instance-double
