### ISSUE TITLE
Idea: use the method signature of `MyClass#initialize` for verified double argument verification of `MyClass.new`

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-mocks#883]
When a user mocks or stubs `.new` on a verified partial class double or on a `class_double`, we are not currently able to do any argument verification because the signature of `Class#new` is so generic.  Compare the two parameter lists:

``` irb
irb(main):001:0> class Foo; def initialize(foo:, bar:); end; end
=> :initialize
irb(main):002:0> Foo.method(:new).parameters
=> [[:rest]]
irb(main):003:0> Foo.instance_method(:initialize).parameters
=> [[:keyreq, :foo], [:keyreq, :bar]]
```

I think that for the special case of mocking or stubbing `.new` on a class, we should look at the method signature of `#initialize` instead since we know that `Class#new` delegates to that.  It is possible for users to redefine `new` so we'll probably want to only do this if `MyClass.method(:new).owner == Class`.

There may be some negative repercussions to this I'm not thinking of (can anyone think of any?).  Also, are there any other "hook" methods (`initialize`, in this case) that define the method signature for another common method (`new`, in this case) that should receive similar treatment?  I can't think of any.

/cc @xaviershay @rspec/rspec

**Comment by JonRowe** [comment]
I think thats reasonable for us to do
