### ISSUE TITLE
'disallow' an allowance?

### ISSUE THREAD

**Issue by ToadJamb** [rspec/rspec-mocks#895]
I like to provide a class that contains the interface to external/dangerous things and then use a global `before` block to inspect the class/module and raise errors if any of the methods are called without being mocked/stubbed. I want to use a helper method that looks something like this:

```ruby
    def not_implemented(klass, method)
      allow(klass)
        .to receive(method)
        .and_raise NotImplementedError,
          "#{klass}.#{method} has been stubbed as not implemented."
    end
```

I was using mocha before (using `stub` and `unstub`), but I'm trying to convert to rspec-mocks. Is there a way to 'disallow' an 'allowance' so that I can then provide expectations without raising an error? My trials have resulted in either raising the stubbed error above or unmet expectations.

**Comment by myronmarston** [comment]
You can use either of these to cause an example to fail if a method is called (and to prevent the dangerous stuff from running):

    expect(klass).not_to receive(:method)
    expect(klass).to receive(:method).never

Alternately, you might consider replacing the class with a pure test double (which obviously can't do the dangerous stuff):

    class_double(MyClass).as_stubbed_const

**Comment by ToadJamb** [comment]
Thank you! I did manage to get everything working close enough to the way I wanted. I did have one other thing come up, though. I couldn't quite figure out how to return different results from a method given the same inputs (this applies to yielding, as well). Is there a way to do that?

**Comment by myronmarston** [comment]
> I couldn't quite figure out how to return different results from a method given the same inputs (this applies to yielding, as well). Is there a way to do that?

Use `with` for that:

``` ruby
dbl = double("MyThing")
allow(dbl).to receive(:foo).with(1).and_return("one")
allow(dbl).to receive(:foo).with(2).and_return("two")

dbl.foo(1) # => "one"
dbl.foo(2) # => "two"
```

Gonna close this since there isn't anything in this issue for us to change in RSpec, but I'm happy to continue the conversation if you have more questions.

**Comment by ToadJamb** [comment]
Closing this is fine.

Using `with` doesn't work, though. I have cases where the same thing is called with the same parameters.

The behavior I'm looking for is something like:

```ruby
dbl = double('MyThing')
allow(dbl).to receive(:foo).with(1).and_return 'a'
allow(dbl).to receive(:foo).with(1).and_return 'b'

dbl.foo(1) #=> 'a'
dbl.foo(1) #=> 'b'
```

I have cases where I want different output, but the inputs are always the same. For instance, a loop that writes to a file, then reads from it and deletes it. The input `out.log` is always the same, but the content yielded could be quite different depending on which item the loop is on.

**Comment by JonRowe** [comment]
You can wire up your own custom return logic using a block.
```Ruby
results = %w[a b]
allow(dbl).to receive(:foo).with(1) { results.shift }
```

**Comment by myronmarston** [comment]
> You can wire up your own custom return logic using a block.

That works, or `and_return` can take multiple arguments, which are treated as sequential return values:

``` ruby
dbl = double('MyThing')
allow(dbl).to receive(:foo).with(1).and_return('a', 'b')

dbl.foo(1) #=> 'a'
dbl.foo(1) #=> 'b'
```

**Comment by myronmarston** [comment]
BTW, the docs on [configuring responses](https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/configuring-responses) are fairly complete, so you might read over those.  Let us know if there's anything else that's unclear from the docs.

**Comment by ToadJamb** [comment]
Thank you! I do find the documentation quite good on RSpec, but could not for the life of me find that. I swear I looked.
