### ISSUE TITLE
Chained receive statements with method arguments

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [rspec/rspec-mocks#897]
A feature that would be really nice is to be able to chain multiple `receive(args).with(args)` methods together. Chained methods are supported with the `receive_message_chain` method, and is really nice. However I don't see how useful it is if you can't actually, somehow, test the arguments. 

Would it be possible to implement a syntax like this? `expect(obj).to receive(:method_name).with("data").receive(:method_two).with("data2").and_return("result")`

Example of use case:

Say I want to test a single-fire object like `MessageClass.new("data").send_to("username")`. Of course you can use spy on the `MessageClass` and stub the new method, and then run an ´expect´ on the spy. But it is tedious and would be much nicer to have in a chain.

Also, there are probably some piping libraries that could benefit from this as well, think: `dataset.filter("whatever").order.first(20)`.

Is this kind of chaining at all possible? If it is, I think it would be a really nice addition to rspec-mocks. I would love to help out developing this, but I don't know where to start.

**Comment by myronmarston** [comment]
As discussed in https://github.com/rspec/rspec-mocks/issues/904#issuecomment-77389895 (and also in our docs: https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/working-with-legacy-code) we consider `receive_message_chain` to be a code smell that can be useful for testing legacy code and other similar situations, but isn't usually something we recommend.  As such, we're not very keen on taking on increased maintenance for it in the form of additional features.

If you find useful needing this, use it as a signal to improve the design of your code.  For example, for the `MessageClass` case, I'd use this as a signal to add a class method that's more easily stubbed:

``` ruby
class MessageClass
  def self.send_data_to(data, username)
    new(data).send_to(username)
  end

  # ...
end
```

As a single-fire object (as you described it), instantiating `MessageClass` doesn't really serve a purpose for the caller, other than to get at the method it needs to use.  Why not make this use case more first-class by supporting it directly on `MessageClass`?  It elevates the intended public API and makes it obvious what entry point callers are intended to use for it.  Then you can mock or stub `send_data_to`.

**Comment by stephan-nordnes-eriksen** [comment]
I do agree that this can be a sign of poorly designed code, but the case for pipelining in my mind still holds. But maybe pipelines can be tested differently, like `expect(one.two.three).to be_kind_of(PipeLine)`, and then see that the correct modification is done to the underlying data structure. I'm not sure. 

I do see the case that this kind of feature might unnecessarily complicate things.
