### ISSUE TITLE
Expectations for `with`, not adding display precision for Time and DateTime

### ISSUE THREAD

**Issue by gavingmiller** [rspec/rspec-mocks#898]
Based on [#331](https://github.com/rspec/rspec-expectations/issues/331), [#416](https://github.com/rspec/rspec-expectations/pull/416), and [f9ee8f9](https://github.com/rspec/rspec-expectations/commit/f9ee8f9cae0696b8aae97492035d31b866b636d6), I would expect that a call made to `with` comparing a `Time` or `DateTime` to output the same display precision as a non-`with` test would. Unfortunately it doesn't. :disappointed: 

Here's an example:

```ruby
context 'test' do
  class Fake; def blah(time); end; end

  it 'fails nicely' do
    expect(Time.now).to eq Time.now
  end

  it 'fails poorly' do
    expect_any_instance_of(Fake).to receive(:blah).with(Time.now)
    Fake.new().blah(Time.now)
  end
end
```

And the output:

```ruby
1) test fails nicely
   Failure/Error: expect(Time.now).to eq Time.now

     expected: 2015-02-19 00:09:28.123861000 +0000
          got: 2015-02-19 00:09:28.123845000 +0000

     (compared using ==)

     Diff:

   # ./spec/fake_spec.rb:10:in `block (5 levels) in <top (required)>'

2) test fails poorly
   Failure/Error: Fake.new().blah(Time.now)
     #<Fake:0x007fb3f8f395b8> received :blah with unexpected arguments
       expected: (2015-02-19 00:09:28 +0000)
            got: (2015-02-19 00:09:28 +0000)
   # ./spec/fake_spec.rb:20:in `block (5 levels) in <top (required)>'
```

I'd love to provide a PR for this, but can't find the seam to insert this code. If someone could point me in the right direction, that'd be awesome. :smile:

**Comment by myronmarston** [comment]
This is definitely something we should fix, and thanks for offering to work up a PR!

There are some other known situations where we should show the increased precision -- see rspec/rspec-expectations#611.

To use the same formatting logic in rspec-mocks and rspec-expectations, it'll need to go in rspec-support. The differ has already been moved there.  I think we should extract the `format_object` method from `eq`:

https://github.com/rspec/rspec-expectations/blob/08c11431771b7755d2a402746b0fe4f8aec8d4ff/lib/rspec/matchers/built_in/eq.rb#L38-L48

...and move that into some rspec-support helper method.  Then we should go through rspec-expectations and rspec-mocks and find all places where we use `inspect` and consider changing to that new helper method.  This is one of those little things that will make a big difference to users but can be a bit tedious, so if you wanted to take that on, that would be fantastic :).

**Comment by gavingmiller** [comment]
Started on this work, and I'm finding myself having to write many tests like [this set in built_in/eq_spec.rb](https://github.com/rspec/rspec-expectations/pull/740/files#diff-e44275aadbb825f5d1baf542701a1cf9R50). If someone has a suggestion on how to test that the [OutputFormatter](https://github.com/rspec/rspec-support/pull/184/files#diff-7b333b879d9eceaa044b5e66b589a83fR5) is being used more simply, that would be greatly appreciated! :smile:
