### ISSUE TITLE
Why would this per test mock cause a deprecation warning?

### ISSUE THREAD

**Issue by ramarnat** [rspec/rspec-mocks#903]
```
  # mock the response of the oauth-provider
  before(:each) do
    Grape::Endpoint.before_each do |endpoint|
      endpoint.stub(:authorize!).and_return(true)
    end
  end
```

**Comment by myronmarston** [comment]
Which deprecation warning, specifically?

**Comment by ramarnat** [comment]
oops. `Using rspec-mocks doubles or partial doubles outside the per-test lifecycle (such as in a `before(:all)` hook) is deprecated`

**Comment by myronmarston** [comment]
When does `Grape::Endpoint.before_each` execute the block given to it?  I suspect that it's executing the block between examples or after all examples have run.

**Comment by ramarnat** [comment]
ah. It seems to run when the get/put methods seem to run. Any thoughts on how we could stub the oauth authorization across all the examples?

**Comment by ramarnat** [comment]
closed in favor of an issue with the grape repo https://github.com/intridea/grape/issues/941

**Comment by myronmarston** [comment]
Does grape expose another way to get the `endpoint` object?  If so, you could grab that and stub it.  If not, I suggest moving the auth logic out of the grape endpoint and into a standalone object that you control, and then you can dependency inject an alternate test implementation (e.g. a test double that always authenticates).
