### ISSUE TITLE
Verify that an object received a message chain?

### ISSUE THREAD

**Issue by mathie** [rspec/rspec-mocks#904]
Leaving aside the tasteless violations of poor Demeter, this morning I wound up writing the following code:

```ruby
before(:each) do
  allow(user).to receive_message_chain(:receipts, :build)
end

it 'builds a new receipt' do
  get :new
  expect(user).to have_received_message_chain(:receipts, :build)
end
```

I expected that since `have_received` exists for verifying stubbed methods are called, then there would be the corresponding method for verifying stubbed message chains.

Of course the workaround is just to set up the expectation before the method call:

```ruby
before(:each) do
  allow(user).to receive_message_chain(:receipts, :build)
end

it 'builds a new receipt' do
  expect(user).to receive_message_chain(:receipts, :build)
  get :new
end
```

but I've fallen in love with spies, and having a consistent given/when/then pattern for all my specs. Would it be possible to implement `have_received_message_chain`?

**Comment by JonRowe** [comment]
`receive_message_chain` exists to be the `expect` syntax equivalent of `stub_chain`, but as such we consider it a legacy feature (like `stub_chain` and `any_instance`) which we're not keen to expand to "new" features like spies... so as such I'm closing for now.

**Comment by mathie** [comment]
Apologies if this is the wrong place to ask, but if `receive_message_chain`, `stub_chain` and `any_instance` are legacy, what’s the current best practice replacement? I should probably fix my code to stop using them! :smile:

Thank you for taking the time to follow up with the issue.

**Comment by myronmarston** [comment]
To expand on what @JonRowe said, it's not that the features themselves are legacy as that we consider them code smells and the main place we see them being useful is when you're testing legacy code.  The docs explain why:

https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/working-with-legacy-code

We recommend designing your code so that rather than needing `any_instance` (which is a very imprecise), you can inject a test double from your test, and then precisely stub or mock just that object.  Similarly, for a case like `stub_chain` or `receive_message_chain`, the need to deal with a message chain as a unit is a signal that you'll probably be better off providing a single method providing that functionality (perhaps by having it internally delegate to the message chain).

Mocking should be used to push your code towards simpler, easier-to-reason about interfaces, rather than being used to encode complex interfaces in your test suite.

**Comment by JonRowe** [comment]
If you truly have to mock out instance creation personally I recommend:

class_double('Class', new: instance_double('Class')).as_stubbed_const

Often using a specific instance_double as a let so I can refer to it.

For receive_mesage_chain I suggest refactoring the code to not need it,
using it is generally a code smell in my opinion.

The caveat to that is of course Rails, but what I can suggest there is
designing your Rails app such that you can pass collaborators (often fully
formed Rails objects like AR queries) into service objects and unit test
those with normal instance_doubles and then test the controller level with
integration/feature tests without mocking.

Thank you for taking the time to follow up with the issue.
>

No worries, thanks for taking the time to contribute :)

**Comment by davidhan527** [comment]
I also originally had the same question as @mathie about implementing `have_received_message_chain`, but your explanations make a lot of sense. 
is there an advantage to using `as_stubbed_const` (if your not planning on transferring nested constants) over doing:

`expect(Class).to receive(:new).and_return(instance_double('Class'))` 

I tried to research as_stubbed_const but didn't find too many examples out there.

**Comment by myronmarston** [comment]
`as_stubbed_const` replaces the class's constant with the fake version of the class.  This means that you have a strong guarantee that a caller isn't using some other class methods.  That can be useful when you're using a test double to isolate things.  Stubbing `Class.new` to return the instance is fine, too, but it doesn't provide the same level of isolation.  Depends on what you are trying to achieve.

**Comment by JonRowe** [comment]
It also means it works without the class loaded at all (note the string
rather than actual constant)

**Comment by davidhan527** [comment]
that makes a lot of sense and I will start using as_stubbed_const immediately.. thanks for your answers!

**Comment by mathie** [comment]
Thank you for the insight. I’m quite a fan of `as_stubbed_const` and verifying doubles — I wrote a little about them here <https://woss.name/articles/specifying-rails-controllers-with-rspec/ <https://woss.name/articles/specifying-rails-controllers-with-rspec/>> a few weeks back.

And yes, my use case for `receive_message_chain` is ActiveRecord associations, etc, that wilfully flaunt the law of Demeter. Delegating appropriately inside the model would certainly make for cleaner tests!
--
Graeme Mathieson

Follow me on Twitter: @mathie <https://twitter.com/mathie>
Blog: <http://woss.name/ <http://woss.name/>>
Telephone: +44 (0)7949 0777 44

**Comment by Rio517** [comment]
FYI, you could do this (from the opening example):

```ruby
before(:each) do
  allow(user).to receive_message_chain(:receipts, :build)
end

it 'builds a new receipt' do
  get :new
  expect(user.receipts).to receive(:build)
end
```
