### ISSUE TITLE
NoMethodError: undefined method `any_instance' for ClassName

### ISSUE THREAD

**Issue by mcshakes** [rspec/rspec-mocks#905]
Hey,

So when I run "rake test" on this file:
```Ruby
require_relative '../test_helper'

class UserProfileTest < ActionDispatch::IntegrationTest
  include Capybara::DSL
  attr_reader:user

  def setup
    @user = User.create(user_name: 'kip', password: 'pass')
  end

  test "registered user can view their profile" do
    ApplicationController.any_instance.stubs(:current_user).returns(user)
    visit user_path(user)
    within("#banner") do
      assert page.has_content?("kip's profile")
    end
  end
end
```
I get this error message:
```
1) Error:
UserProfileTest#test_registered_user_can_view_their_profile:
NoMethodError: undefined method any_instance' for ApplicationController:Class test/integration/user_profile_test.rb:12:inblock in class:UserProfileTest'
```
Am I doing something wrong as far as loading up mocha within my Gemfile? I've loaded it like this:
```Ruby
group :development, :test do
  gem 'byebug'

  gem 'web-console', '~> 2.0'
  gem 'capybara'
  gem 'launchy'
  gem 'rspec-rails'
  gem 'mocha'
end
```
Is this a problem with the Mocha gem, as I was previously running Minitest before switching to RSpec in the same repo.

**Comment by JonRowe** [comment]
You're still writing a Minitest test there, unless you've configured `rspec-mocks` to integrate with Minitest, (which I can't tell if you have because I can't see your test helper) you can't use RSpec methods in minitest tests. See https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/outside-rspec/integrate-with-minitest .

**Comment by myronmarston** [comment]
Also, in your gemfile it looks like you're attempting to use mocha, not rspec-mocks.

What test setup are you attempting to use?  RSpec can be mixed and matched with parts of minitest and with mocha but you'll need to share what you're trying to accomplish before we can advise you.

**Comment by mcshakes** [comment]
Whoops, sorry for the delay in replying. To the first reply, yes, I was going to try and integrate with Minitest (before just scrapping that test file in favor of rspec). And to myron, yep, I missed that. I need to add the mocks, though this problem was with mocha. I'll contact them, I may be running an older version instead of specifying the latest in the gemfile and helper.
Thanks guys for the help anyway!
