### ISSUE TITLE
[FEATURE] Default name for doubles

### ISSUE THREAD

**Issue by mariogintili** [rspec/rspec-mocks#909]
Hello guys,

I've found hard to debug tests that have +1 unnamed double. Like

```ruby
RSpec.describe "So many dubs" do

  let(:camel) { double }
  let(:lion) { double }
  let(:another_double) { double }

  it 'does not name a doubles' do
     lion.eat(camel)
     expect(camel).to be_eaten
     expect(lion).to be_full
  end
end
```

```
F

Failures:

  1) So many dubs does not name a doubles
     Failure/Error: lion.eat(camel)
       Double received unexpected message :eat with (#<RSpec::Mocks::Mock:0x89a2540c @name=nil>)
     # ./spec/dumb_test_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.01773 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/dumb_test_spec.rb:9 # So many dubs does not name a doubles
```

Because mocks are unnamed, however they are  being assigned through a symbol, that could also be their name rather than nothing. Seems like something quite vanilla to implement and will add a lot of value, what do you guys think?

**Comment by myronmarston** [comment]
> Seems like something quite vanilla to implement

Funny, it doesn't seem vanilla to implement to me.  What implementation did you have in mind?  Bear in mind that `let` is an rspec-core feature and `double` is an rspec-mocks feature and each rspec lib needs to be usable on its own.

**Comment by mariogintili** [comment]
> Bear in mind that let is an rspec-core feature and double is an rspec-mocks feature and each rspec lib needs to be usable on its own.

Not vanilla to implement then.

I could take a look on rspec-core's  ``let`` implementation and get back to you?

**Comment by myronmarston** [comment]
> I could take a look on rspec-core's let implementation and get back to you?

Sure.  Or it might be easier to put this into an external gem that can depend on rspec-core and rspec-mocks.

**Comment by JonRowe** [comment]
Yeah given "vanilla" RSpec this would be pretty difficult to implement ;)

**Comment by mariogintili** [comment]
Ok guys let's not then :)
