### ISSUE TITLE
Receive Counts with Recursive Methods

### ISSUE THREAD

**Issue by aowainati** [rspec/rspec-mocks#917]
Hi, running into an issue with the Receive Counts functionality in rspec-mocks, unsure if it's a bug or if it's misuse on my part. Assume I have a simple recursive method in a class:

```
class Bar
    def foo(i=5)
        puts "Foo"
        if i > 1
            foo(i-1)
        end
    end
end
```

I want to write a spec to ensure that it's recursing the correct number of times, so I thought this might be the correct spec to write:
```
...
# assume bar is an instance of Bar
expect(bar).to receive(:foo).exactly(5).times
bar.foo
...
```
This spec fails for me claiming that bar.foo is only getting called once. Any help is appreciated!

**Comment by myronmarston** [comment]
When you expect or allow a message it defines it as a no-op by default (rather than falling through to your logic). If you want it to fall through, tack on 'and_call_original'.

**Comment by aowainati** [comment]
That did it! Thank you!
