### ISSUE TITLE
rspec-mocks + minitest 5.6 dont play nice together

### ISSUE THREAD

**Issue by arthurnn** [rspec/rspec-mocks#931]
see https://github.com/jekyll/jekyll/issues/3656

Minitest 5.6 now defines a `expect` method, which collides with rspec-mocks.
What we can do about it:
 - Dont do anything, but I am sure people will open issues here confused.
 - Lock minitest version in rspec-mocks.
 - Give a warning to the user, so they will better understand the error and the solution.

thoughts?

**Comment by myronmarston** [comment]
Good to know.  Ideally, I'd like to find a way to make rspec-mocks and minitest 5.6+ play nice together.  For rspec-expectations, we added a file that takes care of integrating it with minitest awhile back:

https://github.com/rspec/rspec-expectations/blob/v3.2.1/lib/rspec/expectations/minitest_integration.rb

https://github.com/rspec/rspec-expectations/blob/v3.2.1/features/test_frameworks/minitest.feature

I think we could similarly add a `rspec/mocks/minitest_integration` file that minitest users who use rspec-mocks could use to deal with integrating the two and handling the dual role of `expect`.  We'll need to think carefully about how to make `expect` compatible with both libs, though.

**Comment by myronmarston** [comment]
Here's a simple way to make them compatible:

* Move the `to` and `not_to` methods currently defined on `RSpec::Mocks::ExpectationTarget` into a module (which is included into `RSpec::Mocks::ExpectationTarget` to keep the method available there).
* In the new `rspec/mocks/minitest_integration` file, we would also include the module in `Minitest::Expectation` if `Minitest::Expectation` is defined.

BTW, you can see the relevant minitest change here:

https://github.com/seattlerb/minitest/commit/9e78cc974f3ef0d9716f1cca2675753cf5f648d0

**Comment by arthurnn** [comment]
[related https://github.com/jekyll/jekyll/pull/3658]

**Comment by envygeeks** [comment]
Attaching myself to this ticket so I get notified if you guys make any changes and can remove our hacks from Jekyll.  Thanks @arthurnn and @myronmarston!

**Comment by arthurnn** [comment]
I think , to fix this, we could disable expecations on minitest using that env var https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L327

**Comment by myronmarston** [comment]
> I think , to fix this, we could disable expecations on minitest using that env var https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L327

Maybe I'm reading the code wrong, but I don't see how that will help.  The `expect` method is defined in `Minitest::Spec::DSL::InstanceMethods` and will be unaffected by that environment variable.  Even if it were to solve the problem, I don't think it's a solution I'd be happy with; users should be able to use minitest-spec's `obj.must_xyz` syntax and rspec-mocks in the same project if they wish.  (Some users may already be doing that and preventing the `must_xyz` methods from being added to `Object` would be a breaking change for them).

As I said above, I think the solution is to define a `rspec/mocks/minitest_integration` file that, among other things, includes a module in `Minitest::Expectation` that provides the `to` and `not_to` methods so that it works properly.

**Comment by envygeeks** [comment]
I agree with @myronmarston.  While I wouldn't complain if it did happen that way (because it is an rspec lib after all) it would bum me out that it did have to happen that way.

**Comment by robotfelix** [comment]
I've whipped together a simple patch for this problem, which fixes the problem for me. An `rspec/mocks/minitest_integration` file is added, which needs to be loaded after minitest.

For a future improvement, the refactoring suggested by @myronmarston (allowing the `Minitest::Expectation` class to handle `#to`, `#not_to` & `#to_not` directly) would save allocating an `RSpec::Mocks::ExpectationTarget ` for each call.
