### ISSUE TITLE
#receive_message_chain does not work with #ordered

### ISSUE THREAD

**Issue by jarmo** [rspec/rspec-mocks#934]
Previously this code worked:
```ruby
allow(foo).to receive_message_chain(:bar, :baz).ordered.with(0).and_return(result)
```

Now it doesn't work anymore:
```
NoMethodError:
       undefined method `ordered' for #<RSpec::Mocks::Matchers::ReceiveMessageChain:0x007fa4da5e7af0>
```

**Comment by myronmarston** [comment]
I wasn't aware that ever worked. On which previous version of RSpec did you see it work?

**Comment by JonRowe** [comment]
`stub_chain(*args).ordered` does in fact exist, but it doesn't work...

e.g. both this:

```Ruby
RSpec.describe do
  specify do
    obj = Object.new
    obj.stub_chain(:one, :two).ordered
    obj.stub_chain(:check, :one).ordered
    obj.one.two
    obj.check.one
  end
end
```

and this: 

```Ruby
RSpec.describe do
  specify do
    obj = Object.new
    obj.stub_chain(:one, :two).ordered
    obj.stub_chain(:check, :one).ordered
    obj.check.one
    obj.one.two
  end
end
```

Pass.

Therefore I'm going to say this was never supported and your specs where passing by coincidence.

**Comment by jarmo** [comment]
That's what i expected when @myronmarston asked that question right now :) It was some legacy spec code, which i upgraded yesterday from 2.14 to 3 when it started to fail.

Closing this "bug" seems fair to me, although i'd say that it was a bug in 2.x where it didn't work nor blew up :)

**Comment by JonRowe** [comment]
> Closing this "bug" seems fair to me, although i'd say that it was a bug in 2.x where it didn't work nor blew up :)

Yep, but we're not maintaining `2.x`, what should happen is it blows up on `2.x`
