### ISSUE TITLE
Consider switching from `caller` to raising exceptions to get backtrace for improved performance

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-mocks#937]
There are a number of places in rspec-mocks where we use `caller` (generally via `RSpec::CallerFilter`).  We've known for a while that `caller` is extremely slow.  Another way to get the backtrace is to raise an exception and use `Exception#backtrace` to get it.  A benchmark shows that, unsurprisingly, using `raise` to get a backtrace is slightly slower than `caller`:

``` ruby
require 'benchmark/ips'

def create_stack_trace(n, &block)
  return create_stack_trace(n - 1, &block) if n > 0
  yield
end

[10, 50, 100].each do |frames|
  create_stack_trace(frames) do
    Benchmark.ips do |x|
      x.report("use caller (#{caller.count} frames)") do
        caller
      end

      x.report("use raise (#{caller.count} frames)") do
        exception = begin
          raise "boom"
        rescue => e
          e
        end

        exception.backtrace
      end

      x.compare!
    end
  end
end
```

```
Calculating -------------------------------------
use caller (16 frames)
                         5.204k i/100ms
use raise (16 frames)
                         4.350k i/100ms
-------------------------------------------------
use caller (16 frames)
                         58.244k (±11.1%) i/s -    291.424k
use raise (16 frames)
                         49.039k (± 7.7%) i/s -    247.950k

Comparison:
use caller (16 frames):    58244.5 i/s
use raise (16 frames):    49039.1 i/s - 1.19x slower

Calculating -------------------------------------
use caller (56 frames)
                         2.083k i/100ms
use raise (56 frames)
                         2.020k i/100ms
-------------------------------------------------
use caller (56 frames)
                         22.368k (±10.1%) i/s -    112.482k
use raise (56 frames)
                         21.176k (±10.0%) i/s -    107.060k

Comparison:
use caller (56 frames):    22368.3 i/s
use raise (56 frames):    21175.7 i/s - 1.06x slower

Calculating -------------------------------------
use caller (106 frames)
                         1.254k i/100ms
use raise (106 frames)
                         1.231k i/100ms
-------------------------------------------------
use caller (106 frames)
                         13.076k (± 9.3%) i/s -     65.208k
use raise (106 frames)
                         12.389k (± 9.3%) i/s -     61.550k

Comparison:
use caller (106 frames):    13075.8 i/s
use raise (106 frames):    12388.7 i/s - 1.06x slower
```

However, if you remove the call to `exception.backtrace`, the results look very, very different:

```
Calculating -------------------------------------
use caller (16 frames)
                         5.184k i/100ms
use raise (16 frames)
                        26.722k i/100ms
-------------------------------------------------
use caller (16 frames)
                         55.945k (±13.8%) i/s -    274.752k
use raise (16 frames)
                        400.459k (±15.1%) i/s -      1.951M

Comparison:
use raise (16 frames):   400458.6 i/s
use caller (16 frames):    55944.8 i/s - 7.16x slower

Calculating -------------------------------------
use caller (56 frames)
                         2.229k i/100ms
use raise (56 frames)
                        22.596k i/100ms
-------------------------------------------------
use caller (56 frames)
                         22.769k (± 9.8%) i/s -    113.679k
use raise (56 frames)
                        331.157k (± 9.5%) i/s -      1.650M

Comparison:
use raise (56 frames):   331156.9 i/s
use caller (56 frames):    22769.3 i/s - 14.54x slower

Calculating -------------------------------------
use caller (106 frames)
                         1.294k i/100ms
use raise (106 frames)
                        19.634k i/100ms
-------------------------------------------------
use caller (106 frames)
                         12.954k (±10.4%) i/s -     64.700k
use raise (106 frames)
                        244.556k (±10.2%) i/s -      1.217M

Comparison:
use raise (106 frames):   244555.6 i/s
use caller (106 frames):    12953.6 i/s - 18.88x slower
```

In this case, `caller` is an _order of magnitude_ slower than `raise`.  I think this means that there's an opportunity for a large, noticable perf win if we switch away from using `caller` to `raise` for situations where we don't immediately need the backtrace but are merely storing it for possible later use.  This is the case, for example, for much of rspec-mocks usage of `caller`: when a test double is declared, we store the backtrace so that if there's a mock expectation error, we can use the declaration site in the stacktrace.  But if there is no mock expectation error, we don't use the stacktrace and the fact we called `caller` was wasted work.  Given that the more common case is for a spec to pass, I think it would be worthwhile to switch.

Here are the places in rspec-mocks that could potentially benefit from this:

```
➜  rspec-mocks git:(master) ack CallerFilter lib
lib/rspec/mocks/matchers/receive_messages.rb
8:          @backtrace_line = CallerFilter.first_non_rspec_line

lib/rspec/mocks/message_expectation.rb
588:            "Called from #{CallerFilter.first_non_rspec_line}."

lib/rspec/mocks/proxy.rb
51:        location = opts.fetch(:expected_from) { CallerFilter.first_non_rspec_line }
113:        location = opts.fetch(:expected_from) { CallerFilter.first_non_rspec_line }
435:        source = CallerFilter.first_non_rspec_line
```

Given that we use `RSpec::CallerFilter` here, the change for this will probably involve rspec-support changes to provide a `RSpec::CallerFilter.lazy` (or some similar API).

It's probably also worth looking at the rspec-core and rspec-expectations usage of `caller` and `RSpec::CallerFilter` as there could be some places there that could similarly be improved.

/cc @rspec/rspec

**Comment by JonRowe** [comment]
Did you benchmark this against `caller_locations` too? We already use that where available rather than `caller` for performance reasons.

Anyway I'm in favour of doing something here at least for the `caller` case so, I've opened a PR on rspec-support (rspec/rspec-support#) that uses the raise and capture trick but lazily finds the line from the backtrace based on a `to_s` call. I figure most places we return a caller line will be interpolated into a string giving us this "lazy"ness with much less work. (I use this trick in Rails apps to wrap values with presenters but don't convert the values until the last second, interpolating into templates ;))

**Comment by myronmarston** [comment]
> Did you benchmark this against `caller_locations` too? We already use that where available rather than `caller` for performance reasons.

Nope, I haven't done a benchmark yet.  I expect `raise` to be significantly faster, though; our [caller vs caller_locations](https://github.com/rspec/rspec-support/blob/master/benchmarks/caller_vs_caller_locations.rb) benchmark shows a 2-3x perf benefit out of using `caller_locations` but my benchmark here shows a 7-19x perf benefit so `raise` is almost certainly going to be faster than `caller_locations`.

> Anyway I'm in favour of doing something here at least for the caller case so, I've opened a PR on rspec-support (rspec/rspec-support#199)

Thanks...I'll go comment there :).

**Comment by xaviershay** [comment]
nice find

**Comment by JonRowe** [comment]
See the discussion on rspec/rspec-support#199 it's not actually faster in practise.
