### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by npearson72** [rspec/rspec-mocks#939]
I have the following code in my categories controller:

````
  def destroy
    category = Category.find(params[:id])
    category.destroy
    render json: nil, status: :ok
  end
````

My test looks like:

````
  describe "DELETE #destroy" do
    let(:category) { create :category }

    subject { delete :destroy, id: category.id }

    it "should call Category.find" do
      expect(Category).to receive(:find).and_call_original
      subject
    end
  end
````

I get the following test results:

````
  expected: 1 time with any arguments
  received: 2 times with any arguments
````

I have the exact same setup for a different controller (addresses) and it works perfectly fine.

Any ideas?

**Comment by myronmarston** [comment]
Something else in your code base must be calling `Category.find` a 2nd time.  Try changing your message expectation to:

``` ruby
allow(Category).to receive(:find).and_wrap_original do |original, *args|
  puts "Category.find is begin called from:"
  puts caller.join("\n")
  puts

  original.call(*args)
end
```

That'll hook into your `Category.find` method and print off the stack trace for each call so you can identify where the 2nd call is coming from.

**Comment by npearson72** [comment]
Ah, thanks for the help! Seems like `acts_as_list` is forcing the double call. I'll need to investigate that. Thanks again!

**Comment by ashwintastic** [comment]
For me, the method is being called from a different `it block` 

`it does Something do
  expect(Myclass).to receive(:my_method).and_return(nil)
  some_object.my_method
end

it does SomethingElse do
  expect(Myclass).to receive(:my_method).and_return(nil)
  some_object.my_method
end

ERROR:

           expected: 1 time with any arguments
           received: 2 times with any arguments

When I'm commenting one of the `it block` its working fine
`
