### ISSUE TITLE
Rspec does not initialize the session correctly. session_options missing.

### ISSUE THREAD

**Issue by kaelumania** [rspec/rspec-mocks#943]
We are using a customized  active record session store and it seems that the rspec mocks do not take care of the configuration correctly.

`Rails.application.config.session_store :active_record_store_with_url_parameter, session_key: '_my_session_key'`

**Comment by myronmarston** [comment]
rspec-mocks knows nothing about rails or activerecord and isn't responsible for taking care of configuring a session store correctly (how could it?).

What makes you think that RSpec is causing a problem in that part of your application?

**Comment by kaelumania** [comment]
But its definitely an testing issue and testing is done via rspec.

**Comment by JonRowe** [comment]
It's also done via Rails.

**Comment by JonRowe** [comment]
Hi @kaelumania, rspec-mocks has no integration with Rails directly, so at a minimum if this were to be an issue with rspec, which I don't believe it is, it would be an rspec-rails issue.

Neither rspec-mocks or rspec-rails actually configure Rails however, what is the symptom you are experiencing?

**Comment by kaelumania** [comment]
As already mentioned, I have to set the following rails configuration manually in a controller spec:

`Rails.application.config.session_store :active_record_store_with_url_parameter, session_key: '_my_session_key'`

Otherwise the controller session variable would not contain these information, which is in contrast to the behaviour when starting the rails server manually.

**Comment by JonRowe** [comment]
Well you didn't mention that you were doing that, you just pasted the code snippet without saying what the problem was.

So your problem is actually that your configuration isn't being loaded in the test environment? How are you loading Rails?

**Comment by kaelumania** [comment]
Its only the `session_key` which is part of the rails 'session_options' that is not being loaded correctly. The rails config does contain the `active_record_store_with_url_parameter`. What do you mean by how are you loading rails? I use `bundle exec rspec` or `spring rspec` or `bundle exec rails server`. I am more of a rails beginner than expert.

**Comment by JonRowe** [comment]
Ok from that I'll assume you're using a generated `spec_helper.rb` or `rails_helper.rb` from us, via our install generator (if you don't have one of those files then you probably have something setup wrong and we can chase that down) this now sounds like a rails issue, as we don't do anything to load the config, that's all rails. If RSpec is otherwise running rails tests happily it's no an issue our end.

**Comment by JonRowe** [comment]
As a background I'll point out that rspec (rspec-core, rspec-mocks, rspec-expectations and rspec-support) has zero knowledge of Rails, and rspec-rails which provides integration between rspec and rails is a thin shim around rails own test helpers, and it sounds like thats what is going wrong for you.

**Comment by kaelumania** [comment]
Yes, we are using a `spec_helper` file. Would you recommend to issue a bug at the `rspec-rails` or `rails` project and any ideas where to look (code)?

**Comment by JonRowe** [comment]
`rails`

**Comment by myronmarston** [comment]
How is the session store being configured in your dev and prod environments?  I can imagine it being set in `config/environments/development.rb` and `config/environments/production.rb`.  If that's the case, you'd need to set it in `config/environments/test.rb` as well.
