### ISSUE TITLE
Can't mock nested ActiveRecord scopes

### ISSUE THREAD

**Issue by ivanoblomov** [rspec/rspec-mocks#948]
Given a "sorted" scope that wraps two scopes "created_at" and "by_name":

```ruby
  scope :by_name, -> { order :name }
  scope :created_at, -> { order :created_at }
  scope :sorted, -> { created_at.by_name }
```
Mocking the nested scopes...

```ruby
before do
  expect(described_class).to receive(:created_at)
  expect(described_class).to receive(:by_name)
end
```

...and testing the wrapper scope in an example...

```ruby
it { expect(described_class.sorted).to eq [...] }
```

...results in nil pointer errors...

```ruby
     Failure/Error: expect(described_class.sorted)
     NoMethodError:
       undefined method `by_name' for nil:NilClass
```

The content of the subordinate scopes is irrelevant, only the fact that "sorted" wraps them matters.

**Comment by ivanoblomov** [comment]
My bad, returning the described_class in the mock fixes this:

```ruby
expect(described_class).to receive(:created_at).and_return(described_class)
```

**Comment by myronmarston** [comment]
This is by design.  [As documented](https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/configuring-responses) when you `expect` or `allow` a message, the default is to return `nil` when that message is received.

**Comment by myronmarston** [comment]
Cool, looks like you figured it out.

One thing I'd point out is that it's a bit of a smell to `expect` a query method (a method that returns a result rather than performing a side effect).  I generally try to use `expect` only with a commend (a method that performs a side effect rather than a query).  With a query, the caller winds up _doing_ something with the returned value (or at least it should -- otherwise why is it calling it?), and it generally is a less brittle approach to test that rather than expecting that the method was called.

**Comment by ivanoblomov** [comment]
Right on, thanks for the tip. I think your distinction between commands and queries is totally useful. In my case, I'm trying to decompose some rather complex SQL queries into smaller scopes, which I test explicitly. Then I just make sure the wrapper scopes are calling the correct constituent scopes.

It sounds like you're recommending I only test say, the reports that use the scopes rather than the scopes themselves? Interested in your perspective on this as obviously you guys have to give the theory and practice of testing a lot more thought.

**Comment by cupakromer** [comment]
> Then I just make sure the wrapper scopes are calling the correct constituent scopes.

Honestly, I'd caution against this. If necessary use a `shared_example` to "repeat spec behavior". Otherwise, your tests are extremely brittle to refactoring those "nested scopes".
