### ISSUE TITLE
Is RSpec::Mocks.with_temporary_scope suppose to work in before(:suite)?

### ISSUE THREAD

**Issue by redross** [rspec/rspec-mocks#966]
Hi, I've been checking out "[Factory Girl Seeds](https://github.com/evrone/factory_girl-seeds)" and encountered a problem. The gem author suggests creating records in `before(:suite)`. Which works fine for simple factories, but more advanced ones get in all kinds of trouble (resque jobs being enqueued, external services being called and not found etc.). Normally all of these are stubbed out in a `before(:each)` with stuff like MockRedis, but it seems that stubbing is not possible in the `before(:suite)` block.

Now searching through Google I found out about [RSpec::Mocks.with_temporary_scope](http://stackoverflow.com/questions/20218290/how-should-i-stub-a-method-globally-using-rspec/26621262#26621262) in SO answer about a similar problem for `before(:all)`.

I tried using `with_temporary_scope` in `before(:suite)`, but I still get the `undefined method "allow" for nil class` error. It does however work for `before(:all)` (though seeding in before all makes much less sense).

So:
* Is RSpec::Mocks.with_temporary_scope not suppose to work in before(:suite)?
or
* Do I have some configuration issues?

Thanks for the info :)

**Comment by myronmarston** [comment]
`RSpec::Mocks.with_temporary_scope` can be used in _any_ context but it doesn't automatically make the rspec-mocks API available in that context.  `RSpec::Mocks.with_temporary_scope` is concerned only with the setup/verify/teardown lifecycle of rspec-mocks, performing that lifecycle anywhere you want it to occur.  To make the rspec-mocks API available in a context, `RSpec::Mocks::ExampleMethods` needs to be included or extended in the appropriate place.  rspec-core should be doing this for `before(:suite)` hooks but it's not. You discovered a bug!  See rspec/rspec-core#1986.

For now, you can deal with this yourself doing something like:

``` ruby
RSpec.configure do |config|
  config.before(:suite) do
    RSpec::Mocks.with_temporary_scope do
      mocks_api_context = Object.new
      mocks_api_context.extend RSpec::Mocks::ExampleMethods
      mocks_api_context.instance_eval do
        # use the rspec-mocks API here.
      end
    end
  end
end
```

It's a hack, but a pretty clean one, and it relies only upon public rspec-mocks APIs so it's something that should work in all 3.x releases (and probably 4+, but 4.0 will have breaking changes of some sort).

Sorry for the trouble!

**Comment by redross** [comment]
> You discovered a bug!

Achievement unlocked :laughing: 

Thanks for your help, will try the "hack" :)

**Comment by myronmarston** [comment]
Closing in favor of @JonRowe's fix in rspec/rspec-core#1986.

**Comment by myronmarston** [comment]
rspec-core 3.3.1 has been released with a fix.

**Comment by redross** [comment]
Great! Thanks for taking care of this :bow:
