### ISSUE TITLE
have_received matcher fails with Minitest

### ISSUE THREAD

**Issue by randycoulman** [rspec/rspec-mocks#967]
I'm trying to use rspec-mock's spies in a Minitest (**not** `Minitest::Spec`) project and am running into an error that I don't know how to solve.

I'm using Minitest 5.7, rspec-mocks 3.2.1, and Ruby 2.1.3p342.

As near as I can tell, I'm not running into any conflicts between Minitest and rspec-mocks.  When I trace through the code, I seem to be hitting only methods in rspec-mocks.

When I run the example below, I get the following error. If I run an equivalent example written with RSpec, everything works as expected.

```
 1) Error:
SpyTest#test_accepts_invitation:
NoMethodError: undefined method `setup_expectation' for #<RSpec::Mocks::Matchers::HaveReceived:0xb8dae0cc>
    /usr/local/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.2.1/lib/rspec/mocks/targets.rb:45:in `define_matcher'
    /usr/local/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.2.1/lib/rspec/mocks/targets.rb:14:in `block in delegate_to'
    spies.rb:33:in `test_accepts_invitation'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

```ruby
require "minitest/autorun"
require "rspec/mocks"

class User
  def accept_invitation(invitation)
    invitation.accept
  end
end

module RSpecMocksIntegration
  include ::RSpec::Mocks::ExampleMethods

  def before_setup
    ::RSpec::Mocks.setup
    super
  end

  def after_teardown
    super
    ::RSpec::Mocks.verify
  ensure
    ::RSpec::Mocks.teardown
  end
end

class SpyTest < Minitest::Test
  include RSpecMocksIntegration
  
  def test_accepts_invitation
    invitation = spy("invitation")
    user = User.new
    user.accept_invitation(invitation)
    expect(invitation).to have_received(:accept)
  end
end
```

**Comment by myronmarston** [comment]
Thanks for reporting this!

The problem is that `have_received` implements the `rspec-expectations` matcher protocol, and returns an object that rspec-expectations knows how to work with...but that rspec-mocks doesn't know how to work with.  `expect` is an rspec-expectations method.   rspec-mocks implements a fallback definition of `expect` that allows `expect(x).to receive` to work (which isn't a normal expectation; it's setting the mock up to be verified at the end of the example) but rspec-mocks' fallback definition of `expect` doesn't understand normal matchers (such as `have_received`).

You can fix your problem by loading rspec-expectations and including `RSpec::Matchers`, which will cause rspec-expectations' more powerful `expect` to be used:

``` ruby
require "minitest/autorun"
require "rspec/mocks"
require 'rspec/expectations'

class User
  def accept_invitation(invitation)
    invitation.accept
  end
end

module RSpecMocksIntegration
  include ::RSpec::Mocks::ExampleMethods
  include ::RSpec::Matchers

  def before_setup
    ::RSpec::Mocks.setup
    super
  end

  def after_teardown
    super
    ::RSpec::Mocks.verify
  ensure
    ::RSpec::Mocks.teardown
  end
end

class SpyTest < Minitest::Test
  include RSpecMocksIntegration

  def test_accepts_invitation
    invitation = spy("invitation")
    user = User.new
    user.accept_invitation(invitation)
    expect(invitation).to have_received(:accept)
  end
end
```

We've definitely done a poor job of explaining this, and we need to improve it so that it explicitly tells you to include `RSpec::Matchers` if you try to use `have_received` without `RSpec::Expectations` loaded.  I'm going to think a bit about the best way to do that.

**Comment by randycoulman** [comment]
This looks like it should work.  I'll give it a shot when I get a chance.  Thanks!

**Comment by randycoulman** [comment]
Confirmed - this solves the problem nicely.  Thanks for your help!

**Comment by randycoulman** [comment]
I've continued to think about this issue and how it might be resolved.

As a short-term "fix", we could just raise some kind of error when attempting to use the `have_received` matcher without the support of rspec-expectations.  Also, update documentation to warn about this issue. I think I have an idea about how to do these, and I'll start working on a PR in this direction.

Ultimately, though, it seems like rspec-mocks is simply not fully functional in its current form without rspec-expectations.  As @myronmarston mentioned in #968, rspec-mocks version of `expect` is not as full-featured as the one in rspec-expectations.  I can think of a few ways to resolve this:

1. Bring in the more full-featured version of `expect` from rspec-expectations.  I'm not sure how hard this would be, but it would result in duplicate code in the two sub-projects, which is less than ideal.

2. Like 1, but move `expect` and its supporting infrastructure to rspec-support.  This might work, but might move rspec-support in the direction of becoming a monolithic package that contains most of rspec.  #513 talks about moving the argument matchers into rspec-support as well, and the same danger is raised there as well.

3. Make rspec-mocks depend on rspec-expectations.  I think this is ultimately the way to go, but there are problems doing that for rspec 3 as discussed in #513.

I'm willing to put in a bit of time to move one of these options forward, but I'd like some sense from the maintainers/community about which direction would be best.  For now, I'll see if I can put together the short-term fix as a PR.
