### ISSUE TITLE
Guide to contributing wiki page needed

### ISSUE THREAD

**Issue by lizrush** [rspec/rspec-mocks#986]
I'd love to see a guide for contributors to help folks get started. I found that I was a little uncertain about the expectations and we seemed to uncover some blind spots I had in the course of the PR review we did (ex: I didn't know how to generate the docs so I didn't catch my whitespace in the docs problem).

Potential contribution guide topics could include:
* Do you squash commits or leave all passing commits in tact no matter the size?
* Documentation: How to generate & update documentation on new additions or fixes
* Who are the maintainers/who to ping with questions
* What process & feedback should a contributor expect when making a PR?
* Checklist of todos (generate docs, run tests, etc) before submitting a PR

**Comment by JonRowe** [comment]
I'm pretty certain the wiki is editable by everyone, but alternatively how about drafting a `Contributing.md` we can point to from the read me, that way we could give feedback on it in a PR :)

**Comment by JackDanger** [comment]
@JonRowe It would probably be easier for someone who's already a contributor to the project to start the `Contributing.md` rather than someone who's totally new. Who would be a good person for us to ask to start such a document?

**Comment by myronmarston** [comment]
I'll take a stab at this.  I think it'll make sense to put it in the `rspec-dev` repo where it can be distributed to the other repos using the same mechanism we distribute our build scripts.

**Comment by myronmarston** [comment]
This is a great idea, BTW -- thanks for bringing it up, @lizrush!

**Comment by JonRowe** [comment]
@myronmarston you can probably use rspec/rspec-dev#125 as a basis too

**Comment by myronmarston** [comment]
OK, all repos now have a few files that explain the contribution process, and Github displays it when you open an issue or PR.

**Comment by lizrush** [comment]
Rad, thanks guys! The suggested contributions list is really great & the checklist in development.md will be super helpful for future contributors! :information_desk_person: :tada:
