### ISSUE TITLE
Making the hash_including matcher's failure message be more helpful

### ISSUE THREAD

**Issue by gabehollombe** [rspec/rspec-mocks#993]
Hello awesome RSpec team!

Recently, I was using hash_including in a test, checking for the presence of quite a few keys in the hash.  When my test failed, I noticed that it the failure message didn't make it super easy for me to detect which values from my expected hash were missing from the actual hash.  Is this something you'd welcome a pull request for?

Example gist showing the current behavior I'm talking about: https://gist.github.com/gabehollombe/1f39b5e95e283ba34314

**Comment by myronmarston** [comment]
What specifically do you have in mind for the improved output?  Can you paste a before/after example showing what is currently printed and what you'd like it to print instead?

**Comment by JonRowe** [comment]
>  Is this something you'd welcome a pull request for?

Absolutely, we actually do something a bit more advanced in `rspec-expectations` for the `a_hash_including` matcher but the argument matchers in mocks aren't as complicated. That might be a good place to start though however.

**Comment by JonRowe** [comment]
@myronmarston this gist shows the before, I think it's reasonable to do what we do with the matcher in expectations and print the diff of keys we're looking for rather than the whole hash

**Comment by gabehollombe** [comment]
@JonRowe That sounds good.  Could you point me at the codie in rspec-expectations that does the hash key diffs.  I think we want to diff the keys of the two hashes, but also the contents (since two hashes could have the same key but differ on values).  Anyway, looking at the rspec-expectations code you've already got will give me a good starting point.

**Comment by JonRowe** [comment]
I think reading rspec/rspec-expectations#780 would be a good place to start, its what implemented it on expectations I think
